import {test,expect} from '@playwright/test'
test('account-only file review imports private metadata with explicit correction and no ledger changes',async({page})=>{
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 const before=await(await page.request.get('/api/transactions')).json()
 await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Settings',exact:true}).click()
 await page.getByRole('tab',{name:'Accounts',exact:true}).click();await page.getByRole('button',{name:'Open Accounts',exact:true}).click();await page.getByText('Import an account discovery file',{exact:true}).click()
 await page.getByRole('button',{name:'Import discovered accounts',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Import discovered accounts',exact:true})
 const report={schema_version:1,source:'fnb-account-discovery',accounts:[{name:'Synthetic discovery account',bank_id:'******9876'},{name:'Existing synthetic',bank_id:'12345678901'}]}
 await dialog.getByLabel('Discovered account file').setInputFiles({name:'synthetic-accounts.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...report,password:'synthetic-secret'}))})
 await expect(dialog.getByRole('alert')).toContainText('valid FNB account discovery file')
 await dialog.getByLabel('Discovered account file').setInputFiles({name:'synthetic-accounts.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(report))})
 await expect(dialog.getByText('This account already exists; its settings are unchanged.',{exact:true})).toBeVisible()
 const row=dialog.locator('section.panel').first(),number=row.getByLabel('FNB account number',{exact:true})
 await row.getByRole('button',{name:'Add this account',exact:true}).click()
 await expect(number).toBeFocused();await expect(number).toHaveAttribute('aria-invalid','true')
 await number.fill('998877669876');await expect(number).not.toHaveAttribute('aria-invalid','true')
 await expect(row.getByRole('checkbox',{name:'Share with household budget members'})).not.toBeChecked()
 await row.getByRole('button',{name:'Add this account',exact:true}).click()
 await expect(row.getByText('Account added.',{exact:true})).toBeVisible()
 const accounts=await(await page.request.get('/api/accounts')).json()
 const added=accounts.find((a:any)=>a.bank_id==='998877669876')
 expect(added.name).toBe('Synthetic discovery account');expect(added.household).toBe(0);expect(added.balance_cents).toBeNull()
 expect(await(await page.request.get('/api/transactions')).json()).toEqual(before)
 await dialog.getByRole('button',{name:'Done',exact:true}).click()
 await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Accounts',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Synthetic discovery account',exact:true})).toBeVisible()
})
