import {test,expect,type Page} from '@playwright/test'
async function login(page:Page){await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()}
async function nav(page:Page,name:string,width:number){if(width===360&&!['Dashboard','Accounts','Transactions'].includes(name)){await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'More',exact:true}).click();await page.getByRole('navigation',{name:'More pages'}).getByRole('button',{name,exact:true}).click()}else await page.getByRole('navigation',{name:width===360?'Mobile navigation':'Main navigation',exact:true}).getByRole('button',{name,exact:true}).click()}
async function write(page:Page,path:string,body:unknown,method='POST'){const me=await (await page.request.get('/api/me')).json();const response=await page.request.fetch('/api'+path,{method,data:body,headers:{'X-CSRF-Token':me.csrf}});expect(response.ok(),await response.text()).toBe(true);return response.json()}
for(const width of [1440,360])test(`review navigation, drafts, metadata and filters at ${width}px`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:900});await login(page);await nav(page,'Transactions',width)
 const result=await (await page.request.get('/api/transactions?id=5')).json(),t=result.items[0]
 await write(page,'/transactions/5',{version:t.version,date:t.date,amount_cents:t.amount_cents,description:t.description,is_transfer:false,assignment:'auto',allocations:[{category_id:null,amount_cents:t.amount_cents}]},'PUT')
 const current=(await (await page.request.get('/api/transactions?id=5')).json()).items[0];await write(page,'/transactions/seen',{seen:false,items:[{id:5,version:current.version}]});await page.getByRole('tab',{name:/Needs review/}).click();await page.locator('.transaction-detail').filter({hasText:t.description}).click()
 const editor=page.getByRole('dialog',{name:'Transaction #5',exact:true});await expect(editor).toBeVisible()
 if(!await editor.getByLabel('Transaction note',{exact:true}).isVisible())await editor.locator('summary').filter({hasText:'Notes, merchant and tags'}).click();await editor.getByLabel('Transaction note',{exact:true}).fill('Synthetic draft '+width);await page.keyboard.press('Escape')
 const guard=page.getByRole('dialog',{name:'Unsaved changes',exact:true});await expect(guard).toBeVisible();await guard.getByRole('button',{name:'Stay here'}).click();await expect(editor.getByLabel('Transaction note',{exact:true})).toHaveValue('Synthetic draft '+width)
 await editor.getByRole('button',{name:'New merchant',exact:true}).click();const merchant=page.getByRole('dialog',{name:'New merchant',exact:true});await merchant.getByLabel('Name',{exact:true}).fill('Synthetic shop '+width);await merchant.getByRole('button',{name:'Create and select'}).click()
 await editor.getByRole('button',{name:'New tag',exact:true}).click();const tag=page.getByRole('dialog',{name:'New tag',exact:true});await tag.getByLabel('Name',{exact:true}).fill('Synthetic '+width);await tag.getByRole('button',{name:'Create and select'}).click()
 await editor.getByRole('button',{name:'Category Uncategorized',exact:true}).click();const picker=page.getByRole('dialog',{name:'Select category',exact:true});await picker.getByRole('button',{name:/Groceries Expense/}).first().click()
 await editor.getByRole('button',{name:'Save and next',exact:true}).click();await expect(page.getByRole('dialog',{name:'Review complete'})).toBeVisible();await page.keyboard.press('Escape')
 const saved=(await (await page.request.get('/api/transactions?id=5')).json()).items[0];expect(saved.note).toBe('Synthetic draft '+width);expect(saved.tags.some((tag:any)=>tag.name==='Synthetic '+width)).toBe(true);expect(saved.seen).toBe(1)
 await page.getByRole('tab',{name:'All transactions',exact:true}).click();await page.getByRole('button',{name:'Filters',exact:true}).click();await page.getByLabel('From date',{exact:true}).fill('2026-10-25');await page.getByLabel('To date',{exact:true}).fill('2026-10-25');await expect(page.locator('.transaction-detail')).toHaveCount(1)
 await page.getByRole('button',{name:'Clear filters',exact:true}).click();await expect(page.locator('.transaction-detail')).toHaveCount(5)
 await page.locator('.transaction-detail').filter({hasText:'Market groceries'}).click();const second=page.getByRole('dialog',{name:'Transaction #2',exact:true});await expect(second.getByRole('button',{name:'Next',exact:true})).toBeEnabled();await second.getByRole('button',{name:'Next',exact:true}).click();await expect(page.getByRole('dialog',{name:'Transaction #1',exact:true})).toBeVisible();await page.keyboard.press('Escape')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([])
})
for(const width of [1440,360])test(`budget reports, rebalancing and account health at ${width}px`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:900});await login(page)
 await expect(page.getByLabel('Budget periods',{exact:true})).toBeVisible();await page.getByLabel('Sort budgets',{exact:true}).selectOption('remaining')
 await nav(page,'Budgets',width);await expect(page.getByRole('tab',{name:'Trends & reports'})).toBeVisible();await page.getByLabel('Actions for October 2026',{exact:true}).click()
 await page.getByRole('button',{name:'Rebalance',exact:true}).click();const modal=page.getByRole('dialog',{name:/Rebalance/});await modal.getByLabel('From',{exact:true}).selectOption('0');await modal.getByLabel('To',{exact:true}).selectOption('1');await modal.getByLabel('Amount to move',{exact:true}).fill('10.00');await modal.getByRole('button',{name:'Preview rebalance'}).click();await expect(modal.getByRole('button',{name:'Apply rebalance'})).toBeEnabled();await modal.getByRole('button',{name:'Apply rebalance'}).click();await expect(modal).not.toBeVisible()
 await page.getByRole('tab',{name:'Trends & reports'}).click();await expect(page.getByText('Average spending per saved period:',{exact:false})).toBeVisible();await page.getByLabel('Budget year',{exact:true}).fill('2026');await expect(page.getByText('Average spending per saved period:',{exact:false})).toBeVisible()
 await nav(page,'Accounts',width);await page.locator('.secondary-section > summary').click();await expect(page.getByRole('heading',{name:'Transaction import health'})).toBeVisible();await expect(page.getByText('Last successful transaction import/check: Never').first()).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([])
})
test('bulk category preview and category archive retain history',async({page})=>{
 await login(page);await nav(page,'Transactions',1440);await page.getByRole('checkbox',{name:'Select transactions on this page',exact:true}).check();await page.getByRole('button',{name:'Edit selected (5)'}).click();const bulk=page.getByRole('dialog',{name:'Edit 5 selected transactions'});await bulk.getByLabel('Change',{exact:true}).selectOption('add_tag');await bulk.getByLabel('Tag name',{exact:true}).fill('Batch test');await bulk.getByRole('button',{name:'Preview changes'}).click();await expect(bulk.getByRole('button',{name:'Apply preview'})).toBeEnabled();await bulk.getByRole('button',{name:'Apply preview'}).click();await expect(bulk).not.toBeVisible()
 const created=await write(page,'/categories',{name:'Archive synthetic category',kind:'expense'});await nav(page,'Categories',1440);await page.getByRole('button',{name:'Edit Archive synthetic category',exact:true}).click();const cat=page.getByRole('dialog',{name:'Edit category · Archive synthetic category'});await cat.getByLabel('Archived',{exact:true}).check();await cat.getByRole('button',{name:'Save category'}).click();await expect(cat).not.toBeVisible();const row=(await (await page.request.get('/api/categories?page=0&id='+created.id)).json()).items[0];expect(row.archived).toBe(1)
 await page.getByRole('tab',{name:'Merchant rules',exact:true}).click();await page.getByRole('button',{name:'Add merchant rule'}).click();const rule=page.getByRole('dialog',{name:'New merchant rule'});await rule.getByLabel('Account',{exact:true}).selectOption('1');await rule.getByLabel('New merchant name',{exact:true}).fill('Rule synthetic merchant');await rule.getByLabel('Description contains',{exact:true}).fill('Fuel');await rule.getByRole('button',{name:'Save rule'}).click();await expect(rule).not.toBeVisible();await page.getByLabel('Actions for merchant rule Rule synthetic merchant',{exact:true}).click();await page.getByRole('button',{name:'Preview unnamed transactions'}).click();await expect(page.getByRole('dialog',{name:'Matching unnamed transactions'})).toBeVisible()
})

test('active period daily guide and complete filtered export',async({page})=>{
 await page.clock.setFixedTime(new Date('2026-10-25T10:00:00+02:00'));await login(page)
 const d=await (await page.request.get('/api/dashboard?period=1')).json()
 const guide=page.getByText('Daily budget guide:',{exact:false});await expect(guide).toBeVisible()
 const expected=new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(Math.floor(d.remaining_cents/26)/100);await expect(guide).toContainText(expected)
 await page.getByLabel('Accounts',{exact:true}).selectOption('3');await expect(guide).not.toBeVisible()
 await page.getByLabel('Accounts',{exact:true}).selectOption('');await expect(guide).toBeVisible()
 await page.clock.setFixedTime(new Date('2026-12-01T10:00:00+02:00'));await page.reload();await expect(guide).not.toBeVisible()
 await nav(page,'Transactions',1440);await page.getByLabel('Transaction actions',{exact:true}).click();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export filtered transactions'}).click();expect((await downloadPromise).suggestedFilename()).toBe('transactions.zip')
})
