import {test,expect} from '@playwright/test'

for(const theme of ['light','dark'])for(const width of [1280,360])test(`group/category budgets and handoff ${theme} ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900})
 await page.addInitScript(theme=>localStorage.setItem('finance-theme',theme),theme)
 await page.route('**/api/dashboard?**',async route=>{
  const response=await route.fetch(),body=await response.json(),account=new URL(route.request().url()).searchParams.get('account')
  const category={id:1,name:'Groceries',spent_cents:6000,pending_cents:0,total_spent_cents:9000,target_cents:account?0:10000}
  await route.fulfill({json:{...body,group_total:3,spending_groups:[{id:1,name:'Day-to-day',color:'teal',target_cents:10000,spent_cents:6000,category_total:1,categories:[category]},{id:2,name:'Exceptions with a long spending group name',color:'rose',target_cents:2000,spent_cents:3000,category_total:1,categories:[{...category,target_cents:2000,spent_cents:3000}]},{id:0,name:'No spending group',color:'slate',spent_cents:2000,category_total:1,categories:[{id:0,name:'Needs category',spent_cents:2000,pending_cents:2000}]}]}})
 })
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Spending by group'})).toBeVisible()
 const sortBox=await page.getByLabel('Sort budgets',{exact:true}).boundingBox(),editBox=await page.getByLabel("Spending actions", { exact: true }).boundingBox()
 expect(Math.abs(sortBox!.y-editBox!.y)).toBeLessThan(2)
 expect(Math.abs(sortBox!.height-editBox!.height)).toBeLessThan(2)
 const buckets=page.getByRole('region',{name:'Spending by group',exact:true}).locator('.spending-bucket:not(.income-bucket)')
 await expect(buckets).toHaveCount(3)
 const spending=page.getByRole('region',{name:'Spending by group',exact:true})
 const next=page.getByRole('region',{name:'Next steps',exact:true})
 const balances=page.getByRole('region',{name:'Bank-reported balances',exact:true})
 const mainBox=await spending.boundingBox(),supportBox=await page.locator('.dashboard-support').boundingBox()
 expect(Math.abs(mainBox!.x-supportBox!.x)).toBeLessThan(2)
 expect(Math.abs(mainBox!.width-supportBox!.width)).toBeLessThan(2)
 const nextBox=await next.boundingBox(),balanceBox=await balances.boundingBox()
 expect(nextBox!.y).toBeGreaterThanOrEqual(mainBox!.y+mainBox!.height)
 if(width===1280){expect(Math.abs(nextBox!.y-balanceBox!.y)).toBeLessThan(2);expect(Math.abs(nextBox!.height-balanceBox!.height)).toBeLessThan(2)}
 else expect(balanceBox!.y).toBeGreaterThanOrEqual(nextBox!.y+nextBox!.height)

 await expect(buckets.first().locator('.bucket-category')).toBeHidden()
 await buckets.first().locator(':scope > summary').focus();await page.keyboard.press('Enter')
 await buckets.nth(1).locator(':scope > summary').click()
 await expect(buckets.first().getByText('Groceries',{exact:true})).toBeVisible()
 await expect(buckets.nth(1).getByText('Groceries',{exact:true})).toBeVisible()
 await expect(buckets.first().getByText('Left',{exact:true}).first()).toBeVisible()
 await expect(buckets.first().getByRole('progressbar')).toHaveCount(2)
 await expect(buckets.nth(1).getByText('Over budget',{exact:true}).first()).toBeVisible()
 await buckets.nth(2).locator(':scope > summary').click();await expect(buckets.nth(2).getByText('Needs category',{exact:true})).toBeVisible()
 if(width===1280){
  const summary=await buckets.first().locator('summary .budget-figure').first().boundingBox(),child=await buckets.first().locator('.bucket-category .budget-figure').first().boundingBox()
  expect(Math.abs(summary!.x-child!.x)).toBeLessThan(2)
 }
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByLabel("Spending actions", { exact: true }).click(); await page.getByRole('button',{name:'Edit budgets',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Budgets',exact:true})).toBeVisible()
 const group=page.getByRole('region',{name:'No spending group budget',exact:true})
 await group.locator('.budget-group-summary').click()
 await group.getByRole('button',{name:'Edit budget for Groceries in No spending group',exact:true}).click()
 const modal=page.getByRole('dialog',{name:'Edit budget · Groceries',exact:true})
 await expect(modal.getByLabel('Budget amount',{exact:true})).toHaveValue('4500.00')
 await page.keyboard.press('Escape')
 if(width===1280)await expect(page.getByText('Selected period',{exact:true})).toBeVisible()
 else await expect(page.getByText('Selected period',{exact:true})).toBeHidden()
 await page.locator('.budget-period-head .toolbar-actions>details>summary').first().click()
 await page.getByRole('button',{name:'View spending',exact:true}).click()
 await expect(page.getByLabel('Budget period',{exact:true})).toHaveValue('1')
 await page.getByLabel('Accounts',{exact:true}).selectOption('3')
 await expect(page.getByRole('button',{name:'Edit budgets',exact:true})).toHaveCount(0)
 await buckets.first().locator(':scope > summary').click()
 await expect(buckets.first().getByText('Budget',{exact:true})).toHaveCount(0)
})

test('limits remain available before spending begins',async({page})=>{
 await page.route('**/api/dashboard?**',async route=>{const response=await route.fetch(),body=await response.json();await route.fulfill({json:{...body,spending_groups:[],group_total:0}})})
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByText('No spending yet',{exact:true})).toBeVisible()
 const spendingBox=await page.locator('.spending-panel').boundingBox(),supportBox=await page.locator('.dashboard-support').boundingBox()
 expect(supportBox!.y).toBeGreaterThanOrEqual(spendingBox!.y+spendingBox!.height)
 expect(Math.abs(supportBox!.width-spendingBox!.width)).toBeLessThan(2)
 await page.locator('.category-limits-summary > summary').click()
 await expect(page.getByRole('progressbar',{name:'Groceries budget used'})).toBeVisible()
 await page.getByRole('button',{name:'Set up a budget',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Budgets',exact:true})).toBeVisible()
})

for(const width of [1280,360])test(`build independent category budgets and inherited group totals at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900})
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await page.getByLabel("Spending actions", { exact: true }).click(); await page.getByRole('button',{name:'Edit budgets',exact:true}).click()
 for(const [id,name,amount] of [['1','Day-to-day','1000.00'],['4','Exceptions','300.00']]){
  const builder=page.locator('.budget-groups-view')
  await builder.getByRole('button',{name:'Add group',exact:true}).click()
  const picker=page.getByRole('dialog',{name:'Add budget group',exact:true})
  await picker.getByLabel('Spending group',{exact:true}).selectOption(id)
  await picker.getByRole('button',{name:'Add group to budget',exact:true}).click()
  await builder.getByRole('button',{name:'Add category to '+name,exact:true}).click()
  const category=page.getByRole('dialog',{name:'Add category · '+name,exact:true})
  const existing=(await (await page.request.get('/api/periods/1/targets?group='+id+'&budget_only=1&id=3')).json()).items[0]
  await category.getByLabel('Category',{exact:true}).selectOption('3')
  await expect(category.getByLabel('Budget amount',{exact:true})).toBeEnabled()
  await category.getByLabel('Budget amount',{exact:true}).fill(amount)
  await expect(category.getByLabel('Use this category in')).toHaveValue(existing?.carry_forward?'future':'once')
  if(id==='1')await category.getByLabel('Use this category in').selectOption('future')
  await category.getByRole('button',{name:'Save changes',exact:true}).click()
 }
 const builder=page.locator('.budget-groups-view')
 await builder.getByRole('button',{name:'Add category to Day-to-day',exact:true}).click()
 const add=page.getByRole('dialog',{name:'Add category · Day-to-day',exact:true})
 await add.getByLabel('Category',{exact:true}).selectOption('2')
 await expect(add.getByLabel('Budget amount',{exact:true})).toBeEnabled()
 await add.getByLabel('Budget amount',{exact:true}).fill('200.00')
 await add.getByRole('button',{name:'Save changes',exact:true}).click()
 await expect(add).toHaveCount(0)
 const built=builder.getByRole('region',{name:'Day-to-day budget',exact:true})
 await expect.poll(async()=>(await built.locator('.budget-group-amount').innerText()).replace(/[^0-9]/g,'')).toBe('120000')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.locator('.budget-period-head .toolbar-actions>details>summary').first().click()
 await page.getByRole('button',{name:'View spending',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 const day=page.locator('.spending-bucket:not(.income-bucket)').filter({has:page.locator('.bucket-name strong',{hasText:'Day-to-day'})})
 const exception=page.locator('.spending-bucket:not(.income-bucket)').filter({has:page.locator('.bucket-name strong',{hasText:'Exceptions'})})
 await expect(day.locator(':scope > summary progress')).toHaveAttribute('max','120000')
 await expect(exception.locator(':scope > summary progress')).toHaveAttribute('max','30000')
 await day.locator(':scope > summary').click();await exception.locator(':scope > summary').click()
 await expect(day.getByText('Eating out',{exact:true})).toBeVisible()
 await expect(exception.getByText('Eating out',{exact:true})).toBeVisible()
 await expect(day.getByRole('progressbar',{name:'Day-to-day · Eating out budget used'})).toHaveAttribute('max','100000')
 await expect(exception.getByRole('progressbar',{name:'Exceptions · Eating out budget used'})).toHaveAttribute('max','30000')
})
