import {test,expect,type Page} from '@playwright/test'
async function go(page:Page,name:string,width:number){
 if(width<=760&&!['Dashboard','Transactions','Review'].includes(name)){
  await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'More',exact:true}).click()
  await page.getByRole('navigation',{name:'More pages'}).getByRole('button',{name,exact:true}).click()
 }else await page.getByRole('navigation',{name:width<=760?'Mobile navigation':'Main navigation',exact:true}).getByRole('button',{name,exact:true}).click()
 await expect(page.getByRole('heading',{name,level:1,exact:true})).toBeVisible()
}
for(const {width,theme} of [{width:1440,theme:'light'},{width:900,theme:'dark'},{width:390,theme:'dark'},{width:360,theme:'light'}])test(`density, progressive filters and disclosure states ${width} ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:800})
 await page.addInitScript(t=>localStorage.setItem('finance-theme',t),theme)
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.locator('.dashboard-overview')).toBeVisible()
 await go(page,'Transactions',width)
 await expect(page.locator('.transaction-detail').first()).toBeVisible()
 if(width>=900){const row=page.locator('.transaction-row').filter({hasText:'Market groceries'});const bounds=await row.boundingBox();expect(bounds!.height).toBeGreaterThanOrEqual(64);expect(bounds!.height).toBeLessThanOrEqual(92)}
 await page.screenshot({path:test.info().outputPath('transactions.png')})
 await page.getByRole('button',{name:'Filters',exact:true}).click()
 await expect(page.getByLabel('From date',{exact:true})).toBeHidden()
 await expect(page.getByLabel('Filter by category',{exact:true})).toBeVisible()
 await page.screenshot({path:test.info().outputPath('filters.png')})
 const more=page.locator('.advanced-transaction-filters>summary')
 const closed=await more.evaluate(el=>getComputedStyle(el,'::after').transform)
 expect(closed).not.toBe('none')
 await more.click();const opened=await more.evaluate(el=>getComputedStyle(el,'::after').transform);expect(opened).not.toBe(closed)
 await page.getByLabel('From date',{exact:true}).fill('2026-10-20');await page.getByLabel('To date',{exact:true}).fill('2026-10-26')
 await more.click();await expect(more).toContainText('2 active');await expect(page.getByLabel('From date',{exact:true})).toBeHidden()
 await page.getByRole('button',{name:'Filters (2)',exact:true}).click()
 await page.locator('.transaction-detail').filter({hasText:'Market groceries'}).click()
 const editor=page.getByRole('dialog',{name:'Transaction #2',exact:true})
 await expect(editor.getByRole('region',{name:'Transaction summary'})).toContainText('Market groceries')
 await expect(editor.getByLabel('Category',{exact:true})).toBeInViewport()
 await expect(editor.getByRole('heading',{name:'Category',exact:true})).toHaveCount(0)
 await page.screenshot({path:test.info().outputPath('editor.png')})
 await editor.getByLabel('Close',{exact:true}).click()
 await go(page,'Accounts',width)
 const tools=page.getByRole('region',{name:'Account tools'})
 await expect(tools).toBeVisible();const toolBounds=await tools.boundingBox();expect(toolBounds!.height).toBeLessThanOrEqual(190)
 const disclosure=tools.locator('.secondary-section>summary');const initial=await disclosure.evaluate(el=>getComputedStyle(el,'::after').transform)
 await disclosure.click();expect(await disclosure.evaluate(el=>getComputedStyle(el,'::after').transform)).not.toBe(initial)
 await disclosure.click()
 await go(page,'Settings',width)
 const save=page.getByRole('button',{name:'Save default',exact:true});await expect(save).toBeVisible()
 const saveBounds=await save.boundingBox();expect(saveBounds!.height).toBeGreaterThanOrEqual(44)
 if(width>=900)expect(saveBounds!.width).toBeLessThan(220)
 await page.screenshot({path:test.info().outputPath('settings.png'),fullPage:true})
 for(const name of ['Accounts','Categories','Budgets','Dashboard']){
  await go(page,name,width)
  const heading=page.getByRole('heading',{name,level:1,exact:true})
  expect(await heading.evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBeLessThanOrEqual(28)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 }
})
test('empty creation has one owner and import history does not repeat setup',async({page})=>{
 await page.route('**/api/categories?**',route=>route.fulfill({json:{items:[],total:0,list_version:'empty'}}))
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await go(page,'Categories',1440)
 await expect(page.getByRole('region',{name:'Create your first categories'})).toBeVisible()
 await expect(page.getByRole('button',{name:'Add category',exact:true})).toHaveCount(1)
 await page.getByRole('button',{name:'Add category',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('dialog').getByLabel('Close',{exact:true}).click()
 await go(page,'Transactions',1440);await page.getByRole('tab',{name:/^Import activity/}).click()
 const empty=page.getByRole('region',{name:'No import activity yet'});await expect(empty).toBeVisible();await expect(empty.getByRole('button')).toHaveCount(0)
 await expect(page.getByRole('button',{name:'Connect FNB',exact:true})).toHaveCount(1)
 await page.locator('.upload-panel>summary').click();await expect(page.getByRole('button',{name:'Choose FNB export files',exact:true})).toBeVisible()
})
