import {test,expect} from '@playwright/test'
for(const width of [1440,900,390,360])test(`compact transaction editor ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.addInitScript(t=>localStorage.setItem('finance-theme',t),width===390||width===900?'dark':'light');await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible();const me=await (await page.request.get('/api/me')).json(),t=(await (await page.request.get('/api/transactions?id=5')).json()).items[0];await page.request.put('/api/transactions/5',{headers:{'X-CSRF-Token':me.csrf},data:{version:t.version,date:t.date,amount_cents:t.amount_cents,description:t.description,assignment:'auto',is_transfer:false,allocations:[{category_id:null,amount_cents:t.amount_cents}]}});await page.getByRole('navigation',{name:width<=760?'Mobile navigation':'Main navigation',exact:true}).getByRole('button',{name:'Transactions',exact:true}).click();await expect(page.getByText('Loading transactions',{exact:true})).toBeHidden();await page.locator('.transaction-detail').filter({hasText:'Synthetic long description'}).click();const editor=page.getByRole('dialog',{name:'Transaction #5',exact:true});await expect(editor.getByLabel('Category',{exact:true})).toBeVisible();await expect(editor.getByLabel('Amount',{exact:true})).toHaveCount(0)

 const classification=editor.getByRole('region',{name:'Classification',exact:true});
 const add=classification.getByRole('button',{name:'Add split',exact:true});
 await expect(add).toHaveCount(1);
 const head=(await classification.locator('.transaction-classification-head').boundingBox())!,action=(await add.boundingBox())!;
 expect(Math.abs(action.x+action.width-head.x-head.width)).toBeLessThan(2);
 expect(action.height).toBeGreaterThanOrEqual(44);
 const group=(await editor.getByLabel('Spending group',{exact:true}).boundingBox())!,category=(await editor.getByLabel('Category',{exact:true}).boundingBox())!;
 expect(Math.abs(group.x-category.x)).toBeLessThan(2);
 expect(Math.abs(group.width-category.width)).toBeLessThan(2);
 expect(category.y).toBeGreaterThan(group.y+group.height);
 expect(category.y-group.y-group.height).toBeLessThan(50);
 expect(action.y+action.height).toBeLessThanOrEqual(group.y);
 await editor.getByLabel('Signed amount (ZAR)',{exact:true}).fill('-1250.00');await editor.getByRole('button',{name:'Add split',exact:true}).click();if(width<=700){const split=(await editor.getByLabel('Category 1',{exact:true}).boundingBox())!;expect(Math.abs(split.width-group.width)).toBeLessThan(2)};await editor.getByLabel('Amount',{exact:true}).nth(0).fill('-750.00');await editor.getByLabel('Amount',{exact:true}).nth(1).fill('-500.00');await editor.getByRole('button',{name:'Save changes',exact:true}).click();await expect(editor).toBeHidden();await expect(page.getByText('Loading transactions',{exact:true})).toBeHidden();await page.locator('.transaction-detail').filter({hasText:'Synthetic long description'}).click();await expect(editor.getByLabel('Amount',{exact:true}).nth(0)).toHaveValue('-750.00');await editor.getByLabel('Amount',{exact:true}).nth(1).fill('-400.00');await editor.getByRole('button',{name:'Save changes',exact:true}).click();await expect(editor).toBeVisible();await expect(editor.getByLabel('Amount',{exact:true}).nth(1)).toHaveAttribute('aria-invalid','true');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await editor.getByLabel('Remove allocation 2',{exact:true}).click();await editor.getByLabel('Amount',{exact:true}).fill('-1250.00');await editor.getByRole('button',{name:'Save changes',exact:true}).click();await expect(editor).toBeHidden()
})
