import {test,expect,type Page} from '@playwright/test'
async function navigate(page:Page,name:string,width:number){
 if(width<=760&&!['Dashboard','Transactions','Review'].includes(name)){
  await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'More',exact:true}).click()
  await page.getByRole('navigation',{name:'More pages'}).getByRole('button',{name,exact:true}).click()
 }else await page.getByRole('navigation',{name:width<=760?'Mobile navigation':'Main navigation',exact:true}).getByRole('button',{name,exact:true}).click()
}
async function fits(page:Page){
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 for(const action of await page.locator('.empty-actions button:visible').all()){
  const box=await action.boundingBox();expect(box!.height).toBeGreaterThanOrEqual(44)
  expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(page.viewportSize()!.width+1)
 }
}
for(const {width,theme} of [{width:360,theme:'light'},{width:390,theme:'dark'},{width:768,theme:'light'},{width:1440,theme:'dark'}])test(`intentional empty-state journeys at ${width}px ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:800})
 await page.addInitScript(theme=>localStorage.setItem('finance-theme',theme),theme)
 await page.route('**/api/transactions?**',route=>route.fulfill({json:{items:[],total:0,more:false,list_version:'synthetic-empty'}}))
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 await navigate(page,'Transactions',width)
 const first=page.getByRole('region',{name:'Your transactions start here',exact:true})
 await expect(first).toBeVisible();await fits(page)
 await page.screenshot({path:test.info().outputPath('first-use.png'),fullPage:true})
 await first.getByRole('button',{name:'Import transactions',exact:true}).click()
 await expect(page.getByRole('tab',{name:/^Import activity/})).toHaveAttribute('aria-selected','true')
 await page.locator('.upload-panel>summary').click()
 await expect(page.getByRole('button',{name:'Choose FNB export files',exact:true})).toBeVisible()
 await expect(page.locator('.upload-panel')).toHaveAttribute('open','')
 await page.getByRole('tab',{name:/^Needs review/}).click()
 const complete=page.getByRole('region',{name:"You're all caught up",exact:true})
 await expect(complete).toBeVisible()
 await page.screenshot({path:test.info().outputPath('review-complete.png'),fullPage:true})
 await expect(complete.getByRole('button',{name:'Clear filters'})).toHaveCount(0)
 await page.getByRole('searchbox',{name:'Search transactions'}).fill('restricted review search')
 await expect(page.getByRole('region',{name:'No transactions found',exact:true})).toBeVisible()
 await expect(complete).toHaveCount(0)
 await page.getByRole('searchbox',{name:'Search transactions'}).fill('')
 await expect(complete).toBeVisible()
 await complete.getByRole('button',{name:'View all transactions',exact:true}).click()
 await expect(page.getByRole('tab',{name:'All transactions',exact:true})).toHaveAttribute('aria-selected','true')
 await expect(first).toBeVisible()
 await page.getByRole('searchbox',{name:'Search transactions'}).fill('nonexistent synthetic merchant')
 const filtered=page.getByRole('region',{name:'No transactions found',exact:true})
 await expect(filtered).toBeVisible();await fits(page)
 await filtered.getByRole('button',{name:'Clear filters',exact:true}).click()
 await expect(first).toBeVisible();await expect(page.getByRole('searchbox',{name:'Search transactions'})).toHaveValue('')
 await page.route('**/api/categories?**',route=>route.fulfill({json:{items:[],total:0,more:false,list_version:'empty-categories'}}))
 await navigate(page,'Categories',width)
 const categories=page.getByRole('region',{name:'Create your first categories',exact:true})
 await expect(categories).toBeVisible();await fits(page)
 await page.screenshot({path:test.info().outputPath('empty-categories.png'),fullPage:true})
 await categories.getByRole('button',{name:'Add category',exact:true}).click()
 const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible()
 await page.emulateMedia({reducedMotion:'reduce'})
 await expect(dialog).toHaveCSS('animation-name','none')
 await expect(dialog.getByRole('button',{name:'Close',exact:true})).toHaveCSS('transition-duration','0s')
 await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0)
 await expect(categories.getByRole('button',{name:'Add category',exact:true})).toBeFocused()
})
test('dashboard failure offers recovery without showing a first-use state',async({page})=>{
 let fail=true
 await page.route('**/api/dashboard?**',async route=>{if(fail)await route.fulfill({status:503,json:{error:'Temporarily unavailable'}});else await route.continue()})
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 const error=page.getByRole('region',{name:'Dashboard unavailable',exact:true});await expect(error).toBeVisible()
 await expect(page.getByRole('region',{name:'No spending yet'})).toHaveCount(0)
 fail=false;await error.getByRole('button',{name:'Retry dashboard',exact:true}).click()
 await expect(page.getByRole('region',{name:'Period totals',exact:true})).toBeVisible();await expect(error).toHaveCount(0)
})

test('pending actions keep their name and width and prevent repeated submissions',async({page})=>{
 let release!:()=>void
 const held=new Promise<void>(resolve=>{release=resolve})
 await page.route('**/api/login',async route=>{await held;await route.continue()})
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 const button=page.getByRole('button',{name:/^Sign(ing)? in$/}),before=await button.boundingBox()
 await button.click();await expect(button).toHaveAttribute('aria-busy','true');await expect(button).toBeDisabled()
 const after=await button.boundingBox();expect(after!.width).toBeCloseTo(before!.width,1);expect(after!.height).toBeCloseTo(before!.height,1)
 release();await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
})
