import {test,expect} from '@playwright/test'
for(const {width,motion} of [{width:1440,motion:'no-preference'},{width:1440,motion:'reduce'},{width:390,motion:'no-preference'},{width:390,motion:'reduce'}] as const)test(`organized filters and contained merchant search ${width} ${motion}`,async({page})=>{
 await page.setViewportSize({width,height:850});await page.emulateMedia({reducedMotion:motion})
 await page.route('**/api/labels?kind=merchant*',route=>{
  const params=new URL(route.request().url()).searchParams,q=params.get('q')||'',id=params.get('id')
  const all=Array.from({length:75},(_,i)=>({id:9001+i,name:'Shop '+(i+1),account_name:'Everyday account'})).filter(row=>id?String(row.id)===id:row.name.toLowerCase().includes(q.toLowerCase()))
  const offset=Number(params.get('page')||0)*50
  return route.fulfill({json:{items:all.slice(offset,offset+50),total:all.length,list_version:'synthetic'}})
 })
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await page.getByRole('navigation',{name:width<760?'Mobile navigation':'Main navigation',exact:true}).getByRole('button',{name:'Transactions',exact:true}).click()
 const tools=page.locator('.ledger-tools');await expect(tools.getByRole('button',{name:'Import transactions',exact:true})).toBeHidden()
 await page.getByLabel('Transaction actions',{exact:true}).click();await expect(tools.getByRole('button',{name:'Import transactions',exact:true})).toBeVisible();await page.keyboard.press('Escape')
 await page.getByRole('button',{name:'Filters',exact:true}).click()
 const reveal=page.locator('.transaction-filter-reveal')
 await expect(reveal).toHaveAttribute('aria-hidden','false')
 await reveal.evaluate(el=>Promise.all(el.getAnimations({subtree:true}).map(animation=>animation.finished.catch(()=>{}))))
 const advanced=page.locator('.advanced-transaction-filters')
 await advanced.locator(':scope>summary').click();await expect(advanced).toHaveAttribute('open','')
 const minimum=page.getByLabel('Minimum signed amount',{exact:true}),maximum=page.getByLabel('Maximum signed amount',{exact:true})
 await expect(minimum).toBeVisible();await expect(maximum).toBeVisible()
 await expect.poll(async()=>{const a=await minimum.boundingBox(),b=await maximum.boundingBox();return Math.abs(a!.y-b!.y)}).toBeLessThanOrEqual(1)
 const merchant=page.getByLabel('Merchant',{exact:true}),tag=page.getByLabel('Tag',{exact:true})
 const find=merchant;await expect(find).toBeVisible();await expect(page.getByText('Find more merchant options',{exact:true})).toHaveCount(0)
 await page.getByRole('region',{name:'Transaction filters',exact:true}).evaluate(el=>Promise.all(el.getAnimations({subtree:true}).map(animation=>animation.finished.catch(()=>{}))))
 const original=await tag.evaluate(el=>el.getBoundingClientRect().top+scrollY)
 await page.screenshot({path:test.info().outputPath('organized-filters.png'),fullPage:true})
 await find.click();const search=page.getByRole('dialog',{name:'Select merchant',exact:true});await expect(search).toBeVisible()
 await page.keyboard.press('Escape');await expect(search).toBeHidden();await expect(page.getByRole('button',{name:'Filters',exact:true})).toHaveAttribute('aria-expanded','true');await find.click();await expect(search).toBeVisible()
 const underneath=await tag.evaluate(el=>el.getBoundingClientRect().top+scrollY);expect(underneath).toBeCloseTo(original,1)
 await search.getByLabel('Search merchant',{exact:true}).fill('Shop 74');await expect(search.getByRole('button',{name:'Shop 74 · Everyday account',exact:true})).toBeVisible()
 const exit=await search.getByRole('button',{name:'Shop 74 · Everyday account',exact:true}).evaluate(async(el)=>{(el as HTMLButtonElement).click();await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));const snapshot=document.querySelector<HTMLElement>('.modal-exit-overlay');return snapshot?{inert:snapshot.inert,hidden:snapshot.getAttribute('aria-hidden'),dialogs:snapshot.querySelectorAll('dialog[open]').length}:null})
 if(motion==='reduce')expect(exit).toBeNull();else expect(exit).toEqual({inert:true,hidden:'true',dialogs:0})
 await expect(search).toBeHidden();await expect(merchant).toContainText('Shop 74 · Everyday account');await expect(find).toBeFocused();await expect(page.locator('.modal-exit-overlay')).toHaveCount(0)
 const after=await tag.evaluate(el=>el.getBoundingClientRect().top+scrollY);expect(after).toBeCloseTo(original,1)
 await page.keyboard.press('Escape');await expect(page.locator('.transaction-filter-reveal')).toHaveAttribute('inert','');await expect(minimum).toBeHidden()
 await page.getByRole('button',{name:/^Filters/}).click();await expect(merchant).toContainText('Shop 74 · Everyday account')
 await page.locator('.filter-card-head').getByRole('button',{name:'Clear filters',exact:true}).click();await expect(merchant).toContainText('All merchants');await expect(page.getByLabel('Active filters',{exact:true})).toHaveCount(0)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([])
})
