import { desktopPhoneCases } from './coverage-cases';
import {test,expect} from '@playwright/test'

for(const {width,theme} of desktopPhoneCases)test('shared search and group editor '+width+' '+theme,async({page})=>{
 await page.setViewportSize({width,height:844})
 await page.addInitScript(theme=>localStorage.setItem('finance-theme',theme),theme)
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('demo')
 await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 const trigger=page.getByRole('button',{name:'Search workspace',exact:true})
 const box=await trigger.boundingBox();expect(box!.width).toBeGreaterThanOrEqual(44);expect(box!.height).toBeGreaterThanOrEqual(44)
 await trigger.click()
 const search=page.getByRole('dialog',{name:'Search workspace',exact:true})
 const input=search.getByRole('combobox',{name:'Search workspace',exact:true})
 await expect(input).toBeFocused()
 await input.fill('Groceries')
 await expect(search.getByRole('option').first()).toBeVisible()
 const active=await input.getAttribute('aria-activedescendant');expect(active).toBeTruthy()
 await expect(page.locator('[id="'+active+'"]')).toHaveAttribute('aria-selected','true')
 await search.getByRole('button',{name:'Clear search',exact:true}).focus()
 await page.keyboard.press('Enter')
 await expect(input).toHaveValue('')
 await expect(search).toBeVisible()
 await input.fill('Utilities')
 await expect(search.getByRole('option',{name:/utilities/i}).first()).toBeVisible()
 await input.press('Enter')
 const editor=page.getByRole('dialog',{name:'Edit spending group',exact:true})
 await expect(editor).toBeVisible();await expect(search).toHaveCount(0)
 const name=editor.getByLabel('Name',{exact:true})
 await expect(name).toBeFocused()
 await expect(editor.locator('form')).toHaveAttribute('novalidate','')
 await name.fill(' ')
 await expect(name).not.toHaveAttribute('aria-invalid','true')
 await name.blur()
 await expect(name).toHaveAttribute('aria-invalid','true')
 await expect(editor.getByRole('alert')).toContainText('Enter name.')
 await name.fill('a');await expect(editor.getByRole('alert')).toContainText('2–80')
 await name.fill('Synthetic utilities '+width+' '+theme)
 await expect(name).not.toHaveAttribute('aria-invalid','true')
 await editor.getByRole('button',{name:'Save spending group',exact:true}).click()
 await expect(editor).toHaveCount(0)
 await trigger.click();await input.fill('Groceries');await expect(search.getByRole('option').first()).toBeVisible();await input.press('Enter')
 const category=page.getByRole('dialog',{name:'Edit category · Groceries',exact:true})
 await expect(category).toBeVisible()
 await expect(category.getByLabel('Category name')).toBeFocused()
 await expect(category.getByLabel(/spending group/i)).toHaveCount(0)
 await category.getByRole('button',{name:'Cancel',exact:true}).click()
 await trigger.click();await input.fill('  ')
 await expect(search.getByRole('option')).toHaveCount(0)
 await input.press('Escape');await expect(search).toHaveCount(0);await expect(trigger).toBeFocused()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})

test('search loading, failed request and retry remain distinct',async({page})=>{
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 let release:()=>void=()=>{};const blocked=new Promise<void>(resolve=>{release=resolve})
 let fail=true
 await page.route('**/api/search?**',async route=>{if(fail){await blocked;await route.fulfill({status:503,json:{error:'Synthetic search failure'}})}else await route.fulfill({json:{categories:[],spending_groups:[],transactions:[],merchant_rules:[],rules:[]}})})
 await page.getByRole('button',{name:'Search workspace',exact:true}).click()
 const search=page.getByRole('dialog',{name:'Search workspace',exact:true}),input=search.getByRole('combobox')
 await input.fill('failure')
 await expect(search.getByRole('status')).toContainText('Searching')
 await expect(input).not.toHaveAttribute('aria-activedescendant',/.+/)
 release()
 await expect(search.getByText('Search could not be completed.')).toBeVisible()
 await expect(search.getByText(/No results/)).toHaveCount(0)
 await expect(page.getByRole('alert')).toBeVisible()
 fail=false;await search.getByRole('button',{name:'Retry search',exact:true}).click()
 await expect(search.getByRole('status')).toContainText('No results')
})

test('MCP budget approval shows exact grouped effects',async({page})=>{
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 await page.route('**/api/mcp/settings',async route=>{
  const response=await route.fetch(),state=await response.json()
  state.proposals=[{id:'synthetic-budget-proposal',operation:'update_budget',status:'pending',token_name:'Synthetic budget agent',expires_at:Math.floor(Date.now()/1000)+3600,payload:{
   change:{operation:'update_budget',id:1,budget:{version:1,merge:false,groups:[{group_id:4,targets:[]}],targets:[]}},
   before:{groups:[{group_id:4,group_name:'Exceptions',group_version:1}],targets:[{group_id:4,category_id:1,amount_cents:12000,carry_forward:0,included:1}]},
   budget_after:{groups:[{group_id:4,group_name:'Exceptions',group_version:1}],targets:[]}
  }}]
  await route.fulfill({json:state})
 })
 await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('tab',{name:'MCP',exact:true}).click()
 const proposal=page.locator('.mcp-proposal')
 await proposal.getByText('Inspect exact changes (amounts in cents)',{exact:true}).click()
 await expect(proposal.getByText('After · exact group budgets and carry-forward',{exact:true})).toBeVisible()
 await expect(proposal.locator('pre').nth(0)).toContainText('12000')
 await expect(proposal.locator('pre').nth(1)).toContainText('targets')
 await expect(proposal.getByRole('button',{name:'Approve exact changes',exact:true})).toBeVisible()
})
