import {test,expect} from '@playwright/test'
for(const width of [1440,360])test(`income drilldown and merchant permission layout ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible();await page.locator('.income-bucket>summary').click();await page.getByRole('button',{name:'Salary income transactions',exact:true}).click();const modal=page.getByRole('dialog',{name:'Salary · Income',exact:true});await expect(modal).toContainText('35');await expect(modal.getByRole('button',{name:/Salary payment/})).toBeVisible();await modal.getByRole('button',{name:'Close',exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 if(width===360){await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'More',exact:true}).click();await page.getByRole('navigation',{name:'More pages'}).getByRole('button',{name:'Categories',exact:true}).click()}else await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'Categories',exact:true}).click();const category=page.locator('.classification-category-row').first();await category.hover();await expect(category).toHaveCSS('background-color','rgb(229, 231, 235)')

 await page.route('**/api/mcp/settings',async route=>{const response=await route.fetch(),state=await response.json();state.connections=[{id:999,name:'Preview agent',client_id:'',can_write:1,permission_version:1,expires_at:Math.floor(Date.now()/1000)+3600,permissions:{schema_version:1,preset:'custom',read_merchants:true,capabilities:{manage_merchants:true,manage_merchant_rules:true,assign_merchants:true},automatic_approval:{},constraints:{account_ids:[],selected_accounts:false,missing_categories_only:false,constrained_rules:false}}}];await route.fulfill({json:state})})
 if(width===360){await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'More',exact:true}).click();await page.getByRole('navigation',{name:'More pages'}).getByRole('button',{name:'Settings',exact:true}).click()}else await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'Settings',exact:true}).click()
 await page.getByRole('tab',{name:'MCP',exact:true}).click();await page.getByRole('button',{name:'Edit permissions',exact:true}).click();const permissions=page.getByRole('dialog',{name:'Permissions for Preview agent',exact:true});await expect(permissions.getByRole('group',{name:'Merchants',exact:true})).toBeVisible();await expect(permissions.getByRole('checkbox',{name:'Read merchant names, naming rules and logos',exact:true})).toBeChecked();expect(await permissions.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await permissions.getByLabel('Permission level',{exact:true}).selectOption('review');await expect(permissions.getByRole('heading',{name:'Allowed changes',exact:true})).toHaveCount(0)

})
