import {test,expect} from '@playwright/test'
for(const width of [1440,360])for(const theme of ['light','dark'])test(`sign-in errors remain readable and retryable at ${width}px in ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:900})
 await page.addInitScript(value=>localStorage.setItem('finance-theme',value),theme)
 await page.goto('/')
 const username=page.getByLabel('Username',{exact:true}),password=page.getByLabel('Password',{exact:true}),submit=page.getByRole('button',{name:'Sign in',exact:true})
 await username.fill('synthetic-missing-user')
 await password.fill('synthetic-browser-password')
 const formTop=await page.locator('.login-panel').evaluate(el=>el.getBoundingClientRect().top+scrollY)
 await submit.click()
 const toast=page.locator('.toast:popover-open')
 await expect(toast).toBeVisible()
 await expect(toast).toHaveAttribute('role','alert')
 await expect(toast).toContainText('Username or password is incorrect')
 await page.clock.install()
 await page.clock.fastForward(20000)
 await expect(toast).toBeVisible()
 expect(await page.locator('.login-panel').evaluate(el=>el.getBoundingClientRect().top+scrollY)).toBe(formTop)
 await expect(username).toHaveValue('synthetic-missing-user')
 await toast.getByRole('button',{name:'Dismiss message'}).click()
 await expect(page.locator('.toast')).toHaveCount(0)
 await username.fill('demo')
 await password.fill('incorrect-synthetic-password')
 await password.press('Enter')
 await expect(toast).toContainText('Username or password is incorrect')
 await page.clock.fastForward(20000)
 await expect(toast).toBeVisible()
 await expect(password).toHaveValue('incorrect-synthetic-password')
 await password.fill('synthetic-browser-password')
 await submit.click()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 await expect(page.locator('.toast')).toHaveCount(0)
})

for(const width of [1440,360])for(const theme of ['light','dark'])test(`sign-in request and expired-session errors persist at ${width}px in ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:900})
 await page.addInitScript(value=>localStorage.setItem('finance-theme',value),theme)
 await page.goto('/')
 const username=page.getByLabel('Username',{exact:true}),password=page.getByLabel('Password',{exact:true}),submit=page.getByRole('button',{name:'Sign in',exact:true})
 await username.fill('demo');await password.fill('synthetic-browser-password');await submit.click()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 await page.route('**/api/me',route=>route.fulfill({status:401,json:{error:'Authentication required'}}))
 await page.evaluate(()=>fetch('/api/me').then(response=>{if(response.status===401)window.dispatchEvent(new Event('session-expired'))}))
 const toast=page.locator('.toast:popover-open')
 await expect(toast).toContainText('Your session expired')
 await page.clock.install();await page.clock.fastForward(20000)
 await expect(toast).toBeVisible()
 await username.fill('demo');await password.fill('synthetic-browser-password')
 await expect(toast).toBeVisible()
 await page.route('**/api/login',route=>route.fulfill({status:503,json:{error:'Synthetic sign-in service unavailable'}}))
 await password.press('Enter')
 await expect(toast).toContainText('Synthetic sign-in service unavailable')
 await page.clock.fastForward(20000);await expect(toast).toBeVisible()
 await password.fill('edited-synthetic-password');await expect(toast).toBeVisible()
 await expect(page.locator('.toast')).toHaveCount(1)
 await page.unroute('**/api/login')
 await page.route('**/api/login',route=>route.abort('failed'))
 await submit.click();await expect(toast).toContainText('Failed to fetch')
 await page.clock.fastForward(20000);await expect(toast).toBeVisible()
 await toast.getByRole('button',{name:'Dismiss message'}).click()
 await expect(page.locator('.toast')).toHaveCount(0)
 await expect(password).toHaveValue('edited-synthetic-password')
})
