import {test,expect,type Page} from '@playwright/test'
import {createHash} from 'node:crypto'
test.setTimeout(180000)

async function connect(page:Page,name:string,write=true){
 const metadata=await (await page.request.get('/.well-known/oauth-authorization-server')).json()
 const endpoint=metadata.issuer+'/api/mcp',redirect='http://127.0.0.1:43210/callback'
 const registration=await page.request.post(metadata.registration_endpoint,{data:{client_name:name,redirect_uris:[redirect],token_endpoint_auth_method:'none'}})
 expect(registration.status()).toBe(201);const client=(await registration.json()).client_id
 const verifier='synthetic-browser-pkce-verifier-at-least-forty-three-characters'
 const query=new URLSearchParams({client_id:client,redirect_uri:redirect,response_type:'code',resource:endpoint,scope:'finance:read finance:propose',state:'synthetic-state',code_challenge_method:'S256',code_challenge:createHash('sha256').update(verifier).digest('base64url')})
 await page.route(redirect+'**',route=>route.fulfill({contentType:'text/html',body:'<p>Agent connected</p>'}))
 await page.goto(metadata.authorization_endpoint+'?'+query)
 await expect(page.getByRole('heading',{name:/^(Welcome back|Approve agent connection)$/})).toBeVisible()
 const login=page.getByRole('heading',{name:'Welcome back',exact:true})
 if(await login.isVisible()){
  await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click()
 }
 await expect(page.getByRole('heading',{name:'Approve agent connection',exact:true})).toBeVisible()
 await expect(page.getByLabel('Permissions',{exact:true})).toHaveValue('review')
 if(write)await page.getByLabel('Permissions',{exact:true}).selectOption('finance')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('button',{name:'Approve connection',exact:true}).click()
 await page.waitForURL(redirect+'**');const callback=new URL(page.url());expect(callback.searchParams.get('state')).toBe('synthetic-state');expect(callback.searchParams.get('iss')).toBe(metadata.issuer)
 const exchanged=await page.request.post(metadata.token_endpoint,{form:{grant_type:'authorization_code',client_id:client,redirect_uri:redirect,resource:endpoint,code:callback.searchParams.get('code')!,code_verifier:verifier}})
 expect(exchanged.status()).toBe(200);const credentials=await exchanged.json()
 await page.goto('/')
 return {token:credentials.access_token,refresh:credentials.refresh_token,client,endpoint}
}


for(const width of [1440,360])for(const theme of ['light','dark'])test(`MCP settings and approved agent changes ${width} ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:900})
 await page.addInitScript(t=>localStorage.setItem('finance-theme',t),theme)
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 const {token,endpoint}=await connect(page,`Synthetic ${width} ${theme}`)
 if(width===360){await page.getByRole('navigation',{name:'Mobile navigation',exact:true}).getByRole('button',{name:'More',exact:true}).click();await page.getByRole('navigation',{name:'More pages',exact:true}).getByRole('button',{name:'Settings',exact:true}).click()}else await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Settings',exact:true}).click()
 await page.getByRole('tab',{name:'MCP',exact:true}).click()
 await expect(page.getByLabel('MCP server endpoint')).toHaveValue(/\/api\/mcp$/)
 const call=async(name:string,args:any)=>{
  const response=await page.request.post(endpoint,{headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',Accept:'application/json, text/event-stream','MCP-Protocol-Version':'2025-11-25'},data:{jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}}})
  expect(response.status()).toBe(200)
  const body=await response.json();expect(body.error).toBeUndefined();const result=body.result
  return {error:!!result.isError,value:JSON.parse(result.content[0].text)}
 }
 const transactions=await call('list_transactions',{})
 expect(transactions.error).toBe(false)
 expect(JSON.stringify(transactions.value)).not.toMatch(/12345678901|bank_id|source_description|provenance/)
 const original=transactions.value.items.find((t:any)=>t.id===5)
 const proposal=await call('prepare_change',{operation:'edit_transactions',edits:[{id:5,version:original.version,category_id:original.allocations[0].category_id===1?2:1}]})
 expect(proposal.error).toBe(false)
 expect((await call('apply_change',{proposal_id:proposal.value.proposal_id})).error).toBe(true)
 await page.getByRole('button',{name:'Refresh proposals',exact:true}).click()
 const article=page.locator('.mcp-proposal').filter({hasText:proposal.value.proposal_id.slice(0,8)})
 await article.getByText('Inspect exact changes (amounts in cents)',{exact:true}).click()
 await expect(article).toContainText('Before')
 await expect(article).toContainText('After')
 await expect(article).toContainText('125000')
 await article.getByRole('button',{name:'Approve exact changes',exact:true}).click()
 await expect(article).toContainText('approved')
 expect((await call('apply_change',{proposal_id:proposal.value.proposal_id})).error).toBe(false)
 const edited=await call('list_transactions',{filters:{id:'5'}})
 expect(edited.value.items[0].review_state).toBe('accepted')
 expect(edited.value.items[0].amount_cents).toBe(original.amount_cents)
 expect(edited.value.items[0].seen).toBe(1)
 await expect(page.getByText('Agent setup instructions',{exact:true})).toHaveCount(0)
 await expect(page.getByRole('button',{name:'Copy agent instructions',exact:true})).toHaveCount(0)
 const setup=await page.request.get(endpoint,{headers:{Accept:'text/plain'}})
 expect(setup.status()).toBe(200);expect(await setup.text()).toContain('OAuth browser sign-in with S256 PKCE')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('tab',{name:'General',exact:true}).click()
 await page.getByRole('tab',{name:'MCP',exact:true}).click()
 await expect(page.getByRole('button',{name:'Create MCP token',exact:true})).toHaveCount(0)
 const access=page.locator('.mcp-access-row').filter({hasText:`Synthetic ${width} ${theme}`})
 await expect(access.locator('.mcp-agent-summary')).toContainText('Finance editing')
 await expect(access.locator('.mcp-agent-summary')).toContainText('Manual approval')
 const details=access.locator('.mcp-agent-details')
 await expect(details).not.toHaveAttribute('open','')
 await expect(details.getByText(/Can propose:/)).not.toBeVisible()
 await details.getByText('View permission details',{exact:true}).focus()
 await page.keyboard.press('Enter')
 await expect(details.getByText(/Can propose:/)).toBeVisible()
 await page.keyboard.press('Enter')
 await expect(details.getByText(/Can propose:/)).not.toBeVisible()

 await access.getByRole('button',{name:'Edit permissions',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:`Permissions for Synthetic ${width} ${theme}`})
 await dialog.getByLabel('Permissions',{exact:true}).selectOption('categorization')
 await dialog.getByRole('button',{name:'Save permissions',exact:true}).click()
 await expect(dialog.getByText('Select at least one account.',{exact:true})).toBeVisible()
 await dialog.getByLabel('Everyday account',{exact:true}).check()
 await dialog.getByLabel('Confirm permissions',{exact:true}).selectOption('confirmed')
 await dialog.getByRole('button',{name:'Save permissions',exact:true}).click()
 await expect(dialog).toHaveCount(0)
 await expect(access).toContainText('Reads and proposals limited to: Everyday account')
 const limited=await call('list_accounts',{});expect(limited.value.items.map((a:any)=>a.id)).toEqual([1])
 const deniedChange=await call('prepare_change',{operation:'create_category',category:{name:'Not allowed synthetic',kind:'expense'}});expect(deniedChange.error).toBe(true)
 await access.getByRole('button',{name:'Edit permissions',exact:true}).click()
 await dialog.getByLabel('Permissions',{exact:true}).selectOption('custom')
 await dialog.getByLabel('Mark your transactions seen or unseen',{exact:true}).check()
 await dialog.getByLabel('Automatically approve: Create rules',{exact:true}).check()
 await dialog.getByLabel('Confirm permissions',{exact:true}).selectOption('confirmed')
 await dialog.getByRole('button',{name:'Save permissions',exact:true}).click()
 await expect(dialog).toHaveCount(0);await expect(access).toContainText('mark your transactions seen or unseen')
 await expect(access.locator('.mcp-agent-summary')).toContainText('Automatic for 1 change type')
 await expect(access.locator('.mcp-agent-summary')).toContainText('Everyday account')
 const automatic=await call('prepare_change',{operation:'save_rule',rule:{account_id:1,pattern:`Automatic browser ${width} ${theme}`,category_id:1}})
 expect(automatic.error).toBe(false);expect(automatic.value.status).toBe('approved')
 expect((await call('apply_change',{proposal_id:automatic.value.proposal_id})).error).toBe(false)
 const target=(await call('list_transactions',{filters:{id:'5'}})).value.items[0]
 const seenProposal=await call('prepare_change',{operation:'set_seen',seen:false,seen_items:[{id:5,version:target.version}]});expect(seenProposal.error).toBe(false)
 await page.getByRole('button',{name:'Refresh proposals',exact:true}).click()
 const seenArticle=page.locator('.mcp-proposal').filter({hasText:seenProposal.value.proposal_id.slice(0,8)})
 await seenArticle.getByText('Inspect exact changes (amounts in cents)',{exact:true}).click()
 await expect(seenArticle).toContainText('Current personal seen state')
 await seenArticle.getByRole('button',{name:'Approve exact changes',exact:true}).click()
 expect((await call('apply_change',{proposal_id:seenProposal.value.proposal_id})).error).toBe(false)
 const unseen=(await call('list_transactions',{filters:{id:'5'}})).value.items[0]
 expect(unseen.version).toBe(target.version);expect(unseen.seen).toBe(0)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await access.getByRole('button',{name:'Revoke',exact:true}).click()
 await expect(access).toHaveCount(0)
 const revoked=await page.request.post(endpoint,{headers:{Authorization:`Bearer ${token}`},data:{jsonrpc:'2.0',id:1,method:'ping'}})
 expect(revoked.status()).toBe(401)
 expect(errors).toEqual([])
})

test('MCP budget proposal shows existing limits and applies only after approval',async({page})=>{
 const {token,endpoint}=await connect(page,'Synthetic budget agent')
 await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Settings',exact:true}).click()
 await page.getByRole('tab',{name:'MCP',exact:true}).click()
 const call=async(name:string,args:any)=>{
  const response=await page.request.post(endpoint,{headers:{Authorization:`Bearer ${token}`,Accept:'application/json, text/event-stream','MCP-Protocol-Version':'2025-11-25'},data:{jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}}})
  expect(response.status()).toBe(200);const body=await response.json();expect(body.error).toBeUndefined();expect(body.result.isError).not.toBe(true);return JSON.parse(body.result.content[0].text)
 }
 const periods=await call('list_budget_periods',{}),period=periods.items.find((p:any)=>p.id===1)
 const proposal=await call('prepare_change',{operation:'update_budget',id:1,budget:{version:period.version,merge:true,targets:[{category_id:1,amount_cents:450100}]}})
 await page.getByRole('button',{name:'Refresh proposals',exact:true}).click()
 const article=page.locator('.mcp-proposal').filter({hasText:proposal.proposal_id.slice(0,8)})
 await article.getByText('Inspect exact changes (amounts in cents)',{exact:true}).click()
 await expect(article).toContainText('Before')
 await expect(article).toContainText('450000')
 await expect(article).toContainText('450100')
 await article.getByRole('button',{name:'Approve exact changes',exact:true}).click()
 await expect(article).toContainText('approved')
 await call('apply_change',{proposal_id:proposal.proposal_id})
 const limits=await call('get_budget_limits',{period_id:1})
 expect(limits.items.find((c:any)=>c.id===1).amount_cents).toBe(450100)
 expect(limits.items.find((c:any)=>c.id===2).amount_cents).toBe(200000)
 const first=await call('prepare_change',{operation:'create_category',category:{name:'Bulk browser one',kind:'expense'}})
 const second=await call('prepare_change',{operation:'create_category',category:{name:'Bulk browser two',kind:'expense'}})
 await page.getByRole('button',{name:'Refresh proposals',exact:true}).click()
 await page.getByLabel('Select proposal '+first.proposal_id.slice(0,8),{exact:true}).check()
 await page.getByRole('button',{name:'Approve selected (1)',exact:true}).click()
 await expect(page.locator('.mcp-proposal').filter({hasText:first.proposal_id.slice(0,8)})).toContainText('approved')
 await expect(page.locator('.mcp-proposal').filter({hasText:second.proposal_id.slice(0,8)})).toContainText('pending')
 await page.getByRole('button',{name:/^Approve all shown/}).click()
 await expect(page.locator('.mcp-proposal').filter({hasText:second.proposal_id.slice(0,8)})).toContainText('approved')
 await page.locator('.mcp-access-row').filter({hasText:'Synthetic budget agent'}).getByRole('button',{name:'Revoke',exact:true}).click()
})

test('OAuth read-only default and connection revocation',async({page})=>{
 const {token,refresh,client,endpoint}=await connect(page,'Synthetic read-only agent',false)
 const denied=await page.request.post(endpoint,{headers:{Authorization:`Bearer ${token}`},data:{jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'prepare_change',arguments:{}}}})
 expect(denied.status()).toBe(403);expect(denied.headers()['www-authenticate']).toContain('insufficient_scope')
 const rotated=await page.request.post('/oauth/token',{form:{grant_type:'refresh_token',client_id:client,refresh_token:refresh,resource:endpoint}});expect(rotated.status()).toBe(200)
 const credentials=await rotated.json();expect(credentials.scope).toBe('finance:read')
 await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('tab',{name:'MCP',exact:true}).click()
 const connection=page.locator('.mcp-access-row').filter({hasText:'Synthetic read-only agent'});await expect(connection).toContainText('Read-only');await connection.getByRole('button',{name:'Revoke',exact:true}).click();await expect(connection).toHaveCount(0)
 expect((await page.request.post('/oauth/token',{form:{grant_type:'refresh_token',client_id:client,refresh_token:credentials.refresh_token,resource:endpoint}})).status()).toBe(400)
})
