import {test,expect} from '@playwright/test'
for(const width of [1440,360])test(`network settings save for restart and preserve current session at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 if(width===360){await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'More',exact:true}).click();await page.getByRole('navigation',{name:'More pages'}).getByRole('button',{name:'Settings',exact:true}).click()}
 else await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Settings',exact:true}).click()
 await page.getByRole('tab',{name:'Network',exact:true}).click()
 const url=page.getByLabel('Public URL',{exact:true}),trust=page.getByLabel('Trusted proxy addresses',{exact:true})
 await expect(url).toHaveValue('http://127.0.0.1:18080');await expect(url).not.toHaveAttribute('aria-invalid','true')
 await url.fill('https://finance.example.com/path');await url.press('Tab');await expect(url).toHaveAttribute('aria-invalid','true')
 await url.fill('https://finance.example.com');await expect(url).not.toHaveAttribute('aria-invalid','true')
 await trust.fill('0.0.0.0/0');await trust.press('Tab');await expect(trust).toHaveAttribute('aria-invalid','true')
 await trust.fill('127.0.0.1,::1');await expect(trust).not.toHaveAttribute('aria-invalid','true')
 await page.getByRole('button',{name:'Save network settings',exact:true}).click()
 await expect(page.locator('.toast:popover-open')).toContainText('restart the tracker')
 await expect(page.locator('.network-settings')).toContainText('Restart required')
 await expect(page.locator('.network-settings')).toContainText('http://127.0.0.1:18080')
 await page.reload();await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 if(width===360){await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'More',exact:true}).click();await page.getByRole('navigation',{name:'More pages'}).getByRole('button',{name:'Settings',exact:true}).click()}
 else await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Settings',exact:true}).click()
 await page.getByRole('tab',{name:'Network',exact:true}).click();await expect(url).toHaveValue('https://finance.example.com')
 await page.getByRole('button',{name:'Use environment settings',exact:true}).click();await expect(url).toHaveValue('http://127.0.0.1:18080')
 await expect(page.locator('.network-settings')).toContainText('In use')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
})
