import {test,expect} from '@playwright/test'
const onboardingURL='http://127.0.0.1:'+String(Number(process.env.E2E_TEST_PORT||18080)+1)
test.use({baseURL:onboardingURL})
test('inline validation waits for blur, updates while typing and tracks related fields',async({page,request})=>{
 await page.goto('/')
 const username=page.getByLabel('Username',{exact:true}),password=page.getByLabel('Password',{exact:true}),confirmation=page.getByLabel('Confirm password',{exact:true})
 await expect(page.getByRole('heading',{name:'Create admin account'})).toBeVisible()
 await expect(page.getByRole('alert')).toHaveCount(0)
 await page.getByRole('button',{name:'Show password',exact:true}).click()
 await expect(password).toHaveAttribute('type','text')
 await page.getByRole('button',{name:'Hide password',exact:true}).click()
 await expect(password).toHaveAttribute('type','password')
 await page.getByRole('button',{name:'Show confirm password',exact:true}).click()
 await expect(confirmation).toHaveAttribute('type','text')
 await page.getByRole('button',{name:'Hide confirm password',exact:true}).click()
 await expect(confirmation).toHaveAttribute('type','password')
 await username.fill('a')
 await expect(username).not.toHaveAttribute('aria-invalid','true')
 await password.focus()
 await expect(username).toHaveAttribute('aria-invalid','true')
 const errorId=await username.getAttribute('aria-describedby')
 await expect(page.locator('[id="'+errorId+'"]')).toHaveText('Use at least 2 characters.')
 await username.fill('valid-owner')
 await expect(username).not.toHaveAttribute('aria-invalid','true')
 await password.fill('short')
 await confirmation.focus()
 await expect(password).toHaveAttribute('aria-invalid','true')
 await password.fill('synthetic-validation-password')
 await expect(password).not.toHaveAttribute('aria-invalid','true')
 await confirmation.fill('different-password')
 await username.focus()
 await expect(confirmation).toHaveAttribute('aria-invalid','true')
 await confirmation.fill('synthetic-validation-password')
 await expect(confirmation).not.toHaveAttribute('aria-invalid','true')
 await password.fill('changed-synthetic-password')
 await expect(confirmation).toHaveAttribute('aria-invalid','true')
 await page.setViewportSize({width:360,height:800})
 await page.emulateMedia({colorScheme:'dark'})
 await expect(page.getByText('Passwords do not match.',{exact:true})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:'test-results/inline-errors-mobile.png',fullPage:true})
 await username.fill('')
 await password.fill('')
 await confirmation.fill('')
 await page.getByRole('button',{name:'Create account',exact:true}).click()
 await expect(username).toBeFocused()
 await expect(username).toHaveAttribute('aria-invalid','true')
 await expect(password).toHaveAttribute('aria-invalid','true')
 await expect(confirmation).toHaveAttribute('aria-invalid','true')
 expect((await(await request.get('/api/setup')).json()).required).toBe(true)
})
test('first-run setup, keyboard validation, mobile themes and permanent closure',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await expect(page.getByRole('heading',{name:'Create admin account'})).toBeVisible()
 const bootstrap=await (await request.get('/api/setup')).json()
 expect(bootstrap.required).toBe(true)
 await page.screenshot({path:'test-results/onboarding-desktop.png',fullPage:true})
 await page.setViewportSize({width:360,height:800})
 await page.emulateMedia({colorScheme:'dark'})
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.screenshot({path:'test-results/onboarding-mobile-dark.png',fullPage:true})
 await page.emulateMedia({colorScheme:'light'})
 await expect(page.locator('html')).toHaveAttribute('data-theme','light')
 await expect(page.getByLabel('Username')).toBeFocused()
 await page.keyboard.type('browser-owner')
 await page.keyboard.press('Tab')
 await expect(page.getByLabel('Password',{exact:true})).toBeFocused()
 await page.keyboard.type('synthetic-onboarding-password')
 await page.keyboard.press('Tab')
 await expect(page.getByRole('button',{name:'Show password',exact:true})).toBeFocused()
 await page.keyboard.press('Tab')
 await expect(page.getByLabel('Confirm password',{exact:true})).toBeFocused()
 await page.keyboard.type('different-password')
 await page.keyboard.press('Tab')
 await expect(page.getByRole('button',{name:'Show confirm password',exact:true})).toBeFocused()
 await page.keyboard.press('Tab')
 await expect(page.getByRole('button',{name:'Create account'})).toBeFocused()
 await page.keyboard.press('Enter')
 await expect(page.getByRole('alert')).toHaveText('Passwords do not match.')
 expect((await (await request.get('/api/setup')).json()).required).toBe(true)
 await page.getByLabel('Confirm password',{exact:true}).fill('synthetic-onboarding-password')
 await page.getByRole('button',{name:'Create account'}).focus()
 await page.keyboard.press('Enter')
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 await page.reload()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 expect(await (await request.get('/api/setup')).json()).toEqual({required:false})
 const replay=await request.post('/api/setup',{headers:{Origin:onboardingURL,'X-CSRF-Token':bootstrap.csrf},data:{username:'another-owner',password:'synthetic-onboarding-password'}})
 expect(replay.status()).toBe(409)
 await page.getByRole('button',{name:'Sign out',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible()
 await page.reload()
 await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible()
 await expect(page.getByRole('heading',{name:'Create admin account'})).toHaveCount(0)
 await page.setViewportSize({width:1280,height:800})
 await page.getByLabel('Username',{exact:true}).fill('browser-owner')
 await page.getByLabel('Password',{exact:true}).fill('synthetic-onboarding-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 expect(errors).toEqual([])
})

test('first expense category can be created inside an empty budget',async({page})=>{
 // Simulate an empty category list while keeping the real create/save endpoints.
 await page.route('**/api/periods/*/targets*',async route=>{const response=await route.fetch();const body=await response.json();const items=body.items.filter((item:any)=>item.name==='First synthetic expense');await route.fulfill({response,json:{...body,items,total:items.length,list_version:'empty-category-fixture'}})})
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('browser-owner')
 await page.getByLabel('Password',{exact:true}).fill('synthetic-onboarding-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 // Fresh installations deliberately have no built-in classification configuration.
 const me=await (await page.request.get('/api/me')).json()
 const created=await page.request.post('/api/spending-groups',{headers:{'X-CSRF-Token':me.csrf,Origin:new URL(page.url()).origin},data:{name:'Day-to-day',color:'teal'}})
 expect(created.ok()).toBe(true)
 const groupID=String((await created.json()).id)
 await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Budgets',exact:true}).click()
 await page.getByRole('button',{name:'New period',exact:true}).click()
 await page.getByRole('dialog').getByRole('button',{name:'Preview affected transactions',exact:true}).click()
 await page.getByRole('dialog').getByRole('button',{name:'Save period',exact:true}).click()
 await expect(page.getByRole('dialog')).not.toBeVisible()
 await page.getByRole('button',{name:'Edit budgets',exact:true}).first().click()
 await expect(page.getByRole('dialog').getByText('Start building your budget',{exact:true})).toBeVisible()
 await page.getByRole('dialog').getByRole('button',{name:'Add group',exact:true}).click()
 const group=page.getByRole('dialog',{name:'Add budget group',exact:true})
 await group.getByLabel('Spending group').selectOption(groupID)
 await group.getByRole('button',{name:'Add group to budget',exact:true}).click()
 await page.getByRole('dialog').getByRole('button',{name:'Add category to Day-to-day',exact:true}).click()
 const add=page.getByRole('dialog',{name:'Add category · Day-to-day',exact:true})
 await add.getByRole('button',{name:'Create expense category',exact:true}).click()
 await add.getByLabel('Category name').fill('First synthetic expense')
 await add.getByRole('button',{name:'Create category',exact:true}).click()
 await expect(add.getByLabel('Budget amount')).toHaveValue('0.00')
 await expect(add.getByLabel('Budget amount')).toBeFocused()
 await add.getByLabel('Budget amount').fill('89.12')
 await add.getByRole('button',{name:'Add category to budget',exact:true}).click()
 await page.getByRole('dialog').getByRole('button',{name:'Save budget',exact:true}).click()
 await expect(page.getByRole('dialog')).not.toBeVisible()
 await page.getByRole('button',{name:'Edit budgets',exact:true}).first().click()
 await expect(page.getByLabel('First synthetic expense',{exact:true})).toHaveValue('89.12')
})
