import {test,expect} from '@playwright/test'
for(const width of [1440,360])for(const theme of ['light','dark'])test(`review filters are editable defaults ${width} ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:900})
 await page.addInitScript(t=>localStorage.setItem('finance-theme',t),theme)
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('demo')
 await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await page.getByRole('navigation',{name:width===360?'Mobile navigation':'Main navigation',exact:true}).getByRole('button',{name:'Transactions',exact:true}).click()
 await page.getByRole('button',{name:'Filters',exact:true}).click()
 const rows=page.locator('.transaction-detail')
 const filters=page.getByRole('region',{name:'Transaction filters',exact:true})
 await expect(filters.getByLabel('Accounts',{exact:true})).toBeVisible()
 await expect(filters.getByLabel('Budget period',{exact:true})).toBeVisible()
 await expect(filters.getByLabel('Search transactions',{exact:true})).toBeVisible()
 // Account/period/search remain primary; classification and review states share the expanded filter grid.
 const controls=await Promise.all(['Filter by category','Filter by spending group'].map(label=>filters.getByLabel(label,{exact:true}).boundingBox()))
 for(const control of controls){expect(control).not.toBeNull();expect(Math.abs(control!.width-controls[0]!.width)).toBeLessThanOrEqual(1)}
 await filters.getByLabel('Budget period',{exact:true}).selectOption('unassigned')
 await expect(rows).toHaveCount(0)
 await filters.getByLabel('Budget period',{exact:true}).selectOption('1')
 await expect(rows.filter({hasText:'Market groceries'})).toHaveCount(1)
 await filters.getByLabel('Budget period',{exact:true}).selectOption('')
 await expect(page.getByLabel('Acceptance',{exact:true})).toHaveValue('')
 await expect(page.getByLabel('Seen by you',{exact:true})).toHaveValue('')
 await expect(rows.filter({hasText:'Market groceries'})).toHaveCount(1)
 await page.getByRole('checkbox',{name:'Select Market groceries',exact:true}).check()
 await page.getByRole('button',{name:'Mark unseen (1)',exact:true}).click()
 await expect(rows.filter({hasText:'Market groceries'}).getByText('Unseen',{exact:true})).toBeVisible()
 await page.getByRole('tab',{name:/Needs review/}).click()
 await expect(page.getByLabel('Acceptance',{exact:true})).toHaveValue('needs_category')
 await expect(page.getByLabel('Seen by you',{exact:true})).toHaveValue('')
 await expect(rows.filter({hasText:'Market groceries'})).toHaveCount(0)
 // The tab supplies defaults, not an invisible permanent pending filter.
 await page.getByLabel('Seen by you',{exact:true}).selectOption('0')
 await page.getByLabel('Acceptance',{exact:true}).selectOption('accepted')
 await expect(rows.filter({hasText:'Market groceries'})).toHaveCount(1)
 await expect(rows.locator('.badge').filter({hasText:'Needs category'})).toHaveCount(0)
 await page.getByRole('checkbox',{name:'Select Market groceries',exact:true}).check()
 await page.getByRole('button',{name:'Mark seen (1)',exact:true}).click()
 await expect(rows.filter({hasText:'Market groceries'})).toHaveCount(0)
 await page.getByLabel('Seen by you',{exact:true}).selectOption('1')
 await expect(rows.filter({hasText:'Market groceries'})).toHaveCount(1)
 await page.getByRole('tab',{name:'All transactions',exact:true}).click()
 await expect(page.getByLabel('Acceptance',{exact:true})).toHaveValue('')
 await expect(page.getByLabel('Seen by you',{exact:true})).toHaveValue('')
 await page.getByRole('tab',{name:/Needs review/}).click()
 await expect(page.getByLabel('Acceptance',{exact:true})).toHaveValue('needs_category')
 await expect(page.getByLabel('Seen by you',{exact:true})).toHaveValue('')
 await page.getByRole('region',{name:'Transaction filters',exact:true}).getByRole('button',{name:'Clear filters',exact:true}).click()
 await expect(page.getByLabel('Acceptance',{exact:true})).toHaveValue('')
 await expect(page.getByLabel('Seen by you',{exact:true})).toHaveValue('')
 await expect(rows.filter({hasText:'Synthetic long description'})).toHaveCount(1)
 await expect(rows.filter({hasText:'Market groceries'})).toHaveCount(1)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('tab',{name:/Import activity/}).click()
 await expect(filters.getByLabel('Accounts',{exact:true})).toBeVisible()
 await expect(filters.getByLabel('Filter by category',{exact:true})).toBeVisible()
 await expect(filters.getByLabel('Filter by spending group',{exact:true})).toBeVisible()
 await expect(filters.getByLabel('Money direction',{exact:true})).toBeVisible()
 await expect(filters.getByLabel('Search transactions',{exact:true})).toBeVisible()
 await expect(filters.getByLabel('Budget period',{exact:true})).toHaveCount(0)
 await expect(filters.getByLabel('Acceptance',{exact:true})).toHaveCount(0)
 await expect(filters.getByLabel('Seen by you',{exact:true})).toHaveCount(0)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 expect(errors).toEqual([])
})


test('review count includes seen uncategorized transactions and entry clears unrelated filters',async({page})=>{
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Transactions',exact:true}).click()
 const row=page.locator('.transaction-detail').filter({hasText:'Synthetic long description'})
 await expect(row).toBeVisible();await page.getByRole('checkbox',{name:/Select Synthetic long description/}).check();await page.getByRole('button',{name:'Mark seen (1)',exact:true}).click();await expect(row.getByText('Seen',{exact:true})).toBeVisible()
 await page.getByLabel('Search transactions',{exact:true}).fill('No matching description');await expect(page.locator('.transaction-detail')).toHaveCount(0)
 await page.getByRole('tab',{name:'Needs review (1)',exact:true}).click();await expect(page.getByLabel('Search transactions',{exact:true})).toHaveValue('');await expect(row).toBeVisible();await expect(page.locator('.transaction-detail')).toHaveCount(1)
 await page.getByRole('button',{name:'Filters (1)',exact:true}).click();await expect(page.getByLabel('Seen by you',{exact:true})).toHaveValue('');await expect(page.getByLabel('Acceptance',{exact:true})).toHaveValue('needs_category')
})
