import {test,expect,type Page} from '@playwright/test'
async function login(page:Page){
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
}
async function categories(page:Page,mobile=false){
 if(mobile){await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'More',exact:true}).click();await page.getByRole('navigation',{name:'More pages'}).getByRole('button',{name:'Categories',exact:true}).click()}
 else await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Categories',exact:true}).click()
 await page.getByRole('tab',{name:'Automatic rules',exact:true}).click()
}
for(const mobile of [false,true]){
 test('simple rules across enabled accounts '+(mobile?'360px':'desktop'),async({page})=>{
  if(mobile)await page.setViewportSize({width:360,height:800})
  const pattern=mobile?'Mobile supplier':'Desktop supplier'
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await login(page);await categories(page,mobile)
  const count=await page.evaluate(async()=> (await fetch('/api/accounts?page=0&page_size=100&role=editor').then(r=>r.json())).total)
  await expect(page.getByRole('tab',{name:'Automatic rules',exact:true})).toHaveAttribute('aria-selected','true')
  await expect(page.locator('input[type=file]')).toHaveCount(0)
  const before=await page.evaluate(async()=>JSON.stringify(await fetch('/api/transactions').then(r=>r.json())))
  await page.getByRole('button',{name:'Add rule',exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'Add rule',exact:true})
  await dialog.getByLabel('Description contains',{exact:true}).fill(pattern)
  await dialog.getByLabel('Category',{exact:true}).selectOption('1')
  await dialog.getByLabel('Spending group',{exact:true}).selectOption({label:'Recurring'})
  await expect(dialog.getByLabel('Payment direction')).not.toBeVisible()
  await dialog.getByText('More options',{exact:true}).click()
  await dialog.getByLabel('Payment direction').selectOption('debit')
  await dialog.getByText('Check an example',{exact:true}).click()
  await dialog.getByLabel('Example description').fill(pattern+' reference')
  await dialog.getByRole('button',{name:'Check rule',exact:true}).click()
  await expect(dialog.getByText('Matches '+count+' of '+count+' accounts: Groceries · Recurring',{exact:true})).toBeVisible()
  await dialog.getByRole('button',{name:'Save rule',exact:true}).click()
  await expect(dialog).not.toBeVisible()
  const row=page.locator('.rule-row').filter({hasText:pattern})
  await expect(row).toHaveCount(1)
  await expect(row.getByText('All current accounts you can edit · Money out',{exact:true})).toBeVisible()
  const after=await page.evaluate(async()=>JSON.stringify(await fetch('/api/transactions').then(r=>r.json())))
  expect(after).toBe(before)
  await row.locator('summary').click();await row.getByRole('button',{name:'Pause',exact:true}).click()
  await expect(row.getByRole('img',{name:'Paused',exact:true})).toBeVisible()
  await row.locator('summary').click();await row.getByRole('button',{name:'Resume',exact:true}).click()
  await expect(row.getByRole('img',{name:'Paused',exact:true})).toHaveCount(0)
  await row.locator('summary').click();await row.getByRole('button',{name:'Edit rule '+pattern,exact:true}).click()
  const edit=page.getByRole('dialog',{name:'Edit rule',exact:true})
  await edit.getByLabel('Category',{exact:true}).selectOption('2')
  await edit.getByRole('button',{name:'Save rule',exact:true}).click()
  await expect(row.getByText('Transport · Recurring',{exact:true})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.getByRole('tab',{name:'Categories',exact:true}).click()
  await expect(page.getByRole('button',{name:'Add category',exact:true})).toBeVisible()
  await page.getByRole('tab',{name:'Spending groups',exact:true}).click()
  await expect(page.getByRole('button',{name:'Add spending group',exact:true})).toBeVisible()
  expect(errors).toEqual([])
 })
}
test('rule editor can create its category and check overlapping rules',async({page})=>{
 await login(page);await categories(page)
 await page.getByRole('button',{name:'Add rule',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Add rule',exact:true})
 await dialog.getByLabel('Description contains',{exact:true}).fill('Market specific')
 await dialog.getByRole('button',{name:'Create category',exact:true}).click()
 const create=page.getByRole('dialog',{name:'Create category',exact:true})
 await create.getByLabel('Category name',{exact:true}).fill('Synthetic project costs')
 await create.getByRole('button',{name:'Create category',exact:true}).click()
 await expect(create).not.toBeVisible()
 await expect(dialog.getByLabel('Category',{exact:true})).toHaveValue(/\d+/)
 await dialog.getByText('Check an example',{exact:true}).click()
 await dialog.getByLabel('Example description').fill('Market specific')
 await dialog.getByRole('button',{name:'Check rule',exact:true}).click()
 await expect(dialog.getByText('Another matching rule suggests a different category or spending group. Check both rules.',{exact:true})).toBeVisible()
 await dialog.getByRole('button',{name:'Close',exact:true}).click()
})
