import {test,expect} from '@playwright/test'
for(const width of [1440,360])for(const theme of ['light','dark'])test(`automatic acceptance and seen ${width} ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:900})
 await page.addInitScript(t=>localStorage.setItem('finance-theme',t),theme)
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('demo')
 await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await page.getByRole('navigation',{name:width===360?'Mobile navigation':'Main navigation',exact:true}).getByRole('button',{name:'Transactions',exact:true}).click()
 await page.getByRole('tab',{name:/Import activity/}).click()
 await page.getByText('Upload a bank export',{exact:true}).click()
 await page.getByLabel('Import into account',{exact:true}).selectOption('1')
 const tag=`Seen workflow ${width} ${theme}`
 const descriptions=[`Market ${tag}`,`Unknown merchant ${tag}`]
 const csv='ACCOUNT TRANSACTION HISTORY\n\nName:,Synthetic\nAccount:,12345678901,Fusion\nBalance:,100.00\n\nDate, Amount, Balance, Description\n'+descriptions.map((description,i)=>`2026/10/28,-${i+1}.25,100.00,${description}`).join('\n')+'\n'
 await page.locator('input[type=file]').setInputFiles({name:`seen-${width}-${theme}.csv`,mimeType:'text/csv',buffer:Buffer.from(csv)})
 await page.getByRole('button',{name:'Import statement',exact:true}).click()
 await expect(page.getByRole('tab',{name:/Needs review/})).toHaveAttribute('aria-selected','true')
 const rows=page.locator('.transaction-detail')
 await expect(rows.filter({hasText:descriptions[0]})).toHaveCount(0)
 await expect(rows.filter({hasText:descriptions[1]})).toHaveCount(1)
 await page.getByRole('tab',{name:'All transactions',exact:true}).click()
 const first=rows.filter({hasText:descriptions[0]})
 await expect.poll(async()=>{
  const result=await (await page.request.get('/api/transactions?q='+encodeURIComponent(descriptions[0]))).json()
  return result.items.find((item:any)=>item.description===descriptions[0])?.review_state
 }).toBe('approved')
 await expect(first.getByRole('img',{name:'Unseen',exact:true})).toBeVisible()
 await first.click()
 const editor=page.locator('dialog.modal-wide')
 await expect(editor).toContainText('Unseen by you')
 await editor.getByRole('button',{name:'Close',exact:true}).first().click()
 await expect(first.getByRole('img',{name:'Unseen',exact:true})).toBeVisible()
 if(width===360){await first.press('Space');await page.getByLabel('Transaction actions',{exact:true}).click()}else await page.getByRole('checkbox',{name:'Select '+descriptions[0],exact:true}).check()
 await page.getByRole('button',{name:'Mark seen (1)',exact:true}).click()
 await expect(first.getByRole('img',{name:'Seen',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Filters',exact:true}).click()
 await page.getByLabel('Seen by you',{exact:true}).selectOption('0')
 await expect(first).toHaveCount(0)
 await expect(rows.filter({hasText:descriptions[1]})).toHaveCount(1)
 await page.getByLabel('Seen by you',{exact:true}).selectOption('1')
 await expect(first).toHaveCount(1)
 await first.click()
 await editor.getByRole('button',{name:'Mark unseen',exact:true}).click()
 await expect(editor).toContainText('Unseen by you')
 await editor.getByRole('button',{name:'Close',exact:true}).first().click()
 await expect(first).toHaveCount(0)
 await page.getByLabel('Seen by you',{exact:true}).selectOption('')
 await rows.filter({hasText:descriptions[1]}).click()
 await editor.getByLabel('Category',{exact:true}).click()
 await page.getByRole('dialog',{name:'Select category',exact:true}).getByRole('button').filter({hasText:'Groceries'}).first().click()
 await editor.getByRole('button',{name:'Save changes',exact:true}).click()
 await expect(editor).not.toBeVisible()
 await expect.poll(async()=>{
  const result=await (await page.request.get('/api/transactions?q='+encodeURIComponent(descriptions[1]))).json()
  return result.items.find((item:any)=>item.description===descriptions[1])?.review_state
 }).toBe('approved')
 await expect(rows.filter({hasText:descriptions[1]}).getByRole('img',{name:'Seen',exact:true})).toBeVisible()
 await page.getByRole('tab',{name:/Needs review/}).click()
 await expect(rows.filter({hasText:tag})).toHaveCount(0)
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 expect(errors).toEqual([])
})
