import {test,expect} from '@playwright/test'
for(const width of [1440,360])test(`settings navigation keeps account views clean and preserves drafts at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900})
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 async function navigate(name:string){if(width===360&&name!=='Accounts'){await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'More',exact:true}).click();await page.getByRole('navigation',{name:'More pages'}).getByRole('button',{name,exact:true}).click()}else await page.getByRole('navigation',{name:width===360?'Mobile navigation':'Main navigation',exact:true}).getByRole('button',{name,exact:true}).click()}
 await navigate('Accounts')
 await expect(page.getByRole('heading',{name:'FNB connection',exact:true})).toHaveCount(0)
 await expect(page.getByRole('button',{name:'Add account',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Bank connection',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Settings',exact:true})).toBeVisible()
 await expect(page.getByRole('tab',{name:'Banking',exact:true})).toHaveAttribute('aria-selected','true')
 await expect(page.getByRole('heading',{name:'FNB connection',exact:true})).toBeVisible()
 await page.getByRole('tab',{name:'General',exact:true}).click()
 const draft='Unsaved synthetic workspace'
 await page.getByLabel('Display name',{exact:true}).fill(draft)
 const general=page.getByRole('tab',{name:'General',exact:true})
 await general.focus();await page.keyboard.press('ArrowRight')
 await expect(page.getByRole('tab',{name:'Banking',exact:true})).toBeFocused()
 await expect(page.getByRole('heading',{name:'FNB connection',exact:true})).toBeVisible()
 await page.getByRole('tab',{name:'Security',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Change your password',exact:true})).toBeVisible()
 await page.getByRole('tab',{name:'Security',exact:true}).focus();await page.keyboard.press('Home')
 await expect(general).toBeFocused();await expect(page.getByLabel('Display name',{exact:true})).toHaveValue(draft)
 await page.getByRole('tab',{name:'Users & access',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Account access',exact:true})).toBeVisible()
 await page.getByRole('tab',{name:'Backups',exact:true}).click()
 await expect(page.getByRole('button',{name:'Back up now',exact:true})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
 await expect(page.getByRole('button',{name:'Change appearance',exact:true})).toHaveCount(0)
})

test('ordinary users see only General and Security without management requests',async({page})=>{
 const management:string[]=[]
 page.on('request',request=>{if(/\/api\/(users|grants|backups|accounts\/manage|fnb)(?:$|\?)/.test(new URL(request.url()).pathname))management.push(request.url())})
 await page.route('**/api/me',async route=>{const response=await route.fetch();if(response.status()===200){const body=await response.json();await route.fulfill({response,json:{...body,user:{...body.user,admin:false}}})}else await route.fulfill({response})})
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Settings',exact:true}).click()
 await expect(page.getByRole('tab')).toHaveCount(2)
 await expect(page.getByRole('tab',{name:'Banking',exact:true})).toHaveCount(0)
 await page.getByRole('tab',{name:'Security',exact:true}).click()
 await expect(page.getByLabel('Current password',{exact:true})).toBeVisible()
 expect(management).toEqual([])
})
