import {test,expect} from '@playwright/test'
for(const width of [1440,360])test(`navbar theme preference stays synchronized at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900})
 await page.emulateMedia({colorScheme:'light'})
 await page.addInitScript(()=>{if(!localStorage.getItem('finance-theme'))localStorage.setItem('finance-theme','system')})
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('demo')
 await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 const header=page.locator('.topbar')
 const dark=header.getByRole('button',{name:'Switch to dark theme'}),light=header.getByRole('button',{name:'Switch to light theme'})
 await expect(dark).toBeVisible()
 await page.emulateMedia({colorScheme:'dark'})
 await expect(light).toBeVisible()
 await light.click()
 await expect(page.locator('html')).toHaveAttribute('data-theme','light')
 expect(await page.evaluate(()=>localStorage.getItem('finance-theme'))).toBe('light')
 await dark.focus();await page.keyboard.press('Enter')
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
 const box=await light.boundingBox();expect(box!.width).toBeGreaterThanOrEqual(44);expect(box!.height).toBeGreaterThanOrEqual(44)
 if(width===360){await page.getByRole('button',{name:'More',exact:true}).click();await page.getByRole('navigation',{name:'More pages'}).getByRole('button',{name:'Settings',exact:true}).click()}
 else await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Settings',exact:true}).click()
 await expect(page.getByLabel('Appearance',{exact:true})).toHaveValue('dark')
 await page.getByLabel('Appearance',{exact:true}).selectOption('system')
 await page.emulateMedia({colorScheme:'light'})
 await expect(dark).toBeVisible()
 await dark.click()
 await expect(page.getByLabel('Appearance',{exact:true})).toHaveValue('dark')
 await page.reload()
 await expect(light).toBeVisible()
 expect(await page.evaluate(()=>localStorage.getItem('finance-theme'))).toBe('dark')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})
