import {test,expect} from '@playwright/test'
for(const width of [1440,360])test(`toasts overlay pages and dialogs without shifting layout at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:900})
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 if(width===360){await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'More',exact:true}).click();await page.getByRole('navigation',{name:'More pages'}).getByRole('button',{name:'Settings',exact:true}).click()}
 else await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Settings',exact:true}).click()
 const tabs=page.getByRole('tablist',{name:'Settings sections'}),before=await tabs.evaluate(el=>el.getBoundingClientRect().top+scrollY)
 await page.getByRole('button',{name:'Save workspace name',exact:true}).click()
 const toast=page.locator('.toast:popover-open')
 await expect(toast).toContainText('Workspace name saved');await expect(toast).toHaveCSS('position','fixed')
 expect(await tabs.evaluate(el=>el.getBoundingClientRect().top+scrollY)).toBe(before)
 await toast.getByRole('button',{name:'Dismiss message',exact:true}).click();await expect(toast).toHaveCount(0)
 await page.getByRole('tab',{name:'Accounts',exact:true}).click();await page.getByRole('button',{name:'Open Accounts',exact:true}).click()
 await page.getByLabel('Actions for Everyday account',{exact:true}).click()
 await page.getByRole('button',{name:'Edit account',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Edit account',exact:true})
 await dialog.getByLabel('Account name',{exact:true}).fill('Synthetic toast account')
 await dialog.getByLabel('FNB account number',{exact:true}).fill('98765432100')
 await page.route('**/api/accounts/1',async route=>{if(route.request().method()==='PUT')await route.fulfill({status:503,json:{error:'Synthetic connection error'}});else await route.continue()})
 const body=dialog.locator('.modal-body'),modalBefore=await body.evaluate(el=>el.getBoundingClientRect().top+el.closest('dialog')!.scrollTop)
 await dialog.getByRole('button',{name:'Save account',exact:true}).click()
 await expect(toast).toContainText('Synthetic connection error')
 expect(await body.evaluate(el=>el.getBoundingClientRect().top+el.closest('dialog')!.scrollTop)).toBe(modalBefore)
 expect(await toast.evaluate(element=>{const r=element.getBoundingClientRect();return element.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))})).toBeTruthy()
 await expect(dialog.locator('.modal-notice')).toHaveCount(0)
 await toast.getByRole('button',{name:'Dismiss message',exact:true}).click()
 await dialog.getByRole('button',{name:'Close',exact:true}).click()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
})
