import {test,expect} from '@playwright/test'
for(const mobile of [false,true])for(const theme of ['light','dark'])test(`transaction save/approve and stable pickers ${mobile?'mobile':'desktop'} ${theme}`,async({page})=>{
 await page.setViewportSize({width:mobile?360:1440,height:900})
 await page.addInitScript(theme=>localStorage.setItem('finance-theme',theme),theme)
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('demo')
 await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await page.getByRole('navigation',{name:mobile?'Mobile navigation':'Main navigation',exact:true}).getByRole('button',{name:'Transactions',exact:true}).click()
 await page.locator('.transaction-detail').filter({hasText:'Synthetic long description'}).click()
 const editor=page.locator('dialog.modal-wide')
 await editor.getByLabel('Category',{exact:true}).click()
 const picker=page.getByRole('dialog',{name:'Select category',exact:true})
 await picker.getByRole('button',{name:/^Uncategorized/}).click()
 const before=await editor.boundingBox()
 const scroll=await editor.locator('.modal-body').evaluate(el=>el.scrollTop)
 await editor.getByLabel('Category',{exact:true}).press('Enter')
 await expect(picker).toBeVisible()
 expect(await editor.boundingBox()).toEqual(before)
 if(!mobile)expect((await picker.boundingBox())!.width).toBeLessThan(before!.width)
 const pickerBefore=await picker.boundingBox()
 const category=`Review category ${mobile?'mobile':'desktop'} ${theme}`
 await picker.getByLabel('Search category',{exact:true}).fill(category)
 await expect(picker.getByRole('button',{name:`Create “${category}”`,exact:true})).toBeVisible()
 expect(await picker.boundingBox()).toEqual(pickerBefore)
 const listBounds=await picker.locator('.choice-list').boundingBox()
 const typeBounds=await picker.getByLabel('New category type',{exact:true}).locator('..').boundingBox()
 expect(typeBounds!.y-listBounds!.y-listBounds!.height).toBeGreaterThanOrEqual(24)
 expect(await picker.locator('.choice-list').evaluate(el=>getComputedStyle(el).overflow)).toBe('hidden')
 await picker.getByLabel('Search category',{exact:true}).press('Enter')
 await expect(picker).not.toBeVisible()
 await expect(editor.getByLabel('Category',{exact:true})).toBeFocused()
 expect(await editor.boundingBox()).toEqual(before)
 expect(await editor.locator('.modal-body').evaluate(el=>el.scrollTop)).toBe(scroll)
 await expect(editor.getByRole('heading',{name:'Proposed automatic rule'})).toBeVisible()
 await editor.getByLabel('Spending group',{exact:true}).scrollIntoViewIfNeeded()
 const groupScroll=await editor.locator('.modal-body').evaluate(el=>el.scrollTop)
 await editor.getByLabel('Spending group',{exact:true}).click()
 const groupPicker=page.getByRole('dialog',{name:'Select spending group',exact:true})
 await groupPicker.getByLabel('Search spending group',{exact:true}).press('Escape')
 await expect(groupPicker).not.toBeVisible()
 await expect(editor.getByLabel('Spending group',{exact:true})).toBeFocused()
 expect(await editor.locator('.modal-body').evaluate(el=>el.scrollTop)).toBe(groupScroll)
 await editor.getByLabel('Spending group',{exact:true}).press('Enter')
 await groupPicker.getByRole('button',{name:/^Recurring(?: Selected)?$/}).click()
 await expect(groupPicker).not.toBeVisible()
 expect(await editor.locator('.modal-body').evaluate(el=>el.scrollTop)).toBe(groupScroll)
 await editor.getByLabel('Use this category and spending group for similar transactions in this account',{exact:true}).check()
 await editor.getByLabel('Description contains',{exact:true}).fill('Synthetic long description')
 await editor.getByRole('button',{name:'Save changes',exact:true}).click()
 await expect(editor).not.toBeVisible()
 await expect(page.getByText('Transaction saved and accepted',{exact:true})).toBeVisible()
 const saved=await page.evaluate(async()=>{
  const transactions=await fetch('/api/transactions').then(r=>r.json())
  const rules=await fetch('/api/rules').then(r=>r.json())
  return {transaction:transactions.items.find((r:any)=>r.description.startsWith('Synthetic long description')),rule:rules.find((r:any)=>r.pattern==='Synthetic long description')}
 })
 expect(saved.transaction.review_state).toBe('approved')
 expect(saved.rule.category_name).toBe(category)
 expect(saved.rule.account_id).toBe(1)
 expect(saved.rule.direction).toBe('debit')
 expect(saved.rule.spending_group_name).toBe('Recurring')
 // Removing the category returns this fixture to Needs review.
 await page.locator('.transaction-detail').filter({hasText:'Synthetic long description'}).click()
 await editor.getByLabel('Category',{exact:true}).click()
 await picker.getByRole('button',{name:/^Uncategorized/}).click()
 await editor.getByRole('button',{name:'Save changes',exact:true}).click()
 await expect(editor).not.toBeVisible()
 await expect(page.locator('.transaction-detail').filter({hasText:'Synthetic long description'})).toContainText('Needs category')
 // The group replaces the transfer checkbox, including a round trip back to category review.
 await page.locator('.transaction-detail').filter({hasText:'Synthetic long description'}).click()
 await expect(editor.getByRole('checkbox',{name:'This is a transfer, excluded from income and spending'})).toHaveCount(0)
 await editor.getByLabel('Spending group',{exact:true}).click()
 await groupPicker.getByRole('button',{name:/^Transfer(?: Selected)?$/}).click()
 await expect(editor.getByText('Transfer excluded from income and spending. No category is required.',{exact:true})).toBeVisible()
 await editor.getByRole('button',{name:'Save changes',exact:true}).click()
 await expect(editor).not.toBeVisible()
 const readTransaction=()=>page.evaluate(async()=>{
  const result=await fetch('/api/transactions').then(r=>r.json())
  return result.items.find((r:any)=>r.description.startsWith('Synthetic long description'))
 })
 const transfer=await readTransaction()
 expect(transfer.is_transfer).toBe(1)
 expect(transfer.spending_group_name).toBe('Transfer')
 expect(transfer.review_state).toBe('approved')
 expect(transfer.allocations[0].category_id).toBeNull()
 await page.locator('.transaction-detail').filter({hasText:'Synthetic long description'}).click()
 await editor.getByLabel('Spending group',{exact:true}).click()
 await groupPicker.getByRole('button',{name:/^Recurring(?: Selected)?$/}).click()
 await expect(editor.getByText('Transfer excluded from income and spending. No category is required.',{exact:true})).toHaveCount(0)
 await editor.getByRole('button',{name:'Save changes',exact:true}).click()
 await expect(editor).not.toBeVisible()
 const spending=await readTransaction()
 expect(spending.is_transfer).toBe(0)
 expect(spending.spending_group_name).toBe('Recurring')
 expect(spending.review_state).toBe('pending_review')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 expect(errors).toEqual([])
})

for(const hidden of [false,true])test(`linked transfer group cannot be cleared (${hidden?'hidden':'visible'} counterpart)`,async({page})=>{
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('demo')
 await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await page.getByRole('navigation',{name:'Main navigation',exact:true}).getByRole('button',{name:'Transactions',exact:true}).click()
 // Synthetic read response covers both counterpart visibility states without touching any real ledger.
 await page.route('**/api/transactions?id=5',async route=>{
  const response=await route.fetch();const result=await response.json()
  result.items[0].is_transfer=1
  result.items[0].transfer_counterpart_hidden=hidden
  result.items[0].transfer_counterpart_id=hidden?null:2
  await route.fulfill({json:result})
 })
 await page.locator('.transaction-detail').filter({hasText:'Synthetic long description'}).click()
 const editor=page.getByRole('dialog',{name:'Transaction #5',exact:true})
 await expect(editor.getByText('Transfer excluded from income and spending. No category is required.',{exact:true})).toBeVisible()
 await editor.getByLabel('Spending group',{exact:true}).click()
 const picker=page.getByRole('dialog',{name:'Select spending group',exact:true})
 await picker.getByRole('button',{name:/^Transfer(?: Selected)?$/}).click()
 await editor.getByLabel('Spending group',{exact:true}).click()
 await picker.getByRole('button',{name:/^Recurring(?: Selected)?$/}).click()
 await expect(page.locator('.toast:popover-open')).toContainText('Unlink the transfer before changing its spending group.')
 await expect(editor.getByLabel('Spending group',{exact:true})).toContainText('Transfer')
 await editor.getByLabel('Spending group',{exact:true}).click()
 await picker.getByRole('button',{name:/^Not set(?: Selected)?$/}).click()
 await expect(editor.getByLabel('Spending group',{exact:true})).toContainText('Transfer')
 await editor.locator('.editor-actions').getByRole('button',{name:'Close',exact:true}).click()
})
