import {test,expect,type Page} from '@playwright/test'
async function login(page:Page){await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()}
async function nav(page:Page,name:string,width:number){if(width===360&&!['Dashboard','Transactions','Review'].includes(name)){await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'More',exact:true}).click();await page.getByRole('navigation',{name:'More pages'}).getByRole('button',{name,exact:true}).click()}else await page.getByRole('navigation',{name:width===360?'Mobile navigation':'Main navigation',exact:true}).getByRole('button',{name,exact:true}).click()}
for(const width of [1440,360])test(`shared editor from categories accounts periods and nested references at ${width}px`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.setViewportSize({width,height:900});await login(page)
 await nav(page,'Categories',width)
 await page.getByRole('button',{name:/Groceries.*Expense/}).click()
 await expect(page.getByLabel('Filter by category',{exact:true})).toHaveValue('1')
 await page.locator('.transaction-detail').filter({hasText:'Market groceries'}).click()
 const editor=page.getByRole('dialog',{name:'Transaction #2',exact:true})
 await expect(editor).toBeVisible();await editor.getByLabel('Description',{exact:true}).fill('Market groceries edited '+width)
 await editor.getByRole('button',{name:'Save changes',exact:true}).click();await expect(editor).not.toBeVisible()
 await expect(page.locator('.transaction-detail').filter({hasText:'Market groceries edited '+width})).toBeVisible()
 await nav(page,'Categories',width);await page.getByRole('tab',{name:'Spending groups',exact:true}).click()
 await expect(page.getByRole('button',{name:'View transactions',exact:true})).toHaveCount(0)
 const entries=page.locator('.classification-group-entry');await expect(entries.first()).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 const heights=await entries.evaluateAll(rows=>rows.map(row=>row.getBoundingClientRect().height));expect(Math.max(...heights)-Math.min(...heights)).toBeLessThan(2)
 await page.getByRole('button',{name:'Edit Day-to-day',exact:true}).click();await expect(page.getByRole('dialog',{name:'Edit spending group',exact:true})).toBeVisible();await page.keyboard.press('Escape')
 await page.getByRole('button',{name:'Day-to-day',exact:true}).click();await expect(page.getByLabel('Filter by spending group',{exact:true})).toHaveValue('1')
 await nav(page,'Accounts',width)
 await page.getByRole('button',{name:'Everyday account',exact:true}).click()
 await expect(page.getByLabel('Accounts',{exact:true})).toHaveValue('1');await expect(page.getByLabel('Filter by category',{exact:true})).toHaveValue('')
 const row=page.locator('.transaction-detail').filter({hasText:'Market groceries'});await row.focus();await page.keyboard.press('Enter');await expect(editor).toBeVisible();await page.keyboard.press('Escape');await expect(editor).not.toBeVisible();await expect(row).toBeFocused()
 await nav(page,'Budgets',width)
 const card=page.locator('section.panel').filter({has:page.getByRole('heading',{name:/October 2026/})})
 await card.getByRole('button',{name:'October 2026',exact:true}).click();await expect(page.getByLabel('Budget period',{exact:true})).toHaveValue('1');await expect(page.getByLabel('Accounts',{exact:true})).toHaveValue('')
 await page.locator('.transaction-detail').filter({hasText:'Market groceries'}).click();await expect(editor).toBeVisible();await page.keyboard.press('Escape')
 await nav(page,'Budgets',width);await card.getByLabel('Actions for October 2026',{exact:true}).click();await card.getByRole('button',{name:'Edit dates',exact:true}).click()
 const periodEditor=page.getByRole('dialog',{name:'Edit budget period',exact:true})
 await periodEditor.getByLabel('Start date').fill('2026-10-22');await periodEditor.getByRole('button',{name:'Preview affected transactions',exact:true}).click()
 await periodEditor.getByText('View affected transactions',{exact:true}).click();await periodEditor.locator('.transaction-link').filter({hasText:'#2 ·'}).click()
 await expect(editor).toBeVisible();await page.keyboard.press('Escape');await expect(periodEditor).toBeVisible();await expect(periodEditor.getByLabel('Start date')).toHaveValue('2026-10-22');await page.keyboard.press('Escape')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([])
})
test('import history resolves saved ledger IDs and denied links show a toast',async({page})=>{
 await login(page)
 await page.route('**/api/imports**',route=>{const url=new URL(route.request().url());if(url.pathname==='/api/imports/9801')return route.fulfill({json:{id:9801,total:1,rows:[{row:1,date:'2026-10-21',description:'Original imported description',amount_cents:-84650,transaction_id:2}],decisions:{}}});return route.fulfill({json:{total:1,pending_total:0,items:[{id:9801,account_name:'Everyday account',account_ending:'8901',format:'fnb-live',run_id:'synthetic-history',created_at:'2026-10-03 08:00:00',status:'committed',inserted:1,skipped:0,row_count:1}]}})})
 await nav(page,'Transactions',1440);await page.getByRole('tab',{name:/Import activity/}).click();await page.locator('.activity-run>summary').click();await page.getByText('View imported, skipped, and rejected transactions',{exact:true}).click()
 await page.getByRole('button',{name:/Original imported description/}).click();const editor=page.getByRole('dialog',{name:'Transaction #2',exact:true});await expect(editor).toBeVisible();await expect(editor.getByLabel('Description',{exact:true})).toHaveValue(/Market groceries/);await page.keyboard.press('Escape')
 await page.route('**/api/transactions?id=2',route=>route.fulfill({json:{total:0,items:[]}}));await page.getByRole('button',{name:/Original imported description/}).click();await expect(page.locator('.toast:popover-open')).toContainText('do not have access');await expect(page.getByRole('dialog')).toHaveCount(0)
})
