import {test,expect} from '@playwright/test'
for(const width of [1440,360])for(const theme of ['light','dark'])test(`classification filters across tabs ${width} ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:900})
 await page.addInitScript(t=>localStorage.setItem('finance-theme',t),theme)
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('demo')
 await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 // Reset the target through the normal API so preceding editor tests do not change this fixture.
 const me=(await (await page.request.get('/api/me')).json()),original=(await (await page.request.get('/api/transactions?id=5')).json()).items[0]
 await page.request.put('/api/transactions/5',{headers:{'X-CSRF-Token':me.csrf},data:{version:original.version,date:original.date,amount_cents:original.amount_cents,description:original.description,is_transfer:false,assignment:'auto',allocations:[{category_id:null,amount_cents:original.amount_cents}]}})
 const current=(await (await page.request.get('/api/transactions?id=5')).json()).items[0];await page.request.post('/api/transactions/seen',{headers:{'X-CSRF-Token':me.csrf},data:{seen:false,items:[{id:5,version:current.version}]}})

 const nav=page.getByRole('navigation',{name:width===360?'Mobile navigation':'Main navigation',exact:true})
 await nav.getByRole('button',{name:'Transactions',exact:true}).click()
 await page.getByRole('button',{name:'Filters',exact:true}).click();await page.getByLabel('Search transactions',{exact:true}).fill('Synthetic long description')
 await page.getByLabel('Filter by category',{exact:true}).selectOption('uncategorized')
 const rows=page.locator('.transaction-detail')
 await expect(rows).toHaveCount(1)
 await expect(rows.first()).toContainText('Synthetic long description')
 await page.getByRole('tab',{name:/Needs review/}).click()
 await expect(page.getByLabel('Filter by category',{exact:true})).toHaveValue('uncategorized')
 await expect(rows).toHaveCount(1)
 // Changing filters clears the personal seen selection.
 await page.getByRole('checkbox',{name:/^Select Synthetic long description/}).check()
 await expect(page.getByRole('button',{name:'Mark seen (1)',exact:true})).toBeVisible()
 await page.getByLabel('Filter by category',{exact:true}).selectOption('1')
 await expect(page.getByRole('button',{name:'Mark seen (1)',exact:true})).not.toBeVisible()
 await expect(rows).toHaveCount(0)
 await page.getByRole('tab',{name:'All transactions',exact:true}).click()
 await page.getByLabel('Search transactions',{exact:true}).fill('Market groceries')
 await expect(rows).toHaveCount(1)
 await expect(rows.first()).toContainText('Market groceries')
 await page.getByLabel('Money direction',{exact:true}).selectOption('in')
 await expect(rows).toHaveCount(0)
 await page.getByRole('region',{name:'Transaction filters',exact:true}).getByRole('button',{name:'Clear filters',exact:true}).click()
 await expect(rows.filter({hasText:'Synthetic long description'})).toHaveCount(1)
 await expect(rows.filter({hasText:'Market groceries'})).toHaveCount(1)
 const allCount=await rows.count()
 expect(allCount).toBeGreaterThanOrEqual(5)
 await page.getByLabel('Filter by spending group',{exact:true}).selectOption('unassigned')
 await expect(rows.filter({hasText:'Market groceries'})).toHaveCount(1)
 await expect(rows.locator('.group-label')).toHaveCount(0)
 await page.getByLabel('Search transactions',{exact:true}).fill(`Unmapped filter purchase ${width} ${theme}`)
 await page.getByRole('tab',{name:/Import activity/}).click()
 await expect(page.getByLabel('Filter by spending group',{exact:true})).toHaveValue('unassigned')
 await expect(page.getByText('No matching import activity',{exact:true})).toBeVisible()
 // Create categorized and uncategorized imports with normal explicit upload controls.
 await page.getByText('Upload a bank export',{exact:true}).click()
 await page.getByLabel('Import into account',{exact:true}).selectOption('1')
 const description=`Unmapped filter purchase ${width} ${theme}`
 const csv='ACCOUNT TRANSACTION HISTORY\n\nName:,Synthetic\nAccount:,12345678901,Fusion\nBalance:,100.00\n\nDate, Amount, Balance, Description\n2026/10/27,-1.23,100.00,'+description+'\n'
 await page.locator('input[type=file]').setInputFiles({name:`filter-${width}-${theme}.csv`,mimeType:'text/csv',buffer:Buffer.from(csv)})
 await page.getByRole('button',{name:'Import statement',exact:true}).click()
 await expect(page.getByRole('tab',{name:/Needs review/})).toHaveAttribute('aria-selected','true')
 await page.getByLabel('Filter by category',{exact:true}).selectOption('uncategorized')
 await page.getByLabel('Search transactions',{exact:true}).fill(description)
 await expect(rows).toHaveCount(1)
 await page.getByRole('tab',{name:/Import activity/}).click()
 await expect(page.locator('.activity-run')).toHaveCount(1)
 await page.locator('.activity-run>summary').click()
 await expect(page.locator('.activity-account')).toHaveCount(1)
 await page.getByRole('button',{name:'View transactions',exact:true}).click()
 await expect(page.getByRole('tab',{name:'All transactions',exact:true})).toHaveAttribute('aria-selected','true')
 await expect(page.getByLabel('Filter by category',{exact:true})).toHaveValue('uncategorized')
 await expect(rows).toHaveCount(1)
 await expect(rows.first()).toContainText(description)
 await page.getByRole('tab',{name:/Import activity/}).click()
 await page.getByLabel('Filter by category',{exact:true}).selectOption('1')
 await expect(page.getByText('No matching import activity',{exact:true})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('region',{name:'Transaction filters',exact:true}).getByRole('button',{name:'Clear filters',exact:true}).click()
 await expect(page.getByLabel('Search transactions',{exact:true})).toHaveValue('')
 await expect(page.getByLabel('Filter by category',{exact:true})).toHaveValue('')
 expect(errors).toEqual([])
})
