import {test,expect,type Page} from '@playwright/test'
async function login(page:Page){await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('demo');await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()}
async function nav(page:Page,name:string,width:number){if(width===360&&!['Dashboard','Transactions','Review'].includes(name)){await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'More',exact:true}).click();await page.getByRole('navigation',{name:'More pages'}).getByRole('button',{name,exact:true}).click()}else await page.getByRole('navigation',{name:width===360?'Mobile navigation':'Main navigation',exact:true}).getByRole('button',{name,exact:true}).click()}
for(const width of [1440,360])for(const theme of ['light','dark'])test(`focused workspaces ${width} ${theme}`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.addInitScript(theme=>localStorage.setItem('finance-theme',theme),theme);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await login(page)

 const me=(await (await page.request.get('/api/me')).json()),t=(await (await page.request.get('/api/transactions?id=5')).json()).items[0]
 const reset=await page.request.put('/api/transactions/5',{headers:{'X-CSRF-Token':me.csrf},data:{version:t.version,date:t.date,amount_cents:t.amount_cents,description:t.description,is_transfer:false,assignment:'auto',note:'',clear_merchant:true,tag_ids:[],allocations:[{category_id:null,amount_cents:t.amount_cents}]}});expect(reset.ok()).toBe(true)
 const current=(await (await page.request.get('/api/transactions?id=5')).json()).items[0];await page.request.post('/api/transactions/seen',{headers:{'X-CSRF-Token':me.csrf},data:{seen:false,items:[{id:5,version:current.version}]}})
 await nav(page,'Transactions',width);await expect(page.getByLabel('From date',{exact:true})).toBeHidden();await expect(page.getByLabel('Search transactions',{exact:true})).toBeVisible();await expect(page.getByLabel('Budget periods',{exact:true})).toHaveCount(0)
 if(width===1440){const box=await page.locator('.transaction-panel').boundingBox();expect(box!.y).toBeLessThan(700)}
 await page.getByRole('tab',{name:/Needs review/}).click();await expect(page.getByLabel('Active filters')).toContainText('Needs category');await expect(page.getByLabel('Active filters')).not.toContainText('Unseen')
 await page.getByRole('button',{name:'Filters (1)',exact:true}).click();await page.getByLabel('Acceptance',{exact:true}).selectOption('');await page.getByLabel('Seen by you',{exact:true}).selectOption('');await page.getByLabel('From date',{exact:true}).fill('2026-10-25');await page.getByLabel('To date',{exact:true}).fill('2026-10-25');await page.getByRole('button',{name:'Filters (2)',exact:true}).click();await expect(page.getByLabel('Active filters')).toContainText('From 2026-10-25');await expect(page.getByLabel('From date',{exact:true})).toBeHidden();await expect(page.locator('.transaction-detail')).toHaveCount(1)
 await page.locator('.transaction-detail').click();const editor=page.getByRole('dialog',{name:'Transaction #5',exact:true});await expect(editor.getByLabel('Transaction note',{exact:true})).toBeHidden();await editor.locator('summary').filter({hasText:'Notes, merchant and tags'}).click();await editor.getByLabel('Transaction note',{exact:true}).fill('Draft retained');await editor.locator('summary').filter({hasText:'Notes, merchant and tags'}).click();await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'Unsaved changes'})).toBeVisible();await page.getByRole('button',{name:'Discard changes'}).click();await expect(editor).toBeHidden()
 await nav(page,'Budgets',width);await expect(page.getByRole('heading',{name:'Trends',exact:true})).toBeHidden();await page.getByLabel('Actions for October 2026',{exact:true}).click();await expect(page.getByRole('button',{name:'Rebalance',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Rebalance',exact:true})).toBeHidden();await expect(page.getByLabel('Actions for October 2026',{exact:true})).toBeFocused();await page.getByRole('tab',{name:'Trends & reports'}).click();await expect(page.getByRole('heading',{name:'Trends',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'New period',exact:true})).toBeHidden()
 await nav(page,'Accounts',width);await expect(page.getByText('Last successful transaction import/check: Never').first()).toBeHidden();await page.locator('.secondary-section > summary').click();await expect(page.getByText('Last successful transaction import/check: Never').first()).toBeVisible()
 await nav(page,'Categories',width);await expect(page.getByRole('tab',{name:'Merchant rules',exact:true})).toBeVisible();await page.getByRole('tab',{name:'Merchant rules',exact:true}).click();await page.getByRole('button',{name:'Add merchant rule'}).click();await expect(page.getByLabel('Priority',{exact:true})).toBeHidden();await page.getByRole('dialog').locator('summary').filter({hasText:/^More options/}).click();await expect(page.getByLabel('Priority',{exact:true})).toBeVisible();await page.getByLabel('Scope',{exact:true}).selectOption('1');await page.getByLabel('New merchant name',{exact:true}).fill('Validation merchant');await page.getByLabel('Description contains',{exact:true}).fill('Fuel');await page.getByLabel('Priority',{exact:true}).fill('1000001');await page.getByRole('dialog').locator('summary').filter({hasText:/^More options/}).click();await page.getByRole('button',{name:'Save rule',exact:true}).click();await expect(page.getByLabel('Priority',{exact:true})).toBeVisible();await expect(page.getByLabel('Priority',{exact:true})).toBeFocused();await expect(page.getByLabel('Priority',{exact:true})).toHaveAttribute('aria-invalid','true');await page.keyboard.press('Escape')
 await nav(page,'Settings',width);await page.getByRole('tab',{name:'Branding',exact:true}).click();await expect(page.getByLabel('Display name',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([])
})
