import {test,expect,type Page} from '@playwright/test'
async function login(page:Page){
 await page.goto('/')
 await page.getByLabel('Username',{exact:true}).fill('demo')
 await page.getByLabel('Password',{exact:true}).fill('synthetic-browser-password')
 await page.getByRole('button',{name:'Sign in',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible()
 await expect(page.getByText('Loading this period…')).not.toBeVisible()
}
async function navigate(page:Page,name:string,mobile=false){
 if(mobile&&!['Dashboard','Transactions','Review'].includes(name)){await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('button',{name:'More',exact:true}).click();await page.getByRole('navigation',{name:'More pages'}).getByRole('button',{name,exact:true}).click()}
 else await page.getByRole('navigation',{name:mobile?'Mobile navigation':'Main navigation',exact:true}).getByRole('button',{name,exact:true}).click()
 await expect(page.getByRole('heading',{name,exact:true,level:1})).toBeVisible()
}
async function noOverflow(page:Page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
test('desktop dashboard, keyboard review, rules, and split approval',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
 await login(page)
 await expect(page.getByRole('heading',{name:'Spending by category'})).toBeVisible()
 await expect(page.getByText('Pending transactions are included')).toBeVisible()
 await noOverflow(page)
 await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true})
 await navigate(page,'Review')
 await page.getByRole('button').filter({hasText:'Synthetic long description'}).click()
 const dialog=page.getByRole('dialog')
 await expect(dialog).toBeVisible()
 await dialog.getByLabel('Category',{exact:true}).click()
 await page.getByRole('dialog',{name:'Select category',exact:true}).getByRole('button').filter({hasText:'Groceries'}).first().click()
 await dialog.getByRole('button',{name:'Add split'}).click()
 await dialog.getByLabel('Amount',{exact:true}).nth(0).fill('-750.00')
 await dialog.getByLabel('Amount',{exact:true}).nth(1).fill('-500.00')
 await dialog.getByLabel('Category 2',{exact:true}).click()
 await page.getByRole('dialog',{name:'Select category 2',exact:true}).getByRole('button').filter({hasText:'Eating out'}).first().click()
 await dialog.getByRole('button',{name:'Save changes'}).click()
 await expect(dialog).not.toBeVisible()
 await page.getByRole('button').filter({hasText:'Synthetic long description'}).click()
 await page.getByRole('dialog').getByRole('button',{name:'Approve current details'}).click()
 await expect(page.getByRole('dialog')).not.toBeVisible()
 await expect(page.getByRole('button').filter({hasText:'Synthetic long description'})).toHaveCount(0)
 await navigate(page,'Categories')
 await page.getByRole('button',{name:'Add rule',exact:true}).click()
 await page.getByRole('dialog').getByLabel('Description contains').fill('Station')
 await page.getByRole('dialog').getByLabel('Category',{exact:true}).selectOption('2')
 await page.getByRole('dialog').getByRole('button',{name:'Save rule'}).click()
 await expect(page.getByRole('dialog')).not.toBeVisible()
 await expect(page.getByText('Description contains “Station”')).toBeVisible()
 expect(errors).toEqual([])
})
test('360px mobile upload, review, period preview, and both themes',async({page})=>{
 await page.setViewportSize({width:360,height:800})
 await login(page);await noOverflow(page)
 await page.screenshot({path:'test-results/dashboard-mobile-light.png',fullPage:true})
 await navigate(page,'Settings',true)
 await page.getByRole('combobox',{name:'Appearance',exact:true}).selectOption('dark')
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
 await noOverflow(page)
 await navigate(page,'Dashboard',true)
 await expect(page.getByRole('heading',{name:'Spending by category'})).toBeVisible()
 await page.screenshot({path:'test-results/dashboard-mobile-dark.png',fullPage:true})
 await navigate(page,'Imports',true)
 const csv='ACCOUNT TRANSACTION HISTORY\n\nName:,Synthetic\nAccount:,12345678901,Fusion\nBalance:,100.00\n\nDate, Amount, Balance, Description\n2026/10/27,-12.34,100.00,Market mobile purchase\n'
 await page.locator('input[type=file]').setInputFiles({name:'mobile.csv',mimeType:'text/csv',buffer:Buffer.from(csv)})
 await page.getByRole('button',{name:'Preview import',exact:true}).click()
 await expect(page.getByRole('heading',{name:'mobile.csv',exact:true})).toBeVisible()
 await noOverflow(page)
 await page.getByRole('button',{name:'Confirm import',exact:true}).click()
 await expect(page.getByText('1 transactions imported; 0 skipped. New entries await review.')).toBeVisible()
 await navigate(page,'Review',true)
 await page.getByRole('button').filter({hasText:'Market mobile purchase'}).click()
 await expect(page.getByRole('dialog')).toBeVisible()
 await noOverflow(page)
 await page.getByRole('dialog').getByRole('button',{name:'Approve current details'}).click()
 await expect(page.getByRole('dialog')).not.toBeVisible()
 await navigate(page,'Budgets',true)
 await page.getByRole('button',{name:'Edit dates'}).first().click()
 await page.getByLabel('Start date',{exact:true}).fill('2026-10-19')
 await page.getByRole('button',{name:'Preview assignment changes'}).click()
 await expect(page.getByText(/automatic assignments will change/)).toBeVisible()
 await noOverflow(page)
 await page.getByRole('button',{name:'Save period',exact:true}).click()
 await expect(page.getByRole('dialog')).not.toBeVisible()
 await navigate(page,'Settings',true)
 await page.getByRole('combobox',{name:'Appearance',exact:true}).selectOption('light')
 await expect(page.locator('html')).toHaveAttribute('data-theme','light')
 await page.getByRole('tab',{name:'Backups',exact:true}).click()
 await page.getByRole('button',{name:'Back up now'}).click()
 await expect(page.getByText('Backup completed and integrity checked')).toBeVisible()
})
test('account setup, user setup, category limits and explicit bulk review',async({page})=>{
 await login(page)
 await navigate(page,'Settings')
 await page.getByRole('tab',{name:'Accounts',exact:true}).click()
 await page.getByRole('button',{name:'Add account',exact:true}).click()
 await page.getByLabel('Account name').fill('Test private account')
 await page.getByLabel('FNB account number').fill('44444444444')
 await page.getByLabel('Include in the household budget').uncheck()
 await page.getByRole('button',{name:'Save account',exact:true}).click()
 await navigate(page,'Accounts')
 await expect(page.getByRole('heading',{name:'Test private account',exact:true})).toBeVisible()
 await navigate(page,'Settings')
 await page.getByRole('tab',{name:'Users & access',exact:true}).click()
 await page.getByRole('button',{name:'Add user',exact:true}).click()
 await page.getByRole('dialog').getByLabel('Username').fill('guest')
 await page.getByLabel('Initial password').fill('synthetic-guest-password')
 await page.getByLabel('Household budget member').uncheck()
 await page.getByRole('button',{name:'Create user',exact:true}).click()
 await expect(page.getByText('guest',{exact:true}).first()).toBeVisible()
 await page.getByLabel('User',{exact:true}).selectOption({label:'guest'})
 await page.getByLabel('Account',{exact:true}).selectOption({label:'Test private account · Private'})
 await page.getByRole('button',{name:'Update access'}).click()
 await expect(page.getByText('Account access updated')).toBeVisible()
 await navigate(page,'Budgets')
 await page.getByRole('button',{name:'Edit limits'}).first().click()
 await page.getByLabel('Groceries',{exact:true}).fill('5000.00')
 await page.getByRole('button',{name:'Save limits',exact:true}).click()
 await expect(page.getByRole('dialog')).not.toBeVisible()
 await navigate(page,'Review')
 await page.getByRole('checkbox',{name:'Select pending transactions on this page'}).check()
 await page.getByRole('button',{name:/Approve \d+/}).click()
 await expect(page.getByText('Nothing awaiting review')).toBeVisible()
})
