import {MerchantLogoField} from './MerchantAvatar'
import {ChevronLeft,ChevronRight} from 'lucide-react'
import {useEffect,useState} from 'react'
import {api,cents,money,download} from './api'
import {Button,Field,Form,Modal,Loading,Badge,Empty,Pagination} from './ui'
import {ChoiceField,CategoryChoice,type Choice} from './Choices'
import {PagedSelect,usePagedList,ListStatus,ListNavigation} from './PagedList'
import {useTask} from './shared/useTask'
import {type PageProps,type Row} from './shared/types'
import {useTransactionAccess} from './TransactionAccess'
import {moneyError} from './validation'

export function TransactionLabels({account,merchant,tags,onMerchant,onTags,notify,disabled,globalMerchants=false}:{globalMerchants?:boolean;account:number;merchant:number|null;tags:Row[];onMerchant:(id:number|null,choice?:Choice)=>void;onTags:(rows:Row[])=>void;notify:PageProps['notify'];disabled:boolean}){
 const[logo,setLogo]=useState(''),[logoBusy,setLogoBusy]=useState(false)
 const[create,setCreate]=useState<'merchant'|'tag'|null>(null),[name,setName]=useState(''),[revision,setRevision]=useState(0)
 const{busy,run}=useTask(notify)
 return <><div className="form-grid"><ChoiceField key={'merchant'+revision} label="Merchant" value={merchant} onChange={onMerchant} options={[]} source={'/labels?kind=merchant&account='+account} disabled={disabled} onError={message=>notify(message,true)}/><ChoiceField key={'tag'+revision} label="Add tag" value={null} options={[]} source={'/labels?kind=tag&account='+account} disabled={disabled||tags.length>=20} onError={message=>notify(message,true)} onChange={(id,row)=>{if(id&&row&&!tags.some(t=>t.id===id))onTags([...tags,row])}}/></div><div className="toolbar-actions">{tags.map(tag=><Button key={tag.id} disabled={disabled} variant="quiet" onClick={()=>onTags(tags.filter(t=>t.id!==tag.id))}>{tag.name} ×</Button>)}{!disabled&&<><Button onClick={()=>{setCreate('merchant');setName('');setLogo('')}}>New merchant</Button><Button disabled={tags.length>=20} onClick={()=>{setCreate('tag');setName('')}}>New tag</Button></>}</div>
 {create&&<Modal title={'New '+create} onClose={()=>setCreate(null)}><Form onSubmit={()=>run(async()=>{const result=await api('/labels','POST',{kind:create,account_id:create==='merchant'&&globalMerchants?0:account,name,...(create==='merchant'&&logo?{logo_data:logo}:{})});if(create==='merchant')onMerchant(result.id,{id:result.id,name:name.trim(),category_id:result.category_id,spending_group_id:result.spending_group_id});else if(!tags.some(t=>t.id===result.id))onTags([...tags,{id:result.id,name:name.trim()}]);setRevision(v=>v+1);setCreate(null)})}><Field label="Name" validate={v=>Array.from(v.trim()).length<(create==='merchant'?2:1)?'Use a longer name.':''}><input autoFocus required minLength={create==='merchant'?2:1} maxLength={create==='merchant'?100:40} value={name} onChange={e=>setName(e.target.value)}/></Field>{create==='merchant'&&<MerchantLogoField name={name||'Merchant'} value={logo} onChange={setLogo} onBusy={setLogoBusy}/>}<p className="footnote">Available {create==='merchant'&&globalMerchants?'across all accounts':'for this account'}. Selecting it will be saved with the transaction.</p><Button variant="primary" loading={busy} disabled={logoBusy} type="submit">Create and select</Button></Form></Modal>}</>
}
export function BulkEditor({rows,data,notify,refresh,onClose,onDone,ruleId}:Pick<PageProps,'data'|'notify'|'refresh'>&{rows:Row[];onClose:()=>void;onDone:()=>void;ruleId?:number}){
 const[operation,setOperation]=useState(ruleId?'merchant_rule':'category'),[category,setCategory]=useState<number|null>(null),[group,setGroup]=useState<number|null>(null),[mode,setMode]=useState('missing'),[name,setName]=useState(''),[preview,setPreview]=useState<Row|null>(null)
 const{busy,run}=useTask(notify)
 const change=(action:()=>void)=>{action();setPreview(null)}
 return <Modal title={'Edit '+rows.length+' selected transactions'} size="wide" onClose={onClose}><Form onSubmit={()=>run(async()=>setPreview(await api('/transactions/bulk/preview','POST',{items:rows.map(t=>({id:t.id,version:t.version})),operation,category_id:category,group_id:group,mode,name,rule_id:ruleId})))}>
 {!ruleId&&<Field label="Change"><select value={operation} onChange={e=>change(()=>setOperation(e.target.value))}>{[['category','Category'],['group','Spending group'],['merchant','Set merchant'],['clear_merchant','Clear merchant'],['add_tag','Add tag'],['remove_tag','Remove tag']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></Field>}
 {operation==='category'&&<><CategoryChoice data={data} value={category} onChange={id=>change(()=>setCategory(id))} refresh={refresh} notify={notify}/><Field label="Category mode"><select value={mode} onChange={e=>change(()=>setMode(e.target.value))}><option value="missing">Fill missing categories; preserve assigned categories and splits</option><option value="unsplit">Replace category on unsplit transactions only</option></select></Field></>}
 {operation==='group'&&<ChoiceField source="/spending-groups" label="Spending group" value={group} options={data.spendingGroups.map(g=>({id:g.id,name:g.name,color:g.color}))} onChange={id=>change(()=>setGroup(id))}/>}
 {['merchant','add_tag','remove_tag'].includes(operation)&&<Field label={operation==='merchant'?'Merchant name':'Tag name'} hint="Names are matched within each account. New names are created when you apply the changes."><input required minLength={operation==='merchant'?2:1} maxLength={operation==='merchant'?100:40} value={name} onChange={e=>change(()=>setName(e.target.value))}/></Field>}
 <p className="footnote">Amounts and allocation notes are preserved. Manual changes mark the changed transactions seen by you. Linked transfers are protected.</p><Button loading={busy} disabled={operation==='category'&&!category} type="submit">Preview changes</Button></Form>
 {preview&&<><p>{preview.changed} transactions will change.</p>{preview.items.map((t:Row)=><details key={t.id} className="details"><summary>#{t.id} · {t.description} · {t.reason}</summary><div className="form-grid"><div><h3>Before</h3><BulkDetails value={t.before} data={data}/></div><div><h3>After</h3><BulkDetails value={t.after} data={data}/></div></div></details>)}<div className="editor-actions"><Button variant="primary" loading={busy} disabled={!preview.changed} onClick={()=>run(async()=>{await api('/transactions/bulk/apply','POST',{token:preview.token});onDone()},'Changes saved')}>Apply preview</Button><Button onClick={()=>setPreview(null)}>Revise</Button></div></>}
 </Modal>
}
function BulkDetails({value,data}:{value:Row;data:PageProps['data']}){return <><p>{money(value.amount_cents)} · {value.is_transfer?'Transfer':value.spending_group_name||data.spendingGroups.find(g=>g.id===value.spending_group_id)?.name||'No spending group'}</p>{value.allocations.map((a:Row,i:number)=><p key={i}>{a.category_id?a.category_name||data.categories.find(c=>c.id===a.category_id)?.name||'Category #'+a.category_id:'Uncategorized'} · {money(a.amount_cents)}{a.note?' · '+a.note:''}</p>)}{value.merchant_name&&<p>Merchant: {value.merchant_name}</p>}{value.clear_merchant&&<p>Merchant cleared</p>}{value.tag_names&&<p>Tags: {value.tag_names.join(', ')||'None'}</p>}</>}
export function AccountHealth({revision,notify,onBanking,onImports}:{revision:number;notify:PageProps['notify'];onBanking:()=>void;onImports:()=>void}){
 const[items,setItems]=useState<Row[]|null>(null),[page,setPage]=useState(0),[total,setTotal]=useState(0)
 useEffect(()=>{let alive=true;api('/accounts/health?page='+page).then(v=>{if(alive){setItems(v.items);setTotal(v.total)}}).catch(e=>notify(e.message,true));return()=>{alive=false}},[revision,page])
 if(!items)return <Loading>Loading import health</Loading>
 return <section className="panel"><div className="section-head"><h2>Transaction import health</h2><div className="toolbar-actions"><Button onClick={onBanking}>Banking</Button><Button onClick={onImports}>Import activity</Button></div></div>{items.map(a=><div className="line health-row" key={a.id}><div><strong>{a.name}</strong><small>Balance date: {a.balance_date||'Unavailable'}</small><small>Last successful transaction import/check: {a.last_imported?a.last_imported+' UTC':'Never'}</small>{a.last_fetched&&a.last_fetched!==a.last_imported&&<small>Last fetch: {a.last_fetched} UTC</small>}{a.next_due&&<small>Next due: {new Date(a.next_due*1000).toLocaleString()}</small>}<small>Coverage may be incomplete{a.import_issues?' · '+a.import_issues+' imports need attention':''}.</small></div><Badge tone={a.state==='ready'?'good':a.state==='needs_attention'?'bad':'pending'}>{String(a.state).replaceAll('_',' ')}</Badge></div>)}<Pagination page={page} total={total} onChange={setPage}/></section>
}
export function PeriodNavigation({period,revision,onChange,notify}:{period:string;revision:number;onChange:(id:string)=>void;notify:PageProps['notify']}){
 const[nav,setNav]=useState<Row|null>(null)
 useEffect(()=>{let alive=true;api('/periods/navigation?period='+period).then(v=>alive&&setNav(v)).catch(e=>notify(e.message,true));return()=>{alive=false}},[period,revision])
 return <nav className="toolbar-actions period-navigation" aria-label="Budget periods"><Button variant="quiet" aria-label="Previous period" disabled={!nav?.previous} title={nav?.previous?.name} onClick={()=>onChange(String(nav!.previous.id))}><ChevronLeft size={18}/></Button><Button variant="quiet" disabled={!nav?.current} onClick={()=>onChange(String(nav!.current.id))}>Current period</Button><Button variant="quiet" aria-label="Next period" disabled={!nav?.next} title={nav?.next?.name} onClick={()=>onChange(String(nav!.next.id))}><ChevronRight size={18}/></Button></nav>
}
export function DailyGuide({period,remaining,hasTargets,account}:{period:Row;remaining:number;hasTargets:boolean;account:string}){
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Johannesburg',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
 if(!hasTargets||account||today<period.start_date||today>period.end_date)return null
 const days=Math.round((Date.parse(period.end_date)-Date.parse(today))/86400000)+1
 if(remaining<0)return <p className="negative">Over budget by {money(-remaining)}</p>
 if(remaining===0)return <p className="footnote">No budget remaining.</p>
 return <p className="footnote">Daily budget guide: <strong>{money(Math.floor(remaining/days))}</strong> over {days} remaining {days===1?'day':'days'}, including today. Based on your remaining budget.</p>
}
export function BudgetTrends({data,period,account,revision,notify,refresh}:PageProps&{period:string;account:string}){
 const[count,setCount]=useState('6'),[year,setYear]=useState(''),[category,setCategory]=useState(''),[group,setGroup]=useState(''),[report,setReport]=useState<Row|null>(null),[loading,setLoading]=useState(false)
 const {viewTransactions}=useTransactionAccess(),{busy,run}=useTask(notify)
 const query=new URLSearchParams({period,account,count,...(year.length===4&&Number(year)>=1900&&Number(year)<=9998?{year}:{}),...(category?{category}:{}),...(group?{spending_group:group}:{})}).toString()
 useEffect(()=>{let alive=true;setLoading(true);api('/budget/reports?'+query).then(v=>alive&&setReport(v)).catch(e=>{if(alive){setReport(null);notify(e.message,true)}}).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[query,revision])
 return <section className="panel"><div className="section-head"><h2>Trends</h2><Button loading={busy} onClick={()=>run(()=>download('/budget/export?'+query,'budget.csv'))}>Export report</Button></div><div className="report-filter-grid"><Field label="Compare"><select value={count} onChange={e=>{setCount(e.target.value);setYear('')}}><option value="1">This period only</option><option value="2">Selected and previous period</option><option value="6">Last 6 saved periods</option><option value="12">Last 12 saved periods</option></select></Field><Field label="Budget year" hint="Includes each full budget period that starts in this year."><input type="number" min="1900" max="9998" placeholder="Optional" value={year} onChange={e=>{setYear(e.target.value)}}/></Field><PagedSelect url="/spending-groups" label="Spending group" value={group} onChange={setGroup} empty="All groups" specialOptions={[{value:'0',label:'No spending group'}]}/><PagedSelect url="/categories" label="Category" value={category} onChange={setCategory} empty="All categories" specialOptions={[{value:'0',label:'Uncategorized'}]}/></div>
 {loading&&<Loading>Loading trends</Loading>}{report&&!loading&&<><p>{account?'Actual spending for this account.':'Shared household budget and spending.'} Transfers excluded; refunds reduce expense spending.</p>{!report.periods.length?<Empty title="No saved periods in this range"/>:report.periods.map((p:Row)=><div className="line report-row" key={p.id}><div><strong>{p.name}</strong><small>{p.start_date} – {p.end_date}</small></div><div><strong>{money(p.spent_cents)} spent</strong>{report.has_targets&&<small>{money(p.budget_cents)} budget · {money(p.remaining_cents)} left</small>}</div></div>)}{!!report.periods.length&&<p className="footnote">Average spending per saved period: {money(Math.round(report.spent_cents/report.periods.length))}. A comparison only; your limits are unchanged.</p>}<details className="details"><summary>Group and category detail</summary>{report.entries.map((e:Row,i:number)=><div className="line" key={i}><div><strong>{e.period_name} · {e.group_name} · {e.category_name}</strong></div><span>{money(e.spent_cents)} spent{report.has_targets&&e.has_budget?' · '+money(e.budget_cents)+' budget · '+money(e.remaining_cents)+' left':''}</span></div>)}</details>{report.excluded_count>0&&<div className="toolbar-actions"><p>{report.excluded_count} household transactions in these dates are unassigned or outside budgets.</p><Button onClick={()=>viewTransactions({account,excluded:true,dateFrom:report.periods.map((p:Row)=>p.start_date).sort()[0],dateTo:report.periods.map((p:Row)=>p.end_date).sort().at(-1)})}>Inspect transaction assignments</Button></div>}</>}
 </section>
}
export function Rebalance({period,notify,onClose,onDone}:{period:Row;notify:PageProps['notify'];onClose:()=>void;onDone:()=>void}){
 const[entries,setEntries]=useState<Row[]>([]),[from,setFrom]=useState(''),[to,setTo]=useState(''),[amount,setAmount]=useState(''),[preview,setPreview]=useState<Row|null>(null)
 const{busy,run}=useTask(notify)
 useEffect(()=>{api('/budget/reports?count=1&period='+period.id).then(v=>setEntries(v.entries.filter((e:Row)=>e.has_budget))).catch(e=>notify(e.message,true))},[period.id])
 const change=(fn:()=>void)=>{fn();setPreview(null)}
 return <Modal title={'Rebalance · '+period.name} onClose={onClose}><Form onSubmit={()=>run(async()=>{const f=entries[Number(from)],t=entries[Number(to)];setPreview(await api('/periods/'+period.id+'/rebalance/preview','POST',{version:period.version,from_group:f.group_id,from_category:f.category_id,to_group:t.group_id,to_category:t.category_id,amount_cents:cents(amount)}))})}><div className="form-grid">{[['From',from,setFrom],['To',to,setTo]].map(([label,value,setter])=><Field key={String(label)} label={String(label)}><select required value={String(value)} onChange={e=>change(()=>{(setter as (v:string)=>void)(e.target.value)})}><option value="">Choose budget entry</option>{entries.map((e,i)=><option key={i} value={i}>{e.group_name} · {e.category_name} · {money(e.budget_cents)} budget · {money(e.remaining_cents)} left</option>)}</select></Field>)}</div><Field label="Amount to move" validate={v=>moneyError(v)|| (cents(v)<=0?'Use a positive amount.':'')}><input required inputMode="decimal" value={amount} onChange={e=>change(()=>setAmount(e.target.value))}/></Field><p className="footnote">Moves only unspent budget between existing entries. Total budget and upcoming periods stay unchanged.</p><Button type="submit" loading={busy}>Preview rebalance</Button></Form>{preview&&<><p>{preview.before[0].group_name} · {preview.before[0].category_name}: {money(preview.before[0].amount_cents)} → {money(preview.from_after)}</p><p>{preview.before[1].group_name} · {preview.before[1].category_name}: {money(preview.before[1].amount_cents)} → {money(preview.to_after)}</p><Button variant="primary" loading={busy} onClick={()=>run(async()=>{await api('/periods/'+period.id+'/rebalance/apply','POST',{token:preview.token});onDone()},'Budget rebalanced')}>Apply rebalance</Button></>}</Modal>
}
