import {PagedSelect,usePagedList,ListStatus,ListNavigation} from './PagedList'
import {useEffect,useRef,useState} from 'react'
import {Upload,FileText} from 'lucide-react'
import {api,money} from './api'
import {Button,Field,Badge,Empty,Loading,Pagination} from './ui'
import {useTask,type PageProps,type Row} from './App'
export function Imports({data,revision,refresh,notify}:PageProps){
 const editors=data.accounts.filter(a=>a.role==='editor')
 const[account,setAccount]=useState(String(editors[0]?.id||'')),[files,setFiles]=useState<File[]>([]),[previews,setPreviews]=useState<Row[]>([]),[history,setHistory]=useState<Row[]>([])
 const historyStamp=useRef({version:'',revision})
 const[historyPage,setHistoryPage]=useState(0),[historyTotal,setHistoryTotal]=useState(0),[loading,setLoading]=useState(true),[historyError,setHistoryError]=useState(''),[retry,setRetry]=useState(0)
 const{busy,run}=useTask(notify);const input=useRef<HTMLInputElement>(null),dragDepth=useRef(0)
 const[dragging,setDragging]=useState(false)
 const openPicker=()=>{if(!busy&&input.current){input.current.value='';input.current.click()}}
 const selectFiles=(next:File[])=>{if(busy||!next.length)return;setFiles(next);setPreviews([])}
 useEffect(()=>{let alive=true;setLoading(true);setHistoryError('');api('/imports?page='+historyPage+(historyPage>0&&historyStamp.current.revision===revision?'&list_version='+historyStamp.current.version:'')).then(v=>{if(alive){if(historyPage>0&&historyPage*20>=v.total){setHistoryPage(Math.max(0,Math.ceil(v.total/20)-1));return}historyStamp.current={version:v.list_version,revision};setHistory(v.items);setHistoryTotal(v.total)}}).catch(e=>{if(alive){notify(e.message,true);if(e.message==='This list changed. Start from the first page.'){setHistoryPage(0);setRetry(v=>v+1)}else setHistoryError(e.message)}}).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[revision,historyPage,retry])
 const preview=()=>run(async()=>{const body=new FormData();body.set('account_id',account);files.forEach(f=>body.append('files',f));const v=await api('/imports/preview?paged=1','POST',body);setPreviews(v);refresh()},'Preview ready. Inspect the files and duplicate candidates before importing.')
 const fetchLive=()=>run(async()=>{const v=await api('/fnb/transactions?paged=1','POST');setPreviews(v);refresh();notify('FNB previews ready for '+v.length+' accounts. Inspect duplicates, then confirm the import.')})
 const resume=async(h:Row)=>{await run(async()=>{const preview=await api('/imports/'+h.id+'?page=0&page_size=50');setAccount(String(h.account_id));setPreviews([preview])})}
 return <>
  {data.user.admin&&<section className="panel"><div className="section-head"><div><h2>Live FNB transactions</h2><p className="muted">Fetch recent posted transactions for your visible, connected accounts. Set up the connection in Settings → Banking.</p></div></div><Button variant="primary" loading={busy} disabled={busy} onClick={fetchLive}>{busy?'Working':'Fetch FNB transactions'}</Button><p className="footnote">Fetching creates a preview. Confirm imports here, then review the transactions. FNB may require login approval. Only the first page is supported; older history may be missing.</p></section>}
  <section className="panel upload-panel"><div className="section-head"><div><h2>Upload FNB exports</h2><p className="muted">Choose an account, then select CSV, OFX, or ZIP files.</p></div><Upload size={22}/></div>
   {editors.length?<><PagedSelect url="/accounts?role=editor" label="Import into account" hint="The bank account number in each file must match." value={account} options={editors} onChange={value=>{setAccount(value);setPreviews([])}} revision={revision}/>
   <input ref={input} type="file" hidden aria-label="FNB export files" accept=".csv,.ofx,.zip" multiple disabled={busy} onChange={e=>selectFiles(Array.from(e.target.files||[]))}/><button type="button" className={'file-picker'+(dragging?' dragging':'')} disabled={busy} aria-label="Choose FNB export files" onClick={openPicker} onKeyDown={e=>{if(e.key===' '){e.preventDefault();openPicker()}}} onDragEnter={e=>{e.preventDefault();if(!busy&&e.dataTransfer.types.includes('Files')){dragDepth.current++;setDragging(true)}}} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect=busy?'none':'copy'}} onDragLeave={e=>{e.preventDefault();dragDepth.current=Math.max(0,dragDepth.current-1);if(!dragDepth.current)setDragging(false)}} onDrop={e=>{e.preventDefault();dragDepth.current=0;setDragging(false);selectFiles(Array.from(e.dataTransfer.files))}}><FileText size={24} aria-hidden="true"/><span aria-live="polite">{files.length?files.map(f=>f.name).join(', '):'Click to select files or drag and drop'}</span><small>{files.length?'Click to change files · ':''}CSV, OFX or ZIP · Up to 20 files · 25 MiB total · OFX recommended for transaction IDs</small></button><Button variant="primary" loading={busy} disabled={busy||!files.length||!account} onClick={preview}>{busy?'Reading exports':'Preview import'}</Button></>:<Empty title="Add an account first">You need editor access to an account before uploading.</Empty>}
  </section>
  {previews.map(p=><ImportPreview key={p.id} preview={p} categories={data.categories} groups={data.spendingGroups} notify={notify} refresh={refresh} onDone={()=>{setPreviews(v=>v.filter(item=>item.id!==p.id));setFiles([]);if(input.current)input.current.value=''}}/>)}
  <section className="panel"><div className="section-head"><h2>Import history</h2></div>{loading&&<Loading>Loading import history</Loading>}{historyError&&<p role="alert">{historyError} <Button onClick={()=>setRetry(v=>v+1)}>Retry</Button></p>}{!loading&&!historyError&&!history.length?<Empty title="No imports yet">Your import results and rejected rows will remain here.</Empty>:history.map(h=><details className="details" key={h.id}><summary><span>{h.name}</span><Badge tone={h.status==='committed'?'good':'pending'}>{h.status==='committed'?'Imported':'Staged'}</Badge></summary><div className="history-row"><span>{h.created_at} UTC · {data.accounts.find(a=>a.id===h.account_id)?.name}</span><span>{h.row_count} rows · {h.error_count} rejected{h.status==='committed'?' · '+h.inserted+' imported · '+h.skipped+' skipped':''}</span>{h.error&&<p className="error-text">{h.error}</p>}{h.status==='staged'?<Button onClick={()=>resume(h)} loading={busy}>Inspect current preview</Button>:<RetainedRows id={h.id}/>}</div></details>)}<Pagination page={historyPage} total={historyTotal} loading={loading} onChange={setHistoryPage}/></section>

 </>
}
function ImportPreview({preview:initial,categories,groups,notify,refresh,onDone}:{preview:Row;categories:Row[];groups:Row[];notify:PageProps['notify'];refresh:()=>void;onDone:()=>void}){
 const[p,setPreview]=useState(initial),[loading,setLoading]=useState(false),[pageError,setPageError]=useState(''),[skipAll,setSkipAll]=useState(false),[stale,setStale]=useState(false)
 const[decisions,setDecisions]=useState<Record<string,string>>({}),[confirm,setConfirm]=useState(false),[page,setPage]=useState(0)
 const{busy,run}=useTask(notify)
 const loadPage=async(next:number)=>{setLoading(true);setPageError('');try{const result=await api('/imports/'+p.id+'?page='+next+'&page_size=50');if(result.preview_version!==p.preview_version||result.classification_version!==p.classification_version){setDecisions({});setSkipAll(false);setConfirm(false);notify('Rules or duplicate candidates changed. Review this preview again.',true)}setPreview(result);setPage(next);setStale(false)}catch(e){setPageError((e as Error).message)}finally{setLoading(false)}}
 const bad=p.error_count
 const unresolved=!skipAll&&Object.values(decisions).filter(v=>v==='keep'||v==='skip').length<p.candidate_count
 const commit=async()=>{if(await run(async()=>{const v=await api('/imports/'+p.id+'/commit','POST',{confirm_valid_rows:confirm,decisions,skip_all_candidates:skipAll,classification_version:p.classification_version,...(p.preview_version?{preview_version:p.preview_version}:{})});notify(v.inserted+' transactions imported; '+v.skipped+' skipped. New entries await review.') },undefined,message=>{if(message.includes('preview changed')||message.includes('Classification rules changed'))setStale(true);return false})){refresh();onDone()}}
 return <section className="panel preview"><div className="section-head"><div><h2>{p.name}</h2><p className="muted">{p.format.toUpperCase()} · {p.currency} · account ending {String(p.bank_id).slice(-4)} · {p.total} rows</p></div><Badge tone="pending">Preview</Badge></div>
 {p.coverage&&<p className="footnote">Returned coverage: {p.coverage.returned_start&&p.coverage.returned_end?`${p.coverage.returned_start} to ${p.coverage.returned_end}`:'No posted rows returned'} · {p.coverage.returned_rows} bank rows{p.coverage.service_fee_rows?` · ${p.coverage.service_fee_rows} additional service-fee entries`:''}. History may be incomplete.{p.coverage.pending_rows?` ${p.coverage.pending_rows} pending authorizations excluded.`:''}{p.coverage.page_limit_reached?' The 150-row page limit was reached.':''}</p>}
 {p.error&&<div className="notice error" role="alert">{p.error}</div>}{p.already_imported&&<div className="notice">This exact import has already been committed. It will not create new transactions.</div>}
 {!!p.balance_date&&<p className="footnote">Bank-reported balance: {money(p.balance_cents)} as of {p.balance_date}.</p>}
 {p.candidate_count>0&&<div className="notice"><span>Inspect matching records. Identical-looking purchases can be legitimate.</span><Button disabled={loading} onClick={()=>{setSkipAll(true);setDecisions({})}}>Skip all {p.candidate_count} candidates in this import</Button></div>}
 <div className="preview-rows" aria-busy={loading}>{p.rows.map((r:Row)=><div className="preview-row" key={r.row}><div className="line"><strong>{r.description||'Invalid row'}</strong><strong>{money(r.amount_cents)}</strong></div><small>Row {r.row} · {r.date||'Invalid date'}</small>{r.source_component==='service_fee'&&<p className="footnote">Bank row {r.source_bank_row} service fee · {r.source_bank_description}</p>}{r.error?<p className="error-text">{r.error}</p>:<><div className="row-meta"><span>{categories.find(c=>c.id===r.category_id)?.name||'Uncategorized'}</span>{r.spending_group_id&&<span>{groups.find(g=>g.id===r.spending_group_id)?.name}</span>}{r.suggestion&&<small>{r.suggestion}</small>}{r.rule_conflict&&<Badge tone="pending">Rule conflict — needs classification</Badge>}{(r.rule_match_count||r.rule_matches?.length)>1&&<RuleSuggestions id={p.id} row={r.row} version={p.preview_version} onStale={()=>setStale(true)}/>}{r.duplicate&&<Badge tone={r.duplicate==='conflict'?'bad':'pending'}>{r.duplicate==='exact_id'?'Existing transaction ID — skip':r.duplicate==='conflict'?'Conflicting transaction ID':'Possible duplicate'}</Badge>}</div>{r.candidates?.length>0&&<details><summary>Compare matching records</summary>{r.candidates.map((c:Row,i:number)=><div className="candidate" key={i}><small>{c.id?'Existing transaction #'+c.id:c.file?'Batch file '+c.file:'Earlier row '+c.row}</small><div>{c.date} · {c.description} · {money(c.amount_cents)}</div></div>)}</details>}{['possible','conflict'].includes(r.duplicate)&&<Field label={'Decision for row '+r.row}><select value={decisions[r.row]||(skipAll?'skip':'')} onChange={e=>setDecisions({...decisions,[r.row]:e.target.value})}><option value="">Choose a decision</option><option value="skip">Skip this row</option>{r.duplicate==='possible'&&<option value="keep">Keep as a separate transaction</option>}</select></Field>}</>}</div>)}</div>
 {stale&&<Button disabled={loading} onClick={()=>loadPage(page)}>Reload preview</Button>}
 {loading&&<Loading>Loading import rows</Loading>}{pageError&&<p role="alert">{pageError} <Button onClick={()=>loadPage(page)}>Retry</Button></p>}
 <Pagination page={page} total={p.total} size={50} loading={loading||busy} onChange={loadPage}/>
 {!!bad&&<label className="check"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>Import valid rows and retain {bad} rejected rows in history</label>}
 <div className="editor-actions"><Button variant="primary" loading={busy} disabled={busy||stale||loading||!!pageError||!p.total||!!p.error||p.already_imported||unresolved||(!!bad&&!confirm)} onClick={commit}>{busy?'Importing':'Confirm import'}</Button><span className="muted">All accepted transactions will need review.</span></div>
 </section>
}

function RetainedPage({id}:{id:number}){
 const[page,setPage]=useState(0),[data,setData]=useState<Row|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0)
 useEffect(()=>{let alive=true;setLoading(true);setError('');api('/imports/'+id+'?page='+page+'&page_size=50').then(v=>alive&&setData(v)).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[id,page,retry])
 return <>{loading&&<Loading>Loading retained rows</Loading>}{error&&<p role="alert">{error} <Button onClick={()=>setRetry(v=>v+1)}>Retry</Button></p>}{data?.rows.map((row:Row)=><div className="candidate" key={row.row}><small>Row {row.row} · {row.date}</small><div>{row.description} · {money(row.amount_cents)}</div><small>{row.error?'Rejected: '+row.error:data.decisions?.[row.row]==='skip'||row.duplicate==='exact_id'?'Skipped':'Imported'}</small></div>)}<Pagination page={page} total={data?.total||0} size={50} loading={loading} onChange={setPage}/></>
}

function RetainedRows({id}:{id:number}){const[open,setOpen]=useState(false);return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary>Inspect retained rows and decisions</summary>{open&&<RetainedPage id={id}/>}</details>}

function RuleSuggestions({id,row,version,onStale}:{id:number;row:number;version?:string;onStale:()=>void}){const[open,setOpen]=useState(false);return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary>Compare rule suggestions</summary>{open&&<SuggestionPage url={'/imports/'+id+'/rows/'+row+'/suggestions'+(version?'?preview_version='+version:'')} onStale={onStale}/>}</details>}
function SuggestionPage({url,onStale}:{url:string;onStale:()=>void}){const list=usePagedList(url);useEffect(()=>{if(list.error.includes('Import preview changed'))onStale()},[list.error]);return <><ListStatus list={list}/>{list.items.map(m=><div className="candidate" key={m.id}>{m.pattern} → {m.category_name}{m.spending_group_name?' · '+m.spending_group_name:''}</div>)}<ListNavigation list={list}/></>}
