import {LimitEditor} from './LimitEditor'
import {usePagedList,ListStatus,ListNavigation,PagedSelect} from './PagedList'
import {useAccountManagement,AccountActions,HiddenAccounts} from './AccountManagement'
import {Rules} from './Rules'
import {NetworkSettings} from './NetworkSettings'
import {FNBConnection} from './FNBConnection'
import {GroupDot} from './Choices'
import {AccountDiscovery} from './AccountDiscovery'
import {useEffect,useState} from 'react'
import {Plus,Pencil,Wallet} from 'lucide-react'
import {api,money} from './api'
import {Button,Field,Form,Badge,Empty,Modal,validateFields,Tabs,Loading,Pagination} from './ui'
import {passwordError,usernameError} from './validation'
import {useTask,type PageProps,type Row} from './App'
export function Accounts(props:PageProps&{onManage:()=>void}){
 const{data,onManage}=props,m=useAccountManagement(props),list=usePagedList('/accounts',props.revision)
 return <><div className="toolbar"><p className="muted">Only household accounts contribute to the shared budget.</p>{data.user.admin&&<div className="toolbar-actions"><Button loading={m.refreshing()} disabled={!m.canRefresh||m.busy} onClick={()=>m.refreshBank()}>Refresh accounts</Button><Button onClick={onManage}>Manage accounts</Button></div>}</div>
 {m.loading&&data.user.admin&&<Loading>Loading account controls</Loading>}
 <ListStatus list={list}/><div className="account-grid">{list.items.map(a=><section className="panel account-card" key={a.id} aria-busy={!!m.refreshing(a.id,!!a.fnb_connected)}><div className="section-head"><Wallet size={21}/><Badge>{a.household?'Household':'Private'}</Badge></div><h2>{a.name}</h2><p className="muted">FNB · ending {a.bank_id.slice(-4)}</p><strong className="account-balance">{a.balance_cents===null?'No imported balance':money(a.balance_cents)}</strong><small>{a.balance_date?'Bank-reported as of '+a.balance_date:'Refresh your bank connection or upload an export to record a balance'}</small><div className="account-foot"><span>{m.refreshing(a.id,!!a.fnb_connected)?<Loading>Updating account</Loading>:a.role==='editor'?'Can import, edit, and review':'View only'}</span>{data.user.admin&&<AccountActions account={m.accounts.find(x=>x.id===a.id)||a} management={m}/>}</div></section>)}</div>
 <ListNavigation list={list}/>{!list.loading&&!list.items.length&&<Empty title="No accessible accounts">An administrator can add an account in Settings or grant you access.</Empty>}
 {data.user.admin&&<HiddenAccounts management={m}/>} {m.editor}
 </>
}
function AccountSettings(props:PageProps&{accounts:Row[]}){
 const{data,revision,refresh,notify}=props,m=useAccountManagement(props)
 return <><section className="panel account-settings"><div className="section-head"><div><h2>Account setup</h2><p className="muted">Manage names, sharing and visibility. Hidden history remains stored.</p></div><div className="toolbar-actions"><AccountDiscovery data={data} refresh={refresh} notify={notify} revision={revision}/><Button variant="primary" onClick={()=>m.edit({name:'',bank_id:'',household:true})}><Plus size={17}/>Add account</Button></div></div>
 <ListStatus list={m.shown}/>
 {m.accounts.filter(a=>!a.sync_hidden).map(a=><div className="line" key={a.id}><div><strong>{a.name}</strong><small>FNB · ending {a.bank_id.slice(-4)} · {a.household?'Household':'Private'} · Shown</small>{m.refreshing(a.id,!!a.fnb_connected)&&<Loading>Updating account</Loading>}</div><AccountActions account={a} management={m}/></div>)}
 <ListNavigation list={m.shown}/>{!m.shown.loading&&!m.accounts.length&&<Empty title="No accounts yet">Add an account or discover accounts through Banking.</Empty>}</section><HiddenAccounts management={m}/>{m.editor}</>
}
export function Categories({data,refresh,notify,revision}:PageProps){
 const[spendingEdit,setSpendingEdit]=useState<Row|null>(null),[spendingName,setSpendingName]=useState(''),[spendingColor,setSpendingColor]=useState('blue'),[spendingError,setSpendingError]=useState('')
 const[creating,setCreating]=useState(false),[name,setName]=useState(''),[kind,setKind]=useState('expense')
 const[categoryTab,setCategoryTab]=useState('rules')
 const categoryList=usePagedList('/categories',revision),groupList=usePagedList('/spending-groups',revision)
 const[nameError,setNameError]=useState('')
 useEffect(()=>setNameError(''),[creating])
 const{busy,run}=useTask(notify)
 return <>
 <Tabs id="classification" label="Categories and rules" items={[{id:'rules',label:'Rules'},{id:'categories',label:'Categories'},{id:'groups',label:'Spending groups'}]} value={categoryTab} onChange={setCategoryTab}/>
 <div role="tabpanel" id={'classification-panel-'+categoryTab} aria-labelledby={'classification-tab-'+categoryTab}>
 {categoryTab==='rules'&&<Rules data={data} refresh={refresh} notify={notify} revision={revision}/>}

 {categoryTab==='groups'&&<section className="panel"><div className="section-head"><div><h2>Spending groups</h2><p className="muted">A separate label for each transaction, independent of its categories.</p></div>{data.user.budget_member&&<Button onClick={()=>{setSpendingEdit({});setSpendingName('');setSpendingColor('blue');setSpendingError('')}}><Plus size={16}/>Add spending group</Button>}</div>
 <ListStatus list={groupList}/><div className="spending-group-grid">{groupList.items.map(g=><button type="button" className="choice-row" disabled={!data.user.budget_member} key={g.id} onClick={()=>{setSpendingEdit(g);setSpendingName(g.name);setSpendingColor(g.color);setSpendingError('')}}><GroupDot color={g.color}/><span>{g.name}</span>{data.user.budget_member&&<span className="muted">Edit</span>}</button>)}</div><ListNavigation list={groupList}/></section>}
 {categoryTab==='categories'&&<section className="panel"><div className="section-head"><div><h2>Categories</h2><p className="muted">Limits are set on expense categories in Budgets.</p></div>{data.user.budget_member&&<Button onClick={()=>setCreating(true)}><Plus size={16}/>Add category</Button>}</div>
 <ListStatus list={categoryList}/>{!categoryList.loading&&!categoryList.items.length?<Empty title="Create your first categories">Create categories for the income and expenses you track.</Empty>:categoryList.items.map(c=><div className="line" key={c.id}><span>{c.name}</span><Badge>{c.kind==='expense'?'Expense':'Income'}</Badge></div>)}<ListNavigation list={categoryList}/></section>}
 </div>
 {spendingEdit&&<Modal title={spendingEdit.id?'Edit spending group':'Add spending group'} onClose={()=>setSpendingEdit(null)}><Form onSubmit={async()=>{if(await run(()=>api('/spending-groups'+(spendingEdit.id?'/'+spendingEdit.id:''),spendingEdit.id?'PUT':'POST',{name:spendingName,color:spendingColor,version:spendingEdit.version}),'Spending group saved',message=>{if(message==='Spending group already exists'){setSpendingError(message);return true}return false})){setSpendingEdit(null);refresh()}}}><Field label="Name" serverError={spendingError}><input autoFocus required minLength={2} maxLength={80} value={spendingName} onChange={e=>{setSpendingName(e.target.value);setSpendingError('')}}/></Field><Field label="Color"><select value={spendingColor} onChange={e=>setSpendingColor(e.target.value)}>{['blue','amber','purple','orange','teal','slate','rose'].map(color=><option value={color} key={color}>{color[0].toUpperCase()+color.slice(1)}</option>)}</select></Field><p className="muted">Spending groups are labels. Categories determine budget totals; transfers are designated separately.</p><Button type="submit" variant="primary" loading={busy} disabled={busy}>Save spending group</Button></Form></Modal>}
 {creating&&<Modal title="Add category" onClose={()=>setCreating(false)}><Form onSubmit={async e=>{e.preventDefault();if(await run(()=>api('/categories','POST',{name,kind}),'Category created',message=>{if(message==='Category already exists'){setNameError(message);return true}return false})){setCreating(false);setName('');refresh()}}}><Field label="Category name" serverError={nameError}><input required maxLength={80} value={name} onChange={e=>{setName(e.target.value);setNameError('')}}/></Field><Field label="Type"><select value={kind} onChange={e=>setKind(e.target.value)}><option value="expense">Expense (refunds reduce spending)</option><option value="income">Income</option></select></Field><Button type="submit" variant="primary" loading={busy} disabled={busy}>Create category</Button></Form></Modal>}

 </>
}
export function Budgets({data,refresh,notify,revision}:PageProps){
 const[editing,setEditing]=useState<Row|null>(null),[preview,setPreview]=useState<Row|null>(null),[limits,setLimits]=useState<Row|null>(null)
 const{busy,run}=useTask(notify)
 const periods=usePagedList('/periods',revision)
 const[previewPage,setPreviewPage]=useState(0)
 const startEdit=(p:Row)=>{setEditing({...p});setPreview(null);setPreviewPage(0)}
 const update=(key:string,value:string)=>{setEditing(v=>v?{...v,[key]:value}:null);setPreview(null);setPreviewPage(0)}
 const payload=()=>({name:editing!.name,start_date:editing!.start_date,end_date:editing!.end_date,version:editing!.version||0,preview_token:preview?.preview_token||''})
 return <>
 <div className="toolbar"><p className="muted">Limits reset each period. New periods copy your previous limits.</p><Button variant="primary" onClick={()=>startEdit({...data.next,version:0})}><Plus size={17}/>New period</Button></div>
 <ListStatus list={periods}/>{!periods.loading&&!periods.items.length?<Empty title="No budget periods">Create your first period to start budgeting.</Empty>:periods.items.map(p=><section className="panel" key={p.id}><div className="section-head"><div><h2>{p.name}</h2><p className="muted">{p.start_date} — {p.end_date}</p></div><div className="toolbar-actions"><Button onClick={()=>startEdit(p)}>Edit dates</Button><Button onClick={()=>{setLimits(p)}}>Edit limits</Button></div></div>
 <div className="budget-total"><span>Category limits</span><strong>{money(p.target_total)}</strong></div>
 {p.targets.filter((t:Row)=>t.amount_cents>0).map((t:Row)=><div className="line" key={t.category_id}><span>{t.name||'Category'}</span><strong>{money(t.amount_cents)}</strong></div>)}{!p.target_total&&<p className="footnote">No spending limits set yet.</p>}{p.targets.length===20&&<p className="footnote">Use Edit limits to browse all categories.</p>}</section>)}<ListNavigation list={periods}/>
 {editing&&<Modal title={editing.id?'Edit budget period':'New budget period'} onClose={()=>setEditing(null)}><Field label="Period name"><input required maxLength={100} value={editing.name||''} onChange={e=>update('name',e.target.value)}/></Field><div className="form-grid"><Field label="Start date"><input type="date" required value={editing.start_date||''} onChange={e=>update('start_date',e.target.value)}/></Field><Field label="End date (inclusive)" validate={value=>editing.start_date&&value<editing.start_date?'End date must be on or after the start date.':''}><input type="date" required value={editing.end_date||''} onChange={e=>update('end_date',e.target.value)}/></Field></div><p className="muted">Dates are independent. Overlapping transactions use the latest-starting period; gaps need explicit assignment. Manual assignments are preserved.</p>
 <Button loading={busy} disabled={busy} onClick={e=>{if(validateFields(e.currentTarget.closest('.modal-body')!))run(async()=>{setPreview(await api('/periods/'+(editing.id||'new')+'/preview?page=0&page_size=50','POST',payload()));setPreviewPage(0)})}}>Preview assignment changes</Button>
 {preview&&<div className="notice"><div><strong>{preview.total} automatic assignments will change.</strong><p>{preview.manual_outside} manual assignments will be outside their period dates.</p><details><summary>Inspect affected transactions</summary>{preview.affected.map((t:Row)=><p key={t.id}>#{t.id} · {t.date} · {t.from?data.periods.find(p=>p.id===t.from)?.name||t.from:'Unassigned'} → {t.to?data.periods.find(p=>p.id===t.to)?.name||'New period':'Unassigned'}</p>)}<Pagination page={previewPage} total={preview.total} size={50} loading={busy} onChange={page=>run(async()=>{const next=await api('/periods/'+(editing.id||'new')+'/preview?page='+page+'&page_size=50','POST',payload());setPreview(next);setPreviewPage(page)})}/></details></div></div>}
 <div className="editor-actions"><Button variant="primary" loading={busy} disabled={busy||!preview} onClick={async()=>{if(await run(()=>api('/periods'+(editing.id?'/'+editing.id:''),editing.id?'PUT':'POST',payload()),'Budget period saved')){setEditing(null);refresh()}}}>Save period</Button><Button onClick={()=>setEditing(null)}>Cancel</Button></div></Modal>}
 {limits&&<Modal title={'Category limits · '+limits.name} onClose={()=>setLimits(null)}><LimitEditor period={limits} notify={notify} refresh={refresh} revision={revision} onDone={()=>setLimits(null)}/></Modal>}

 </>
}
export function SettingsPage({data,revision,refresh,notify,theme,onTheme,section,onSectionChange}:PageProps&{theme:string;onTheme:(v:string)=>void;section:string;onSectionChange:(v:string)=>void}){
 const[workspaceName,setWorkspaceName]=useState(data.branding.display_name),[brandingVersion,setBrandingVersion]=useState(data.branding.version),[brandingError,setBrandingError]=useState('')
 const[settingsLoading,setSettingsLoading]=useState(true)
 const[startDay,setStartDay]=useState('20'),[users,setUsers]=useState<Row[]>([]),[backups,setBackups]=useState<Row>({items:[]}),[manageAccounts,setManageAccounts]=useState<Row[]>([])
 const userList=usePagedList(data.user.admin?'/users':'',revision),grantList=usePagedList(data.user.admin?'/grants':'',revision)
 const[editUser,setEditUser]=useState<Row|null>(null);const[addUser,setAddUser]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[member,setMember]=useState(true),[admin,setAdmin]=useState(false)
 const[grantUser,setGrantUser]=useState(''),[grantAccount,setGrantAccount]=useState(''),[role,setRole]=useState('viewer')
 const[oldPassword,setOldPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[oldPasswordError,setOldPasswordError]=useState(''),[userNameError,setUserNameError]=useState('')
 useEffect(()=>setUserNameError(''),[addUser,editUser?.id])
 const{busy,run}=useTask(notify)
 useEffect(()=>{let alive=true;setSettingsLoading(true);Promise.all([data.user.budget_member?api('/settings'):Promise.resolve({start_day:20}),data.user.admin?api('/users?page=0&page_size=100'):Promise.resolve([]),data.user.admin?Promise.resolve({items:[]}):Promise.resolve([]),data.user.admin?api('/backups'):Promise.resolve({items:[]}),data.user.admin?api('/accounts/manage?page=0&page_size=100'):Promise.resolve([])]).then(([s,u,_g,b,a])=>{if(alive){setStartDay(String(s.start_day));setUsers(u.items||[]);setBackups(b);setManageAccounts(a.items||[])}}).catch(e=>alive&&notify(e.message,true)).finally(()=>alive&&setSettingsLoading(false));return()=>{alive=false}},[revision])
 const tabs=[{id:'general',label:'General'},...(data.user.admin?[{id:'banking',label:'Banking'},{id:'accounts',label:'Accounts'},{id:'access',label:'Users & access'},{id:'backups',label:'Backups'},{id:'network',label:'Network'}]:[]),{id:'security',label:'Security'}]
 const active=tabs.some(tab=>tab.id===section)?section:'general'
 const panel=(id:string)=>({id:'settings-panel-'+id,role:'tabpanel','aria-labelledby':'settings-tab-'+id,hidden:active!==id,className:'settings-panel'})
 return <>
 {settingsLoading&&<Loading>Loading settings</Loading>}
 <Tabs id="settings" label="Settings sections" items={tabs} value={active} onChange={onSectionChange}/>
 <div {...panel('general')}>
 {data.user.admin&&<section className="panel"><h2>Workspace name</h2><Form onSubmit={async()=>{if(await run(async()=>{const result=await api('/branding','PUT',{display_name:workspaceName,version:brandingVersion});setWorkspaceName(result.display_name);setBrandingVersion(result.version)},'Workspace name saved',message=>{if(message.startsWith('Use a workspace name')){setBrandingError(message);return true}return false}))refresh()}}><Field label="Display name" hint="Shown to signed-in users. The sign-in screen keeps a generic name." serverError={brandingError} validate={value=>Array.from(value.trim()).length<2||Array.from(value.trim()).length>60?'Use a workspace name of 2–60 characters':''}><input required value={workspaceName} onChange={e=>{setWorkspaceName(e.target.value);setBrandingError('')}}/></Field><div className="editor-actions"><Button type="submit" variant="primary" loading={busy} disabled={busy}>Save workspace name</Button><Button loading={busy} disabled={busy} onClick={async()=>{if(await run(async()=>{const b=await api('/branding');setWorkspaceName(b.display_name);setBrandingVersion(b.version);setBrandingError('')}))refresh()}}>Reload saved name</Button></div></Form></section>}
 <section className="panel"><h2>Preferences</h2><Field label="Appearance"><select value={theme} onChange={e=>onTheme(e.target.value)}><option value="system">Follow device</option><option value="light">Light</option><option value="dark">Dark</option></select></Field><div className="line"><span>Currency</span><strong>South African rand (ZAR)</strong></div><div className="line"><span>Budget timezone</span><strong>Africa/Johannesburg</strong></div>{data.user.budget_member&&<Form onSubmit={async e=>{e.preventDefault();if(await run(()=>api('/settings','PUT',{start_day:Number(startDay)}),'Default updated; existing periods are unchanged'))refresh()}}><Field label="Default period start day" hint="Used for new periods. Days beyond a month’s length use its last day."><input type="number" min={1} max={31} required value={startDay} onChange={e=>setStartDay(e.target.value)}/></Field><Button type="submit" loading={busy} disabled={busy}>Save default</Button></Form>}</section>
 </div>
 <div {...panel('security')}>
 <section className="panel"><h2>Change your password</h2><Form onSubmit={async e=>{e.preventDefault();if(await run(()=>api('/password','POST',{old_password:oldPassword,new_password:newPassword}),'Password changed; other sessions signed out',message=>{if(message==='Current password is incorrect'){setOldPasswordError(message);return true}return false})){setOldPassword('');setNewPassword('')}}}><Field label="Current password" serverError={oldPasswordError}><input type="password" autoComplete="current-password" required value={oldPassword} onChange={e=>{setOldPassword(e.target.value);setOldPasswordError('')}}/></Field><Field label="New password" validate={passwordError}><input type="password" autoComplete="new-password" required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></Field><Button type="submit" loading={busy} disabled={busy}>Change password</Button></Form></section>
 </div>
 {data.user.admin&&<>
 <div {...panel('banking')}>{active==='banking'&&<FNBConnection data={data} revision={revision} refresh={refresh} notify={notify}/>}</div>
 <div {...panel('network')}>{active==='network'&&<NetworkSettings data={data} revision={revision} refresh={refresh} notify={notify}/>}</div>
 <div {...panel('accounts')}>{active==='accounts'&&<AccountSettings data={data} revision={revision} refresh={refresh} notify={notify} accounts={manageAccounts}/>}</div>
 <div {...panel('access')}>
 <section className="panel"><div className="section-head"><h2>Users</h2><Button onClick={()=>setAddUser(true)}><Plus size={16}/>Add user</Button></div><ListStatus list={userList}/>{userList.items.map(u=><div className="line user-row" key={u.id}><strong>{u.username}</strong><div className="row-meta">{u.admin===1&&<Badge>Administrator</Badge>}{u.budget_member===1&&<Badge>Household member</Badge>}{u.disabled===1&&<Badge tone="bad">Disabled</Badge>}<Button variant="quiet" aria-label={'Edit user '+u.username} onClick={()=>setEditUser({...u})}><Pencil size={16}/></Button></div></div>)}<ListNavigation list={userList}/><p className="footnote">Household members can edit shared accounts and budgets. Recover a password using the offline administrator command.</p></section>
 <section className="panel"><h2>Account access</h2><p className="muted">Household members automatically have editor access to household accounts. These grants control private accounts and other users.</p><Form onSubmit={async e=>{e.preventDefault();if(await run(()=>api('/grants','PUT',{user_id:Number(grantUser),account_id:Number(grantAccount),role}),'Account access updated'))refresh()}}><div className="form-grid"><PagedSelect url="/users" label="User" nameKey="username" required value={grantUser} options={users} onChange={setGrantUser} revision={revision}/><PagedSelect url="/accounts/manage" label="Account" optionLabel={a=>a.name+(a.household?' · Household':' · Private')} required value={grantAccount} options={manageAccounts} onChange={setGrantAccount} revision={revision}/></div><Field label="Permission"><select value={role} onChange={e=>setRole(e.target.value)}><option value="viewer">Viewer</option><option value="editor">Editor (includes approval)</option><option value="">Revoke explicit access</option></select></Field><Button loading={busy} disabled={busy} type="submit">Update access</Button></Form><ListStatus list={grantList}/>{grantList.items.map(g=><div className="line" key={g.user_id+'-'+g.account_id}><span>{g.username} · {g.account_name}</span><Badge>{g.role}</Badge></div>)}<ListNavigation list={grantList}/></section>
 </div>
 <div {...panel('backups')}>
 <section className="panel"><div className="section-head"><h2>Backups</h2><Button loading={busy} disabled={busy} onClick={async()=>{if(await run(()=>api('/backups','POST'),'Backup completed and integrity checked'))refresh()}}>Back up now</Button></div><p className="muted">A consistent snapshot every 24 hours. Keep the latest 14 successful snapshots.</p>{backups.error&&<p role="alert" className="error-text">{backups.error}</p>}{backups.items.length?<p>Last successful backup: <strong>{backups.items[0].created_at} UTC</strong></p>:<p>No successful backup recorded yet.</p>}<p className="footnote">Restore with the service stopped, using the documented command. A restore preserves the previous database and signs out old sessions. Store backup copies on a separate device.</p></section>
 </div>
 </>}
 {editUser&&<Modal title="Edit user" onClose={()=>setEditUser(null)}><Form onSubmit={async e=>{e.preventDefault();if(await run(()=>api('/users/'+editUser.id,'PUT',{username:editUser.username,admin:!!editUser.admin,budget_member:!!editUser.budget_member,disabled:!!editUser.disabled,version:editUser.version}),'User updated',message=>{if(message==='Username already exists'){setUserNameError(message);return true}return false})){setEditUser(null);refresh()}}}><Field label="Username" validate={usernameError} serverError={userNameError}><input required minLength={2} maxLength={80} value={editUser.username} onChange={e=>{setEditUser({...editUser,username:e.target.value});setUserNameError('')}}/></Field><label className="check"><input type="checkbox" checked={!!editUser.budget_member} onChange={e=>setEditUser({...editUser,budget_member:e.target.checked})}/>Household budget member</label><label className="check"><input type="checkbox" checked={!!editUser.admin} onChange={e=>setEditUser({...editUser,admin:e.target.checked})}/>Administrator</label><label className="check"><input type="checkbox" checked={!!editUser.disabled} onChange={e=>setEditUser({...editUser,disabled:e.target.checked})}/>Disable login and revoke sessions</label><Button variant="primary" type="submit" loading={busy} disabled={busy}>Save user</Button></Form></Modal>}
 {addUser&&<Modal title="Add user" onClose={()=>setAddUser(false)}><Form onSubmit={async e=>{e.preventDefault();if(await run(()=>api('/users','POST',{username,password,admin,budget_member:member}),'User created',message=>{if(message==='Username already exists'){setUserNameError(message);return true}return false})){setAddUser(false);setUsername('');setPassword('');refresh()}}}><Field label="Username" validate={usernameError} serverError={userNameError}><input required minLength={2} maxLength={80} value={username} onChange={e=>{setUsername(e.target.value);setUserNameError('')}}/></Field><Field label="Initial password" validate={passwordError}><input type="password" autoComplete="new-password" required value={password} onChange={e=>setPassword(e.target.value)}/></Field><label className="check"><input type="checkbox" checked={member} onChange={e=>setMember(e.target.checked)}/>Household budget member</label><label className="check"><input type="checkbox" checked={admin} onChange={e=>setAdmin(e.target.checked)}/>Administrator</label><Button variant="primary" loading={busy} disabled={busy} type="submit">Create user</Button></Form></Modal>}
 </>
}
