import {SpendingGroupEditor} from './SpendingGroupEditor'
import {AccountHealth,BudgetTrends,Rebalance} from './CoreWorkflows'
import {CategoryEditor,MerchantRules} from './Organisation'
import {useTransactionAccess} from './TransactionAccess'
import {MCPSettings} from './MCPSettings'
import {LimitEditor} from './LimitEditor'
import {usePagedList,ListStatus,ListNavigation,PagedSelect} from './PagedList'
import {useAccountManagement,AccountActions,HiddenAccounts} from './AccountManagement'
import {Rules} from './Rules'
import {NetworkSettings} from './NetworkSettings'
import {FNBConnection} from './FNBConnection'
import {GroupDot,ChoiceField} from './Choices'
import {AccountDiscovery} from './AccountDiscovery'
import {useEffect,useState} from 'react'
import {Plus,Pencil,ChevronRight} from 'lucide-react'
import {AccountIcon} from './AccountIcon'
import {api,money} from './api'
import {Button,Field,Form,Badge,Empty,Modal,validateFields,Tabs,Loading,Pagination,ActionMenu} from './ui'
import {passwordError,usernameError} from './validation'
import {useTask,type PageProps,type Row} from './App'
export function Accounts(props:PageProps&{onManage:()=>void;onTransactions:()=>void}){
 const {viewTransactions}=useTransactionAccess()
 const{data,onManage,onTransactions}=props,m=useAccountManagement(props),list=usePagedList('/accounts',props.revision)
 return <><div className="toolbar"><p className="muted">{list.total} {list.total===1?'account':'accounts'} · Household accounts contribute to the shared budget.</p>{data.user.admin&&<div className="toolbar-actions"><Button loading={m.refreshing()} disabled={!m.canRefresh||m.busy} onClick={()=>m.refreshBank()}>Refresh balances</Button><Button variant="primary" onClick={onTransactions}>Get transactions</Button><ActionMenu label="Account management"><Button variant="quiet" onClick={onManage}>Bank connection</Button><Button variant="quiet" onClick={()=>m.edit({name:'',bank_id:'',household:false})}><Plus size={17}/>Add account</Button></ActionMenu></div>}</div>
 {m.loading&&data.user.admin&&<Loading>Loading account controls</Loading>}
 <section className="panel account-list"><ListStatus list={list}/>{list.items.map(a=><div className="account-summary" key={a.id} aria-busy={!!m.refreshing(a.id,!!a.fnb_connected)}><div className="account-identity"><AccountIcon type={a.account_type}/><div><h2><button type="button" className="transaction-link" title={'View transactions for '+a.name} onClick={()=>viewTransactions({account:String(a.id)})}>{a.name}</button></h2><small>FNB · ••{a.bank_id.slice(-4)} · {a.household?'Household':'Private'} · {a.role==='editor'?'Editor':'View only'}</small></div></div><div className="account-value"><strong>{a.balance_cents===null?'Balance unavailable':money(a.balance_cents)}</strong><small>{m.refreshing(a.id,!!a.fnb_connected)?<Loading>Updating balance</Loading>:a.balance_date?'As of '+a.balance_date:'No bank balance recorded'}</small></div>{data.user.admin&&<AccountActions account={m.accounts.find(x=>x.id===a.id)||a} management={m}/>}</div>)}
 {!list.loading&&!list.error&&!list.items.length&&<Empty title="No accessible accounts">{data.user.admin?'Connect FNB to discover accounts, add one manually, or import a discovery file.':'Ask an administrator to grant account access.'}{data.user.admin&&<Button onClick={onManage}>Connect FNB</Button>}</Empty>}<ListNavigation list={list}/></section>
 <details className="panel secondary-section"><summary>Transaction import health</summary><AccountHealth revision={props.revision} notify={props.notify} onBanking={onManage} onImports={onTransactions}/></details>
 {data.user.admin&&<><details className="panel"><summary>Import an account discovery file</summary><p className="footnote">Use an account-only file from the owner-run discovery tool.</p><AccountDiscovery {...props}/></details><HiddenAccounts management={m}/></>} {m.editor}
 </>
}
export function Categories({data,refresh,notify,revision,onAccounts,tab:externalTab,onTabChange}:PageProps&{onAccounts:()=>void;tab?:string;onTabChange?:(tab:string)=>void}){
 const {viewTransactions}=useTransactionAccess()
 const[spendingEdit,setSpendingEdit]=useState<Row|null>(null)
 const[creating,setCreating]=useState(false),[name,setName]=useState(''),[kind,setKind]=useState('expense')
 const[categoryEdit,setCategoryEdit]=useState<Row|null>(null)
 const[internalTab,setInternalTab]=useState('categories')
 const categoryTab=externalTab||internalTab
 const changeTab=(t:string)=>{setInternalTab(t);onTabChange?.(t)}
 const categoryList=usePagedList('/categories',revision),groupList=usePagedList('/spending-groups',revision)
 const[nameError,setNameError]=useState('')
 useEffect(()=>{setNameError('')},[creating])
 const{busy,run}=useTask(notify)
 return <>
 <div className="classification-layout"><aside className="classification-nav"><Tabs id="classification" label="Categories and rules" items={[{id:'categories',label:'Categories'},{id:'groups',label:'Spending groups'},{id:'rules',label:'Automatic rules'},{id:'merchants',label:'Merchant rules'}]} value={categoryTab} onChange={changeTab}/></aside>
 <div role="tabpanel" id={'classification-panel-'+categoryTab} aria-labelledby={'classification-tab-'+categoryTab}>
 {categoryTab==='merchants'&&<MerchantRules data={data} refresh={refresh} notify={notify} revision={revision}/>}
 {categoryEdit&&<CategoryEditor category={categoryEdit} notify={notify} onClose={()=>setCategoryEdit(null)} onDone={()=>{setCategoryEdit(null);refresh()}}/>}
 {categoryTab==='rules'&&<Rules onAccounts={onAccounts} onCreateCategory={()=>setCreating(true)} data={data} refresh={refresh} notify={notify} revision={revision}/>}

 {categoryTab==='groups'&&<section className="panel"><div className="section-head"><div><h2>Spending groups</h2><p className="muted">Organize transactions with an extra label, such as Essentials or Leisure. This does not change their budget category.</p></div>{data.user.budget_member&&<Button onClick={()=>{setSpendingEdit({})}}><Plus size={16}/>Add spending group</Button>}</div>
 <ListStatus list={groupList}/><div className="spending-group-grid">{groupList.items.map(g=><div className="classification-group-entry" key={g.id}><button type="button" className="choice-row" title={'View transactions for '+g.name} onClick={()=>viewTransactions({group:String(g.id)})}><GroupDot color={g.color}/><span>{g.name}</span><ChevronRight size={16} aria-hidden="true"/></button>{data.user.budget_member&&<Button variant="quiet" aria-label={'Edit '+g.name} title={'Edit '+g.name} onClick={()=>{setSpendingEdit(g)}}><Pencil size={16} aria-hidden="true"/></Button>}</div>)}</div><ListNavigation list={groupList}/></section>}
 {categoryTab==='categories'&&<section className="panel"><div className="section-head"><div><h2>Categories</h2><p className="muted">Limits are set on expense categories in Budgets.</p></div>{data.user.budget_member&&<Button onClick={()=>setCreating(true)}><Plus size={16}/>Add category</Button>}</div>
 <ListStatus list={categoryList}/>{!categoryList.loading&&!categoryList.items.length?<Empty title="Create your first categories">Create categories for the income and expenses you track.</Empty>:categoryList.items.map(c=><div className="classification-group-entry" key={c.id}><button type="button" className="line classification-category-row" key={c.id} title={'View transactions for '+c.name} onClick={()=>viewTransactions({category:String(c.id)})}><span>{c.name}{c.archived?' · Archived':''}</span><span className="toolbar-actions"><Badge>{c.kind==='expense'?'Expense':'Income'}</Badge><ChevronRight size={16} aria-hidden="true"/></span></button>{data.user.budget_member&&<Button variant="quiet" aria-label={'Edit '+c.name} onClick={()=>setCategoryEdit(c)}><Pencil size={16}/></Button>}</div>)}<ListNavigation list={categoryList}/></section>}
 </div></div>
 {spendingEdit&&<SpendingGroupEditor group={spendingEdit} notify={notify} onClose={()=>setSpendingEdit(null)} onDone={()=>{setSpendingEdit(null);refresh()}}/>}
 {creating&&<Modal title="Add category" onClose={()=>setCreating(false)}><Form onSubmit={async e=>{e.preventDefault();const body:Record<string,unknown>={name,kind};if(await run(()=>api('/categories','POST',body),'Category created',message=>{if(message==='Category already exists'){setNameError(message);return true}return false})){setCreating(false);setName('');refresh()}}}><Field label="Category name" serverError={nameError}><input required maxLength={80} value={name} onChange={e=>{setName(e.target.value);setNameError('')}}/></Field><Field label="Type"><select value={kind} onChange={e=>{setKind(e.target.value)}}><option value="expense">Expense (refunds reduce spending)</option><option value="income">Income</option></select></Field><Button type="submit" variant="primary" loading={busy} disabled={busy}>Create category</Button></Form></Modal>}

 </>
}
export function Budgets({data,refresh,notify,revision,period,account,onDashboard}:PageProps&{period:string;account:string;onDashboard:(id:number)=>void}){
 const {openTransaction,viewTransactions}=useTransactionAccess()
 const[budgetTab,setBudgetTab]=useState('periods')
 const[rebalance,setRebalance]=useState<Row|null>(null)
 const[editing,setEditing]=useState<Row|null>(null),[preview,setPreview]=useState<Row|null>(null),[limits,setLimits]=useState<Row|null>(null)
 const{busy,run}=useTask(notify)
 const periods=usePagedList('/periods',revision)
 const selectedPeriod=data.periods.find(p=>String(p.id)===period)
 const visiblePeriods=selectedPeriod&&!periods.items.some(p=>p.id===selectedPeriod.id)?[selectedPeriod,...periods.items]:periods.items
 const[previewPage,setPreviewPage]=useState(0)
 const startEdit=(p:Row)=>{setEditing({...p});setPreview(null);setPreviewPage(0)}
 const update=(key:string,value:string)=>{setEditing(v=>v?{...v,[key]:value}:null);setPreview(null);setPreviewPage(0)}
 const payload=()=>({name:editing!.name,start_date:editing!.start_date,end_date:editing!.end_date,version:editing!.version||0,preview_token:preview?.preview_token||''})
 return <>
 <Tabs id="budgets" label="Budget workspace" items={[{id:'periods',label:'Budget periods'},{id:'trends',label:'Trends & reports'}]} value={budgetTab} onChange={setBudgetTab}/>
 <div role="tabpanel" id="budgets-panel-periods" aria-labelledby="budgets-tab-periods" hidden={budgetTab!=='periods'}><div className="toolbar"><p className="muted">Set limits for each spending group and category.</p><Button variant="primary" onClick={()=>startEdit({...data.next,version:0})}><Plus size={17}/>New period</Button></div>
 <ListStatus list={periods}/>{!periods.loading&&!visiblePeriods.length?<section className="panel"><Empty title="No budget periods">Create your first period to start budgeting.</Empty></section>:visiblePeriods.map(p=><section className="panel" key={p.id}><div className="section-head"><div><h2><button type="button" className="transaction-link" title={'View transactions for '+p.name} onClick={()=>viewTransactions({period:String(p.id)})}>{p.name}</button> {String(p.id)===period&&<Badge>Selected period</Badge>}</h2><p className="muted">{p.start_date} — {p.end_date}</p></div><div className="toolbar-actions"><Button variant="primary" onClick={()=>setLimits(p)}>Edit budgets</Button><Button variant="quiet" onClick={()=>onDashboard(p.id)}>View spending</Button><ActionMenu label={'Actions for '+p.name}><Button variant="quiet" onClick={()=>startEdit(p)}>Edit dates</Button><Button variant="quiet" onClick={()=>setRebalance(p)}>Rebalance</Button></ActionMenu></div></div>
 <div className="budget-total"><span>Total budget</span><strong>{money(p.target_total)}</strong></div>
 {p.group_budgets?.filter((g:Row)=>g.target_cents>0).map((g:Row)=><div className="line" key={g.id}><span>{g.name}</span><strong>{money(g.target_cents)}</strong></div>)}{!p.target_total&&<p className="footnote">No spending limits set yet.</p>}{p.group_budgets?.length===20&&<p className="footnote">Use Edit budgets to browse all groups and categories.</p>}</section>)}<ListNavigation list={periods}/></div>
 {editing&&<Modal title={editing.id?'Edit budget period':'New budget period'} onClose={()=>setEditing(null)}><Field label="Period name"><input required maxLength={100} value={editing.name||''} onChange={e=>update('name',e.target.value)}/></Field><div className="form-grid"><Field label="Start date"><input type="date" required value={editing.start_date||''} onChange={e=>update('start_date',e.target.value)}/></Field><Field label="End date (inclusive)" validate={value=>editing.start_date&&value<editing.start_date?'End date must be on or after the start date.':''}><input type="date" required value={editing.end_date||''} onChange={e=>update('end_date',e.target.value)}/></Field></div><p className="muted">Choose any date range. If periods overlap, transactions go into the period that starts later. Transactions in a gap need a period chosen manually. Periods you chose manually stay unchanged.</p>
 <Button loading={busy} disabled={busy} onClick={e=>{if(validateFields(e.currentTarget.closest('.modal-body')!))run(async()=>{setPreview(await api('/periods/'+(editing.id||'new')+'/preview?page=0&page_size=50','POST',payload()));setPreviewPage(0)})}}>Preview affected transactions</Button>
 {preview&&<div className="notice"><div><strong>{preview.total} transactions will move to a different budget period.</strong><p>{preview.manual_outside} transactions will keep their chosen period but fall outside its dates.</p><details><summary>View affected transactions</summary>{preview.affected.map((t:Row)=><button type="button" className="transaction-link" key={t.id} onClick={()=>openTransaction(t.id,()=>setPreview(null))}>#{t.id} · {t.date} · {t.from?data.periods.find(p=>p.id===t.from)?.name||t.from:'Unassigned'} → {t.to?data.periods.find(p=>p.id===t.to)?.name||'New period':'Unassigned'}</button>)}<Pagination page={previewPage} total={preview.total} size={50} loading={busy} onChange={page=>run(async()=>{const next=await api('/periods/'+(editing.id||'new')+'/preview?page='+page+'&page_size=50','POST',payload());setPreview(next);setPreviewPage(page)})}/></details></div></div>}
 <div className="editor-actions"><Button variant="primary" loading={busy} disabled={busy||!preview} onClick={async()=>{if(await run(()=>api('/periods'+(editing.id?'/'+editing.id:''),editing.id?'PUT':'POST',payload()),'Budget period saved')){setEditing(null);refresh()}}}>Save period</Button><Button onClick={()=>setEditing(null)}>Cancel</Button></div></Modal>}
 {rebalance&&<Rebalance period={rebalance} notify={notify} onClose={()=>setRebalance(null)} onDone={()=>{setRebalance(null);refresh()}}/>}
 <div role="tabpanel" id="budgets-panel-trends" aria-labelledby="budgets-tab-trends" hidden={budgetTab!=='trends'}>{budgetTab==='trends'&&<BudgetTrends data={data} refresh={refresh} revision={revision} notify={notify} period={period} account={account}/>}</div>
 {limits&&<Modal title={'Group budgets · '+limits.name} onClose={()=>setLimits(null)}><LimitEditor period={limits} notify={notify} refresh={refresh} revision={revision} onDone={()=>setLimits(null)}/></Modal>}

 </>
}
export function SettingsPage({data,revision,refresh,notify,theme,onTheme,section,onSectionChange,onAccounts,onTransactions}:PageProps&{onAccounts:()=>void;onTransactions:()=>void;theme:string;onTheme:(v:string)=>void;section:string;onSectionChange:(v:string)=>void}){
 const[workspaceName,setWorkspaceName]=useState(data.branding.display_name),[brandingVersion,setBrandingVersion]=useState(data.branding.version),[brandingError,setBrandingError]=useState('')
 const[settingsLoading,setSettingsLoading]=useState(true)
 const[startDay,setStartDay]=useState('20'),[users,setUsers]=useState<Row[]>([]),[backups,setBackups]=useState<Row>({items:[]}),[manageAccounts,setManageAccounts]=useState<Row[]>([])
 const userList=usePagedList(data.user.admin?'/users':'',revision),grantList=usePagedList(data.user.admin?'/grants':'',revision)
 const[editUser,setEditUser]=useState<Row|null>(null);const[addUser,setAddUser]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[member,setMember]=useState(true),[admin,setAdmin]=useState(false)
 const[grantUser,setGrantUser]=useState(''),[grantAccount,setGrantAccount]=useState(''),[role,setRole]=useState('viewer')
 const[oldPassword,setOldPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[oldPasswordError,setOldPasswordError]=useState(''),[userNameError,setUserNameError]=useState('')
 useEffect(()=>setUserNameError(''),[addUser,editUser?.id])
 const{busy,run}=useTask(notify)
 useEffect(()=>{let alive=true;setSettingsLoading(true);Promise.all([data.user.budget_member?api('/settings'):Promise.resolve({start_day:20}),data.user.admin?api('/users?page=0&page_size=100'):Promise.resolve([]),data.user.admin?Promise.resolve({items:[]}):Promise.resolve([]),data.user.admin?api('/backups'):Promise.resolve({items:[]}),data.user.admin?api('/accounts/manage?page=0&page_size=100'):Promise.resolve([])]).then(([s,u,_g,b,a])=>{if(alive){setStartDay(String(s.start_day));setUsers(u.items||[]);setBackups(b);setManageAccounts(a.items||[])}}).catch(e=>alive&&notify(e.message,true)).finally(()=>alive&&setSettingsLoading(false));return()=>{alive=false}},[revision])
 const tabs=[{id:'general',label:'General'},...(data.user.admin?[{id:'banking',label:'Banking'},{id:'accounts',label:'Accounts'},{id:'access',label:'Users & access'},{id:'backups',label:'Backups'},{id:'network',label:'Network'}]:[]),{id:'mcp',label:'MCP'},{id:'security',label:'Security'}]
 const active=tabs.some(tab=>tab.id===section)?section:'general'
 const panel=(id:string)=>({id:'settings-panel-'+id,role:'tabpanel','aria-labelledby':'settings-tab-'+id,hidden:active!==id,className:'settings-panel'})
 return <>
 {settingsLoading&&<Loading>Loading settings</Loading>}
 <Tabs id="settings" label="Settings sections" items={tabs} value={active} onChange={onSectionChange}/>
 <div {...panel('general')}><div className="general-settings-grid">
 {data.user.admin&&<section className="panel"><h2>Workspace name</h2><Form onSubmit={async()=>{if(await run(async()=>{const result=await api('/branding','PUT',{display_name:workspaceName,version:brandingVersion});setWorkspaceName(result.display_name);setBrandingVersion(result.version)},'Workspace name saved',message=>{if(message.startsWith('Use a workspace name')){setBrandingError(message);return true}return false}))refresh()}}><Field label="Display name" hint="Shown to signed-in users. The sign-in screen keeps a generic name." serverError={brandingError} validate={value=>Array.from(value.trim()).length<2||Array.from(value.trim()).length>60?'Use a workspace name of 2–60 characters':''}><input required value={workspaceName} onChange={e=>{setWorkspaceName(e.target.value);setBrandingError('')}}/></Field><div className="editor-actions settings-save-actions"><Button type="submit" variant="primary" loading={busy} disabled={busy}>Save workspace name</Button><Button variant="quiet" loading={busy} disabled={busy} onClick={async()=>{if(await run(async()=>{const b=await api('/branding');setWorkspaceName(b.display_name);setBrandingVersion(b.version);setBrandingError('')}))refresh()}}>Reload saved name</Button></div></Form></section>}
 <section className="panel"><h2>Preferences</h2><Field label="Appearance"><select value={theme} onChange={e=>onTheme(e.target.value)}><option value="system">Follow device</option><option value="light">Light</option><option value="dark">Dark</option></select></Field><div className="line"><span>Currency</span><strong>South African rand (ZAR)</strong></div><div className="line"><span>Budget timezone</span><strong>Africa/Johannesburg</strong></div>{data.user.budget_member&&<Form onSubmit={async e=>{e.preventDefault();if(await run(()=>api('/settings','PUT',{start_day:Number(startDay)}),'Default updated; existing periods are unchanged'))refresh()}}><Field label="Default period start day" hint="Used for new periods. Days beyond a month’s length use its last day."><input type="number" min={1} max={31} required value={startDay} onChange={e=>setStartDay(e.target.value)}/></Field><Button type="submit" loading={busy} disabled={busy}>Save default</Button></Form>}</section>
 </div></div>
 <div {...panel('mcp')}>{active==='mcp'&&<MCPSettings notify={notify} refresh={refresh}/>}</div>
 <div {...panel('security')}>
 <section className="panel"><h2>Change your password</h2><Form onSubmit={async e=>{e.preventDefault();if(await run(()=>api('/password','POST',{old_password:oldPassword,new_password:newPassword}),'Password changed; other sessions signed out',message=>{if(message==='Current password is incorrect'){setOldPasswordError(message);return true}return false})){setOldPassword('');setNewPassword('')}}}><Field label="Current password" serverError={oldPasswordError}><input type="password" autoComplete="current-password" required value={oldPassword} onChange={e=>{setOldPassword(e.target.value);setOldPasswordError('')}}/></Field><Field label="New password" validate={passwordError}><input type="password" autoComplete="new-password" required value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></Field><Button type="submit" loading={busy} disabled={busy}>Change password</Button></Form></section>
 </div>
 {data.user.admin&&<>
 <div {...panel('banking')}>{active==='banking'&&<FNBConnection onAccounts={onAccounts} onTransactions={onTransactions} data={data} revision={revision} refresh={refresh} notify={notify}/>}</div>
 <div {...panel('network')}>{active==='network'&&<NetworkSettings data={data} revision={revision} refresh={refresh} notify={notify}/>}</div>
 <div {...panel('accounts')}>{active==='accounts'&&<section className="panel"><h2>Manage your accounts</h2><p className="muted">Account discovery, names, sharing, balances and visibility are together on Accounts.</p><Button onClick={onAccounts}>Open Accounts</Button></section>}</div>
 <div {...panel('access')}>
 <section className="panel"><div className="section-head"><h2>Users</h2><Button onClick={()=>setAddUser(true)}><Plus size={16}/>Add user</Button></div><ListStatus list={userList}/>{userList.items.map(u=><div className="line user-row" key={u.id}><strong>{u.username}</strong><div className="row-meta">{u.admin===1&&<Badge>Administrator</Badge>}{u.budget_member===1&&<Badge>Household member</Badge>}{u.disabled===1&&<Badge tone="bad">Disabled</Badge>}<Button variant="quiet" aria-label={'Edit user '+u.username} onClick={()=>setEditUser({...u})}><Pencil size={16}/></Button></div></div>)}<ListNavigation list={userList}/><p className="footnote">Household members can edit shared accounts and budgets. Recover a password using the offline administrator command.</p></section>
 <section className="panel"><h2>Account access</h2><p className="muted">Household members automatically have editor access to household accounts. Use the settings below to give users access to individual accounts.</p><Form onSubmit={async e=>{e.preventDefault();if(await run(()=>api('/grants','PUT',{user_id:Number(grantUser),account_id:Number(grantAccount),role}),'Account access updated'))refresh()}}><div className="form-grid"><PagedSelect url="/users" label="User" nameKey="username" required value={grantUser} options={users} onChange={setGrantUser} revision={revision}/><PagedSelect url="/accounts/manage" label="Account" optionLabel={a=>a.name+(a.household?' · Household':' · Private')} required value={grantAccount} options={manageAccounts} onChange={setGrantAccount} revision={revision}/></div><Field label="Permission"><select value={role} onChange={e=>setRole(e.target.value)}><option value="viewer">Viewer</option><option value="editor">Editor (can update transactions)</option><option value="">Remove individual access</option></select></Field><Button loading={busy} disabled={busy} type="submit">Update access</Button></Form><ListStatus list={grantList}/>{grantList.items.map(g=><div className="line" key={g.user_id+'-'+g.account_id}><span>{g.username} · {g.account_name}</span><Badge>{g.role}</Badge></div>)}<ListNavigation list={grantList}/></section>
 </div>
 <div {...panel('backups')}>
 <section className="panel"><div className="section-head"><h2>Backups</h2><Button loading={busy} disabled={busy} onClick={async()=>{if(await run(()=>api('/backups','POST'),'Backup completed and integrity checked'))refresh()}}>Back up now</Button></div><p className="muted">A backup is made every 24 hours. The latest 14 successful backups are kept.</p>{backups.error&&<p role="alert" className="error-text">{backups.error}</p>}{backups.items.length?<p>Last successful backup: <strong>{backups.items[0].created_at} UTC</strong></p>:<p>No successful backup recorded yet.</p>}<p className="footnote">Restore with the service stopped, using the documented command. A restore preserves the previous database and signs out old sessions. Store backup copies on a separate device.</p></section>
 </div>
 </>}
 {editUser&&<Modal title="Edit user" onClose={()=>setEditUser(null)}><Form onSubmit={async e=>{e.preventDefault();if(await run(()=>api('/users/'+editUser.id,'PUT',{username:editUser.username,admin:!!editUser.admin,budget_member:!!editUser.budget_member,disabled:!!editUser.disabled,version:editUser.version}),'User updated',message=>{if(message==='Username already exists'){setUserNameError(message);return true}return false})){setEditUser(null);refresh()}}}><Field label="Username" validate={usernameError} serverError={userNameError}><input required minLength={2} maxLength={80} value={editUser.username} onChange={e=>{setEditUser({...editUser,username:e.target.value});setUserNameError('')}}/></Field><label className="check"><input type="checkbox" checked={!!editUser.budget_member} onChange={e=>setEditUser({...editUser,budget_member:e.target.checked})}/>Household budget member</label><label className="check"><input type="checkbox" checked={!!editUser.admin} onChange={e=>setEditUser({...editUser,admin:e.target.checked})}/>Administrator</label><label className="check"><input type="checkbox" checked={!!editUser.disabled} onChange={e=>setEditUser({...editUser,disabled:e.target.checked})}/>Disable sign-in and sign out this user</label><Button variant="primary" type="submit" loading={busy} disabled={busy}>Save user</Button></Form></Modal>}
 {addUser&&<Modal title="Add user" onClose={()=>setAddUser(false)}><Form onSubmit={async e=>{e.preventDefault();if(await run(()=>api('/users','POST',{username,password,admin,budget_member:member}),'User created',message=>{if(message==='Username already exists'){setUserNameError(message);return true}return false})){setAddUser(false);setUsername('');setPassword('');refresh()}}}><Field label="Username" validate={usernameError} serverError={userNameError}><input required minLength={2} maxLength={80} value={username} onChange={e=>{setUsername(e.target.value);setUserNameError('')}}/></Field><Field label="Initial password" validate={passwordError}><input type="password" autoComplete="new-password" required value={password} onChange={e=>setPassword(e.target.value)}/></Field><label className="check"><input type="checkbox" checked={member} onChange={e=>setMember(e.target.checked)}/>Household budget member</label><label className="check"><input type="checkbox" checked={admin} onChange={e=>setAdmin(e.target.checked)}/>Administrator</label><Button variant="primary" loading={busy} disabled={busy} type="submit">Create user</Button></Form></Modal>}
 </>
}
