import {Field} from './ui'
import type {Row} from './shared/types'
export const capabilityLabels:Record<string,string>={manage_merchants:'Create/edit merchants and logos',manage_merchant_rules:'Create/edit merchant naming rules',delete_merchant_rule:'Delete merchant naming rules',assign_merchants:'Assign or clear transaction merchants',assign_missing:'Fill missing categories',recategorize:'Change assigned categories',financial_edit:'Edit amounts, dates, descriptions, notes, splits, groups and periods',create_category:'Create categories',create_rule:'Create rules',update_rule:'Edit rules',delete_rule:'Delete rules',update_budget:'Edit shared budget limits',change_seen:'Mark your transactions seen or unseen'}
export const reviewPermissions=()=>({schema_version:1,preset:'review',automatic_approval:{},capabilities:Object.fromEntries(Object.keys(capabilityLabels).map(k=>[k,false])),constraints:{account_ids:[] as number[],selected_accounts:false,missing_categories_only:false,constrained_rules:false}})
export function selectPreset(p:Row,preset:string):Row{
 const capabilities=Object.fromEntries(Object.keys(capabilityLabels).map(k=>[k,preset==='finance'&&!['change_seen','manage_merchants','manage_merchant_rules','delete_merchant_rule','assign_merchants'].includes(k)||preset==='categorization'&&['assign_missing','create_rule'].includes(k)]))
 return {...p,preset,automatic_approval:{},capabilities:preset==='custom'?p.capabilities:capabilities,constraints:{...p.constraints,selected_accounts:preset==='categorization'||p.constraints.selected_accounts,missing_categories_only:preset==='custom'?p.constraints.missing_categories_only:preset==='categorization',constrained_rules:preset==='custom'?p.constraints.constrained_rules:preset==='categorization'}}
}
export function PermissionSummary({value,accounts}:{value:Row;accounts:Row[]}){
 const ids:number[]=value.constraints.account_ids||[],granted=Object.keys(capabilityLabels).filter(k=>value.capabilities[k]),automatic=Object.keys(capabilityLabels).filter(k=>value.automatic_approval?.[k])
 return <div><p>{value.read_merchants?'Merchant names, rules and requested logos can be read.':'Merchant metadata is excluded.'}</p><p>{granted.length?'Can propose: '+granted.map(k=>capabilityLabels[k].toLowerCase()).join('; ')+'.':'Review only: no change proposals.'}</p><p className="footnote">{ids.length?'Reads and proposals limited to: '+ids.map(id=>accounts.find(a=>a.id===id)?.name||'Account #'+id).join(', ')+'.':'Reads cover all currently accessible accounts.'} {value.constraints.missing_categories_only?'Category changes can only fill missing categories. ':''}{value.constraints.constrained_rules?'Rule creation is limited to selected accounts and a bounded contains-description pattern. ':''}{automatic.length?'Automatically approves: '+automatic.map(k=>capabilityLabels[k].toLowerCase()).join('; ')+'. Other change types require manual approval.':'Every proposed change needs manual approval.'}</p></div>
}
export function MCPPermissionFields({value,onChange,accounts,canPropose}:{value:Row;onChange:(p:Row)=>void;accounts:Row[];canPropose:boolean}){
 const ids:number[]=value.constraints.account_ids||[],scopeError=value.constraints.selected_accounts&&!ids.length?'Select at least one account.':value.constraints.constrained_rules&&value.capabilities.create_rule&&!ids.length?'Select at least one account for constrained rules.':ids.length&&value.capabilities.update_budget?'Shared budget editing requires all accessible accounts.':''
 const merchantError=['manage_merchants','manage_merchant_rules','delete_merchant_rule','assign_merchants'].some(k=>value.capabilities[k])&&!value.read_merchants?'Enable merchant reads for merchant changes.':''
 const constraintError=merchantError||((value.constraints.missing_categories_only&&(value.capabilities.financial_edit||value.capabilities.recategorize))?'Missing-category-only access cannot include financial edits or recategorization.':(value.constraints.constrained_rules&&(value.capabilities.update_rule||value.capabilities.delete_rule))?'Constrained rules permit creation only.':'')
 const constraint=(key:string,v:boolean)=>onChange({...value,constraints:{...value.constraints,[key]:v}})
 return <>
 <Field label="Permission level"><select value={value.preset} onChange={e=>onChange(selectPreset(value,e.target.value))}><option value="review">Review only</option>{canPropose&&<><option value="categorization">Categorisation proposals</option><option value="finance">Finance editing proposals</option><option value="custom">Custom permissions</option></>}{value.preset==='legacy_finance'&&<option value="legacy_finance" disabled>Existing finance permissions</option>}</select></Field>
 <section className="permission-scope"><h3>Read access and account scope</h3>
  <label className="check"><input type="checkbox" checked={!!value.read_merchants} onChange={e=>onChange({...value,read_merchants:e.target.checked})}/>Read merchant names, naming rules and logos</label>
  <Field label="Account access" validate={()=>scopeError} hint="Selected accounts limit both reads and proposals. Current account permissions still apply. Global merchant changes require all accessible accounts."><select value={value.constraints.selected_accounts||ids.length?'selected':'all'} onChange={e=>onChange({...value,constraints:{...value.constraints,selected_accounts:e.target.value==='selected',account_ids:e.target.value==='all'?[]:ids}})}><option value="all">All accessible accounts</option><option value="selected">Selected accounts</option></select></Field>
  {(value.constraints.selected_accounts||ids.length>0)&&<fieldset><legend>Selected accounts</legend>{accounts.map(a=><label className="check" key={a.id}><input type="checkbox" checked={ids.includes(a.id)} onChange={e=>onChange({...value,constraints:{...value.constraints,account_ids:e.target.checked?[...ids,a.id]:ids.filter(id=>id!==a.id)}})}/>{a.name}{!a.can_edit?' (view only)':''}</label>)}</fieldset>}
 </section>
 {value.preset==='custom'&&canPropose&&<section className="permission-changes"><h3>Allowed changes</h3><p className="footnote">These permissions allow proposals. Automatic approval is configured separately below.</p><div className="permission-groups">{[
  ['Categorisation',['assign_missing','recategorize','create_category']],
  ['Merchants',['manage_merchants','manage_merchant_rules','delete_merchant_rule','assign_merchants']],
  ['Rules and budgets',['create_rule','update_rule','delete_rule','update_budget']],
  ['Transaction details',['financial_edit','change_seen']]
  ].map(([title,keys])=><fieldset key={title as string}><legend>{title}</legend>{(keys as string[]).map(key=><label className="check" key={key}><input type="checkbox" checked={!!value.capabilities[key]} onChange={e=>onChange({...value,capabilities:{...value.capabilities,[key]:e.target.checked},automatic_approval:{...value.automatic_approval,[key]:e.target.checked?!!value.automatic_approval?.[key]:false}})}/>{capabilityLabels[key]}</label>)}</fieldset>)}</div></section>}
 {value.preset==='custom'&&<section className="permission-scope"><h3>Restrictions</h3>
  <label className="check"><input type="checkbox" checked={value.constraints.missing_categories_only} onChange={e=>constraint('missing_categories_only',e.target.checked)}/>Only fill missing categories</label>
  <label className="check"><input type="checkbox" checked={value.constraints.constrained_rules} onChange={e=>constraint('constrained_rules',e.target.checked)}/>Only create constrained rules in selected accounts</label>
  {constraintError&&<p className="field-error" role="alert">{constraintError}</p>}
 </section>}
 {canPropose&&Object.values(value.capabilities).some(Boolean)&&<details className="details permission-automatic"><summary>Automatic approval · {Object.values(value.automatic_approval||{}).filter(Boolean).length} enabled</summary><fieldset><legend>Automatically approve selected changes</legend><p className="footnote">Enable only the change types this agent may approve without asking you. Proposals still record exact changes; applying them checks current access and versions. Combined changes require every relevant type to be enabled.</p>{Object.entries(capabilityLabels).filter(([key])=>value.capabilities[key]).map(([key,label])=><label className="check" key={key}><input type="checkbox" aria-label={'Automatically approve: '+label} checked={!!value.automatic_approval?.[key]} onChange={e=>onChange({...value,automatic_approval:{...value.automatic_approval,[key]:e.target.checked}})}/>{label}</label>)}</fieldset></details>}
 <div className="permission-summary"><h3>Permission summary</h3><PermissionSummary value={value} accounts={accounts}/></div>
 </>
}
