import {MerchantAvatar} from './MerchantAvatar'
import {useTransactionAccess} from './TransactionAccess'
import {useEffect,useState} from 'react'
import {api} from './api'
import {Button,Field,Loading,Empty,Badge,Form,Modal} from './ui'
import {useTask,type PageProps,type Row} from './App'
import {MCPPermissionFields,PermissionSummary,capabilityLabels} from './MCPPermissions'

export function MCPSettings({notify}:Pick<PageProps,'notify'|'refresh'>){
 const {openTransaction}=useTransactionAccess()
 const[state,setState]=useState<Row|null>(null),[editing,setEditing]=useState<Row|null>(null),[draft,setDraft]=useState<Row|null>(null),[consent,setConsent]=useState(false),[selected,setSelected]=useState<string[]>([])
 const{busy,run}=useTask(notify)
 const load=async()=>{const next=await api('/mcp/settings');setState(next);setSelected(ids=>ids.filter(id=>next.proposals.some((p:Row)=>p.id===id&&p.status==='pending')))}
 useEffect(()=>{let alive=true;api('/mcp/settings').then(s=>alive&&setState(s)).catch(e=>alive&&notify(e.message,true));return()=>{alive=false}},[])
 const endpoint=state?.endpoint||''
 const copy=(value:string)=>run(async()=>{await navigator.clipboard.writeText(value)},'Copied')
 const pending:Row[]=state?.proposals.filter((p:Row)=>p.status==='pending')||[]
 const approveBatch=(ids:string[])=>run(async()=>{await api('/mcp/proposals/batch','POST',{proposal_ids:ids,approve:true});await load()},`${ids.length} proposals approved; your agents can now apply them`)
 return <>
 <section className="panel"><h2>MCP agent connection</h2><p className="muted">Connect an agent to your accessible transactions, categories, rules and budget. Account numbers, banking credentials, source references, provenance and notes are excluded. Account labels are generic; long numbers, email addresses and URLs in descriptions are redacted.</p><p className="footnote">Amounts, dates and merchant descriptions still contain financial information. Use an agent you trust. Names and other personal text inside descriptions may remain.</p>
 {!state?<Loading>Loading MCP settings</Loading>:<><Field label="MCP server endpoint"><input readOnly value={endpoint}/></Field><div className="editor-actions"><Button onClick={()=>copy(endpoint)}>Copy endpoint</Button></div><p className="footnote">Share this link with your agent. It contains the setup instructions; you sign in in your browser and approve the connection. Your agent needs remote MCP with OAuth support.</p></>}
 </section>
 <section className="panel"><div className="section-head"><h2>Connected agents</h2><Button disabled={busy} onClick={()=>run(load)}>Refresh connections</Button></div><p className="muted">Manage each agent’s access and approval settings. Revoking disconnects the agent and removes its pending proposals.</p>
 {state&&!state.connections.length&&<Empty title="No connected agents">Connect using the endpoint above, then approve the browser request.</Empty>}
 {state?.connections.map((t:Row)=>{
 const granted=Object.keys(capabilityLabels).filter(k=>t.permissions.capabilities[k]),automatic=granted.filter(k=>t.permissions.automatic_approval?.[k]),ids:number[]=t.permissions.constraints.account_ids||[],expired=t.expires_at*1000<=Date.now()
 const accessLabel=granted.length?({categorization:'Categorisation',finance:'Finance editing',legacy_finance:'Finance editing'} as Record<string,string>)[t.permissions.preset]||'Custom permissions':'Read-only'
 return <article className="mcp-proposal mcp-access-row" key={t.id}>
 <div className="mcp-agent-header"><div className="mcp-agent-name"><h3>{t.name}</h3>{expired&&<Badge tone="bad">Expired</Badge>}</div><div className="editor-actions"><Button disabled={busy||expired} onClick={()=>{setEditing(t);setDraft({...t.permissions,preset:t.permissions.preset==='legacy_finance'?'custom':t.permissions.preset});setConsent(false)}}>Edit permissions</Button><Button disabled={busy} onClick={()=>run(async()=>{await api('/mcp/connections/'+t.id,'DELETE');await load()},'MCP connection revoked')}>Revoke</Button></div></div>
 <dl className="mcp-agent-summary"><div><dt>Access</dt><dd>{accessLabel}</dd></div><div><dt>Accounts</dt><dd>{ids.length===1?state.accounts.find((a:Row)=>a.id===ids[0])?.name||'1 selected account':ids.length?`${ids.length} selected accounts`:'All accessible accounts'}</dd></div><div><dt>Approval</dt><dd>{!granted.length?'No changes allowed':automatic.length?`Automatic for ${automatic.length} change ${automatic.length===1?'type':'types'}`:'Manual approval'}</dd></div></dl>
 <p className="footnote mcp-agent-activity">{t.last_used_at?'Last used '+new Date(t.last_used_at*1000).toLocaleString('en-ZA'):'Not used yet'} · {expired?'Expired':'Expires'} {new Date(t.expires_at*1000).toLocaleDateString('en-ZA')}{!t.client_id?' · Legacy connection':''}</p>
 <details className="mcp-agent-details"><summary>View permission details</summary><PermissionSummary value={t.permissions} accounts={state.accounts}/></details>
 </article>
 })}
 </section>
 <section className="panel"><div className="section-head"><h2>Agent change proposals</h2><Button disabled={busy} loading={busy} onClick={()=>run(load)}>Refresh proposals</Button></div><p className="muted">Select proposals to approve together, or approve all currently shown pending proposals. Automatic approval applies only to the types enabled for that agent. Proposals expire after one hour. Approval authorizes only these changes; the agent then applies them with current permissions and version checks. Categorized transactions become Accepted automatically.</p>
 {state&&!state.proposals.length&&<Empty title="No pending proposals">Ask your agent to prepare a change, then refresh this list.</Empty>}
 {pending.length>0&&<div className="editor-actions"><label className="check"><input type="checkbox" aria-label="Select all pending proposals" disabled={busy} checked={pending.every(p=>selected.includes(p.id))} onChange={e=>setSelected(e.target.checked?pending.map(p=>p.id):[])}/>Select all pending proposals</label><span>{selected.length} selected</span><Button variant="primary" disabled={busy||!selected.length} onClick={()=>approveBatch(selected)}>Approve selected ({selected.length})</Button><Button disabled={busy} onClick={()=>approveBatch(pending.map(p=>p.id))}>Approve all shown ({pending.length})</Button></div>}
 {state?.proposals.map((p:Row)=><article className="mcp-proposal" key={p.id}><div className="section-head"><div>{p.status==='pending'&&<label className="check"><input type="checkbox" aria-label={'Select proposal '+p.id.slice(0,8)} disabled={busy} checked={selected.includes(p.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,p.id]:ids.filter(id=>id!==p.id))}/>Select proposal</label>}<h3>{p.operation.replaceAll('_',' ')} · {p.token_name}</h3><small>Expires {new Date(p.expires_at*1000).toLocaleTimeString('en-ZA')} · Proposal {p.id.slice(0,8)}</small></div><Badge>{p.status==='approved'&&p.payload.automatic_approval?'Automatically approved':p.status}</Badge></div><details><summary>Inspect exact changes (amounts in cents)</summary>{p.payload.transactions?.map((t:Row)=><div key={t.id}><button type="button" className="transaction-link" onClick={()=>openTransaction(t.id)}><strong>Transaction #{t.id}</strong><span> · {t.before.description}</span></button><div className="form-grid"><div><strong>Before</strong><pre className="mcp-code">{JSON.stringify(t.before,null,2)}</pre></div><div><strong>After</strong><pre className="mcp-code">{JSON.stringify(t.after,null,2)}</pre></div></div></div>)}{!p.payload.transactions?.length&&<>{p.payload.before&&<><strong>Before</strong><pre className="mcp-code">{JSON.stringify(p.payload.before,(key,value)=>key==='logo_data'&&value?'[Current local logo]':value,2)}</pre></>}{p.payload.seen_states&&<><strong>Current personal seen state</strong><pre className="mcp-code">{JSON.stringify(p.payload.seen_states,null,2)}</pre></>}{(p.payload.change.merchant?.logo_data||p.payload.change.merchant_rule?.merchant_logo)&&<div className="merchant-identity"><MerchantAvatar name={p.payload.change.merchant?.name||'Merchant'} logo={p.payload.change.merchant?.logo_data||p.payload.change.merchant_rule?.merchant_logo}/><span>Proposed merchant logo</span></div>}{p.payload.budget_after&&<><strong>After · exact group budgets and carry-forward</strong><pre className="mcp-code">{JSON.stringify(p.payload.budget_after,null,2)}</pre></>}<strong>Requested change</strong><pre className="mcp-code">{JSON.stringify(p.payload.change,(key,value)=>['logo_data','merchant_logo'].includes(key)&&value?'[Local image shown above]':value,2)}</pre></>}</details>{p.status==='pending'&&<div className="editor-actions"><Button variant="primary" disabled={busy} onClick={()=>run(async()=>{await api('/mcp/proposals/'+p.id,'POST',{approve:true});await load()},'Proposal approved; your agent can now apply it')}>Approve exact changes</Button><Button disabled={busy} onClick={()=>run(async()=>{await api('/mcp/proposals/'+p.id,'POST',{approve:false});await load()},'Proposal rejected')}>Reject</Button></div>}</article>)}
 </section>
 {editing&&draft&&<Modal size="wide" title={'Permissions for '+editing.name} onClose={()=>{if(!busy)setEditing(null)}}><Form onSubmit={()=>run(async()=>{await api('/mcp/connections/'+editing.id+'/permissions','PUT',{version:editing.permission_version,permissions:draft,consent});await load();setEditing(null)},'Connection permissions updated')}>
 <MCPPermissionFields value={draft} onChange={v=>{setDraft(v);setConsent(false)}} accounts={state?.accounts||[]} canPropose={!!editing.can_write}/>
 {!editing.can_write&&<p className="footnote">To allow proposals, start a new connection from the agent and approve proposal access.</p>}
 <Field label="Confirm permissions" validate={()=>consent?'':'Confirm the permissions shown above.'}><select value={consent?'confirmed':''} onChange={e=>setConsent(e.target.value==='confirmed')}><option value="">Review permissions above</option><option value="confirmed">I approve these connection permissions</option></select></Field>
 <div className="editor-actions"><Button type="submit" variant="primary" disabled={busy} loading={busy}>Save permissions</Button><Button disabled={busy} onClick={()=>setEditing(null)}>Cancel</Button></div>
 </Form></Modal>}
 </>
}
